import React, { useMemo } from 'react';
import { B2Badge, B2Button, B2PageHeader, B2SectionHeader, B2StatCard, B2Surface } from '../components/B2UI.jsx';
import { B2DataState, B2Status } from '../components/B2Data.jsx';
import { dataSourceLabel, dataSourceTone, useBrianV2Data } from '../data/BrianV2DataContext.jsx';
import './B2SystemWorkspaces.css';

const openV1 = (route = 'assessment-core') => window.open(`/#/${route}`, '_blank', 'noopener,noreferrer');
const safeArray = (value) => Array.isArray(value) ? value : [];
const text = (value, fallback = '') => String(value ?? '').trim() || fallback;

export default function B2Assessment() {
  const { homeroom, resources, sources, loading } = useBrianV2Data();
  const records = safeArray(homeroom?.workspace?.learningRecords);
  const assessmentResources = useMemo(() => safeArray(resources?.items).filter((item) => item.type === 'Đề kiểm tra'), [resources]);
  const assessmentNames = useMemo(() => new Set(records.map((item) => text(item.assessment || item.assessmentType || item.type)).filter(Boolean)), [records]);
  const studentIds = useMemo(() => new Set(records.map((item) => text(item.studentId || item.student_id)).filter(Boolean)), [records]);
  const scored = records.filter((item) => Number.isFinite(Number(item.score)));
  const average = scored.length ? scored.reduce((sum, item) => sum + Number(item.score), 0) / scored.length : null;
  const recent = [...records].sort((a,b)=>String(b.updatedAt||b.recordedAt||b.date||'').localeCompare(String(a.updatedAt||a.recordedAt||a.date||''))).slice(0,12);

  return <>
    <B2PageHeader eyebrow="TEACH · ASSESSMENT CORE" title="Đánh giá & ngân hàng đề" description="Workspace V2 đọc learning records của lớp và các học liệu đánh giá hiện hữu. Việc tạo blueprint, ngân hàng câu hỏi, mã đề và ghi điểm vẫn mở Assessment Core V1 cho đến khi write bridge được duyệt." actions={<><B2Button variant="primary" onClick={()=>openV1('assessment-core')}>Mở Assessment Core V1 ↗</B2Button><B2Button onClick={()=>openV1('homeroom')}>Mở sổ điểm V1 ↗</B2Button></>} aside={<B2Badge tone={dataSourceTone(sources.homeroom)}>{dataSourceLabel(sources.homeroom)}</B2Badge>} />
    <section className="b2-system-stats"><B2StatCard label="Bản ghi điểm" value={records.length} meta="learning records" tone="blue" icon="▥"/><B2StatCard label="Đợt / bài" value={assessmentNames.size} meta="assessment labels" tone="green" icon="◇"/><B2StatCard label="Học sinh có điểm" value={studentIds.size} meta={homeroom?.className||'lớp hiện tại'} tone="violet" icon="◎"/><B2StatCard label="Học liệu kiểm tra" value={assessmentResources.length} meta="Resource Library" tone="cyan" icon="▤"/></section>
    <section className="b2-system-grid"><div className="b2-system-stack"><div><B2SectionHeader eyebrow="RECENT RECORDS" title="Điểm và đánh giá gần đây" description={average===null?'Chưa có điểm số đủ để tính trung bình.':`Trung bình các bản ghi có số: ${average.toFixed(2)}`}/>{loading?<B2DataState type="loading"/>:recent.length?<div className="b2-system-list">{recent.map((item,index)=><article key={item.id||`${item.studentId}-${index}`} className="b2-system-row"><div className="b2-system-row__copy"><strong>{text(item.studentName||item.fullName||item.name||item.studentId,'Học sinh')}</strong><small>{text(item.assessment||item.assessmentType||item.type,'Đánh giá')} · {text(item.subject,'Tiếng Anh')}</small><em>{text(item.period||item.recordedAt||item.date,'Chưa có thời điểm')}</em></div><div className="b2-system-row__meta"><B2Status tone={Number(item.score)>=8?'green':Number(item.score)<5?'red':'blue'}>{Number.isFinite(Number(item.score))?`${Number(item.score)} / ${Number(item.maxScore||10)}`:'Chưa có điểm'}</B2Status></div></article>)}</div>:<div className="b2-system-empty"><div><strong>Chưa có learning record</strong><p>Shadow UI không tạo điểm mẫu. Khi V1 có dữ liệu, danh sách này tự cập nhật qua Data Bridge.</p></div></div>}</div><div><B2SectionHeader eyebrow="ASSESSMENT RESOURCES" title="Học liệu dùng để kiểm tra"/><div className="b2-system-list">{assessmentResources.slice(0,8).map((item)=><article className="b2-system-row" key={item.id}><div className="b2-system-row__copy"><strong>{item.title}</strong><small>{item.description||item.meta||'Đề / bảng tính đánh giá'}</small><em>{item.category}</em></div><B2Badge tone="cyan">{item.status||'local'}</B2Badge></article>)}{!assessmentResources.length?<div className="b2-system-empty"><div><strong>Chưa có học liệu kiểm tra</strong></div></div>:null}</div></div></div><aside className="b2-system-stack"><B2Surface><B2SectionHeader eyebrow="WRITE COMMANDS" title="Tác vụ ghi dữ liệu"/><div className="b2-system-action-list"><button onClick={()=>openV1('assessment-core')}><span>＋</span><strong>Tạo ngân hàng / blueprint</strong><em>↗</em></button><button onClick={()=>openV1('assessment-core')}><span>▤</span><strong>Tạo mã đề</strong><em>↗</em></button><button onClick={()=>openV1('homeroom')}><span>◎</span><strong>Nhập / chỉnh điểm</strong><em>↗</em></button></div></B2Surface><B2Surface><B2SectionHeader eyebrow="DATA SOURCES" title="Nguồn đang đọc"/><div className="b2-system-source"><B2Badge tone={dataSourceTone(sources.homeroom)}>CLASS · {dataSourceLabel(sources.homeroom)}</B2Badge><B2Badge tone={dataSourceTone(sources.resources)}>RESOURCES · {dataSourceLabel(sources.resources)}</B2Badge></div></B2Surface></aside></section>
  </>;
}
