-- Brian English Studio V11.3.3 — Work Assignment Notification & File Response
-- Safe to rerun. Existing work items, comments and uploaded files are preserved.
begin;
create extension if not exists pgcrypto;

create table if not exists public.bes_schema_registry (
  component text primary key,
  version text not null,
  installed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create or replace function public.bes_v1133_is_leader(target_user uuid default auth.uid())
returns boolean
language plpgsql
stable
security definer
set search_path=public,auth,pg_temp
as $$
declare role_value text; jwt_role text;
begin
  if target_user is null then return false; end if;
  if to_regprocedure('public.bes_v1099_current_role(uuid)') is not null then
    execute 'select public.bes_v1099_current_role($1)' into role_value using target_user;
    if lower(coalesce(role_value,'')) in ('admin','department_head','head','ttcm','leader') then return true; end if;
  end if;
  if to_regclass('public.system_roles') is not null then
    select role into role_value from public.system_roles
    where user_id=target_user and active=true order by assigned_at desc nulls last limit 1;
    if lower(coalesce(role_value,'')) in ('admin','department_head','head','ttcm','leader') then return true; end if;
  end if;
  if to_regclass('public.profiles') is not null then
    begin
      execute 'select role from public.profiles where coalesce(id,user_id,profile_id)=$1 limit 1'
      into role_value using target_user;
      if lower(coalesce(role_value,'')) in ('admin','department_head','head','ttcm','leader') then return true; end if;
    exception when others then null;
    end;
  end if;
  jwt_role := lower(coalesce(
    auth.jwt()->'app_metadata'->>'role',
    auth.jwt()->'user_metadata'->>'role',
    auth.jwt()->>'role',''
  ));
  return jwt_role in ('admin','administrator','department_head','head','ttcm','leader');
exception when others then return false;
end $$;
grant execute on function public.bes_v1133_is_leader(uuid) to authenticated;

create table if not exists public.work_hub_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  item_type text not null default 'task',
  status text not null default 'draft',
  priority text not null default 'normal',
  created_by uuid not null default auth.uid(),
  owner_id uuid not null default auth.uid(),
  assignee_ids uuid[] not null default '{}',
  watcher_ids uuid[] not null default '{}',
  visibility text not null default 'restricted',
  start_at timestamptz,
  due_at timestamptz,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  completed_at timestamptz,
  reviewed_by uuid,
  source_module text not null default '',
  source_id text not null default '',
  attachments jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.work_hub_comments (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.work_hub_items(id) on delete cascade,
  author_id uuid not null default auth.uid(),
  body text not null,
  comment_type text not null default 'comment',
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.work_hub_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  item_id uuid references public.work_hub_items(id) on delete cascade,
  notification_type text not null default 'work_item',
  title text not null,
  body text not null default '',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.work_hub_activity (
  id bigint generated by default as identity primary key,
  item_id uuid not null references public.work_hub_items(id) on delete cascade,
  actor_id uuid,
  event_type text not null,
  from_status text,
  to_status text,
  message text not null default '',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.work_hub_comments add column if not exists comment_type text not null default 'comment';
alter table public.work_hub_comments add column if not exists attachments jsonb not null default '[]'::jsonb;
alter table public.work_hub_notifications add column if not exists user_id uuid;
alter table public.work_hub_notifications add column if not exists item_id uuid references public.work_hub_items(id) on delete cascade;
alter table public.work_hub_notifications add column if not exists notification_type text not null default 'work_item';
alter table public.work_hub_notifications add column if not exists title text not null default 'Work update';
alter table public.work_hub_notifications add column if not exists body text not null default '';
alter table public.work_hub_notifications add column if not exists read_at timestamptz;
alter table public.work_hub_notifications add column if not exists created_at timestamptz not null default now();

-- Permit a dedicated submission comment while preserving any previous compatible schema.
do $do$
declare c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid='public.work_hub_comments'::regclass
      and contype='c'
      and pg_get_constraintdef(oid) ilike '%comment_type%'
  loop
    execute format('alter table public.work_hub_comments drop constraint if exists %I',c.conname);
  end loop;
end $do$;
alter table public.work_hub_comments
  add constraint work_hub_comments_type_v1133
  check(comment_type in ('comment','review','system','submission'));

create index if not exists work_hub_items_assignees_v1133 on public.work_hub_items using gin(assignee_ids);
create index if not exists work_hub_comments_item_v1133 on public.work_hub_comments(item_id,created_at);
create index if not exists work_hub_notifications_user_v1133 on public.work_hub_notifications(user_id,read_at,created_at desc);

create or replace function public.bes_v1133_can_view_work_item(target_item public.work_hub_items,target_user uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public,auth,pg_temp as $$
  select target_user is not null and (
    public.bes_v1133_is_leader(target_user)
    or target_item.created_by=target_user
    or target_item.owner_id=target_user
    or target_user=any(coalesce(target_item.assignee_ids,'{}'::uuid[]))
    or target_user=any(coalesce(target_item.watcher_ids,'{}'::uuid[]))
    or target_item.visibility='department'
  );
$$;
grant execute on function public.bes_v1133_can_view_work_item(public.work_hub_items,uuid) to authenticated;

create or replace function public.bes_v1133_guard_work_item_update()
returns trigger language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare uid uuid:=auth.uid(); old_core jsonb; new_core jsonb;
begin
  if uid is null then raise exception 'Authentication required'; end if;
  new.updated_at:=now();
  if public.bes_v1133_is_leader(uid) or old.created_by=uid or old.owner_id=uid then return new; end if;
  if uid=any(coalesce(old.assignee_ids,'{}'::uuid[])) then
    old_core:=to_jsonb(old)-array['status','submitted_at','completed_at','updated_at'];
    new_core:=to_jsonb(new)-array['status','submitted_at','completed_at','updated_at'];
    if old_core<>new_core then raise exception 'Assignees can only update workflow status'; end if;
    if new.status=old.status then return new; end if;
    if not(
      (old.status='assigned' and new.status in ('accepted','in_progress','submitted'))
      or (old.status='accepted' and new.status in ('in_progress','submitted'))
      or (old.status='in_progress' and new.status='submitted')
      or (old.status='changes_requested' and new.status in ('in_progress','submitted'))
    ) then raise exception 'Invalid assignee workflow transition: % -> %',old.status,new.status; end if;
    if new.status='submitted' then new.submitted_at:=coalesce(new.submitted_at,now()); end if;
    return new;
  end if;
  raise exception 'You cannot update this work item';
end $$;

drop trigger if exists bes_v1133_work_item_guard on public.work_hub_items;
create trigger bes_v1133_work_item_guard before update on public.work_hub_items
for each row execute function public.bes_v1133_guard_work_item_update();

create or replace function public.bes_v1133_notify_work_users(
  target_item uuid,target_users uuid[],target_type text,target_title text,target_body text,actor uuid default auth.uid()
) returns void language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare recipient uuid;
begin
  foreach recipient in array coalesce(target_users,'{}'::uuid[]) loop
    if recipient is not null and recipient is distinct from actor then
      insert into public.work_hub_notifications(user_id,item_id,notification_type,title,body)
      values(recipient,target_item,target_type,left(target_title,240),left(coalesce(target_body,''),1000));
    end if;
  end loop;
end $$;

create or replace function public.bes_v1133_after_work_item_insert()
returns trigger language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare recipients uuid[];
begin
  insert into public.work_hub_activity(item_id,actor_id,event_type,to_status,message,payload)
  values(new.id,new.created_by,'created',new.status,'Đã tạo và giao công việc',jsonb_build_object('title',new.title));
  select array_agg(distinct u) into recipients
  from unnest(coalesce(new.assignee_ids,'{}'::uuid[])||coalesce(new.watcher_ids,'{}'::uuid[])) u
  where u is not null;
  perform public.bes_v1133_notify_work_users(
    new.id,recipients,'work_item_assigned','Công việc mới: '||new.title,
    case when new.due_at is null then 'Admin/TTCM vừa giao một công việc mới.'
         else 'Hạn hoàn thành: '||to_char(new.due_at at time zone 'Asia/Ho_Chi_Minh','DD/MM/YYYY HH24:MI') end,
    new.created_by
  );
  return new;
end $$;

create or replace function public.bes_v1133_after_work_item_update()
returns trigger language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare actor uuid:=auth.uid(); recipients uuid[]; notice_type text; notice_title text; notice_body text;
begin
  if new.status is distinct from old.status then
    insert into public.work_hub_activity(item_id,actor_id,event_type,from_status,to_status,message,payload)
    values(new.id,actor,'status_changed',old.status,new.status,'Đã cập nhật trạng thái công việc',jsonb_build_object('title',new.title));
    select array_agg(distinct u) into recipients
    from unnest(
      coalesce(new.assignee_ids,'{}'::uuid[])
      ||coalesce(new.watcher_ids,'{}'::uuid[])
      ||array[new.owner_id,new.created_by]
    ) u where u is not null;
    if new.status='submitted' then
      notice_type:='work_item_submission';
      notice_title:='Đã nộp công việc: '||new.title;
      notice_body:='Giáo viên đã gửi phản hồi hoặc tệp đính kèm. Mở Trung tâm công việc để xem.';
    else
      notice_type:='work_item_status';
      notice_title:='Cập nhật công việc: '||new.title;
      notice_body:='Trạng thái mới: '||new.status;
    end if;
    perform public.bes_v1133_notify_work_users(new.id,recipients,notice_type,notice_title,notice_body,actor);
  end if;
  return new;
end $$;

create or replace function public.bes_v1133_after_work_comment_insert()
returns trigger language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare item public.work_hub_items%rowtype; recipients uuid[];
begin
  insert into public.work_hub_activity(item_id,actor_id,event_type,message,payload)
  values(new.item_id,new.author_id,case when new.comment_type='submission' then 'response_submitted' else 'comment_added' end,
    case when new.comment_type='submission' then 'Giáo viên đã nộp phản hồi' else 'Đã thêm phản hồi' end,
    jsonb_build_object('comment_id',new.id,'comment_type',new.comment_type));
  if new.comment_type='submission' then return new; end if;
  select * into item from public.work_hub_items where id=new.item_id;
  select array_agg(distinct u) into recipients
  from unnest(
    coalesce(item.assignee_ids,'{}'::uuid[])
    ||coalesce(item.watcher_ids,'{}'::uuid[])
    ||array[item.owner_id,item.created_by]
  ) u where u is not null;
  perform public.bes_v1133_notify_work_users(item.id,recipients,'work_item_comment','Phản hồi mới: '||item.title,left(new.body,300),new.author_id);
  return new;
end $$;

-- Replace earlier Work Hub notification triggers to avoid duplicate notifications.
drop trigger if exists work_hub_item_insert_activity on public.work_hub_items;
drop trigger if exists work_hub_item_update_activity on public.work_hub_items;
drop trigger if exists work_hub_comment_insert_activity on public.work_hub_comments;
drop trigger if exists bes_v1133_work_item_insert on public.work_hub_items;
drop trigger if exists bes_v1133_work_item_update on public.work_hub_items;
drop trigger if exists bes_v1133_work_comment_insert on public.work_hub_comments;
create trigger bes_v1133_work_item_insert after insert on public.work_hub_items
for each row execute function public.bes_v1133_after_work_item_insert();
create trigger bes_v1133_work_item_update after update on public.work_hub_items
for each row execute function public.bes_v1133_after_work_item_update();
create trigger bes_v1133_work_comment_insert after insert on public.work_hub_comments
for each row execute function public.bes_v1133_after_work_comment_insert();

-- Atomic teacher response: comment + attachments + submitted status in one transaction.
create or replace function public.bes_v1133_submit_work_response(
  target_item uuid,
  response_body text,
  response_attachments jsonb default '[]'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path=public,auth,pg_temp
as $$
declare uid uuid:=auth.uid(); item public.work_hub_items%rowtype; response public.work_hub_comments%rowtype;
begin
  if uid is null then raise exception 'Authentication required'; end if;
  select * into item from public.work_hub_items where id=target_item for update;
  if not found then raise exception 'Work item not found'; end if;
  if not(uid=any(coalesce(item.assignee_ids,'{}'::uuid[])) or public.bes_v1133_is_leader(uid)) then
    raise exception 'You are not allowed to submit this work item';
  end if;
  if jsonb_typeof(coalesce(response_attachments,'[]'::jsonb))<>'array' then
    raise exception 'Attachments must be a JSON array';
  end if;
  insert into public.work_hub_comments(item_id,author_id,body,comment_type,attachments)
  values(target_item,uid,coalesce(nullif(btrim(response_body),''),'Đã nộp phản hồi công việc.'),'submission',coalesce(response_attachments,'[]'::jsonb))
  returning * into response;
  update public.work_hub_items
  set status='submitted',submitted_at=now(),updated_at=now()
  where id=target_item returning * into item;
  return jsonb_build_object('comment',to_jsonb(response),'item',to_jsonb(item));
end $$;
grant execute on function public.bes_v1133_submit_work_response(uuid,text,jsonb) to authenticated;

alter table public.work_hub_items enable row level security;
alter table public.work_hub_comments enable row level security;
alter table public.work_hub_notifications enable row level security;
alter table public.work_hub_activity enable row level security;

do $do$ declare p record; begin
  for p in
    select tablename,policyname from pg_policies
    where schemaname='public'
      and tablename in ('work_hub_items','work_hub_comments','work_hub_notifications','work_hub_activity')
      and policyname like '%v1133%'
  loop
    execute format('drop policy if exists %I on public.%I',p.policyname,p.tablename);
  end loop;
end $do$;

create policy work_hub_items_select_v1133 on public.work_hub_items
for select to authenticated using(public.bes_v1133_can_view_work_item(work_hub_items,auth.uid()));
create policy work_hub_items_insert_v1133 on public.work_hub_items
for insert to authenticated with check(
  created_by=auth.uid() and owner_id=auth.uid()
  and (public.bes_v1133_is_leader(auth.uid()) or assignee_ids<@array[auth.uid()]::uuid[])
);
create policy work_hub_items_update_v1133 on public.work_hub_items
for update to authenticated using(public.bes_v1133_can_view_work_item(work_hub_items,auth.uid()))
with check(public.bes_v1133_can_view_work_item(work_hub_items,auth.uid()));
create policy work_hub_comments_select_v1133 on public.work_hub_comments
for select to authenticated using(exists(select 1 from public.work_hub_items i where i.id=item_id and public.bes_v1133_can_view_work_item(i,auth.uid())));
create policy work_hub_comments_insert_v1133 on public.work_hub_comments
for insert to authenticated with check(author_id=auth.uid() and exists(select 1 from public.work_hub_items i where i.id=item_id and public.bes_v1133_can_view_work_item(i,auth.uid())));
create policy work_hub_activity_select_v1133 on public.work_hub_activity
for select to authenticated using(exists(select 1 from public.work_hub_items i where i.id=item_id and public.bes_v1133_can_view_work_item(i,auth.uid())));
create policy work_hub_notifications_select_v1133 on public.work_hub_notifications
for select to authenticated using(user_id=auth.uid());
create policy work_hub_notifications_update_v1133 on public.work_hub_notifications
for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy work_hub_notifications_delete_v1133 on public.work_hub_notifications
for delete to authenticated using(user_id=auth.uid());

grant select,insert,update on public.work_hub_items to authenticated;
grant select,insert,update on public.work_hub_comments to authenticated;
grant select on public.work_hub_activity to authenticated;
grant select,update,delete on public.work_hub_notifications to authenticated;
do $do$ begin
  if to_regclass('public.work_hub_notifications_id_seq') is not null then
    grant usage,select on sequence public.work_hub_notifications_id_seq to authenticated;
  end if;
end $do$;

-- Private storage bucket for teacher responses.
insert into storage.buckets(id,name,public,file_size_limit)
values('work-hub-submissions','work-hub-submissions',false,26214400)
on conflict(id) do update set public=false,file_size_limit=26214400;

do $do$ declare p record; begin
  for p in select policyname from pg_policies where schemaname='storage' and tablename='objects' and policyname like 'work_hub_files_%_v1133'
  loop execute format('drop policy if exists %I on storage.objects',p.policyname); end loop;
end $do$;

create policy work_hub_files_select_v1133 on storage.objects
for select to authenticated using(
  bucket_id='work-hub-submissions'
  and exists(
    select 1 from public.work_hub_items i
    where i.id::text=(storage.foldername(name))[1]
      and public.bes_v1133_can_view_work_item(i,auth.uid())
  )
);
create policy work_hub_files_insert_v1133 on storage.objects
for insert to authenticated with check(
  bucket_id='work-hub-submissions'
  and (storage.foldername(name))[2]=auth.uid()::text
  and exists(
    select 1 from public.work_hub_items i
    where i.id::text=(storage.foldername(name))[1]
      and public.bes_v1133_can_view_work_item(i,auth.uid())
  )
);
create policy work_hub_files_delete_v1133 on storage.objects
for delete to authenticated using(
  bucket_id='work-hub-submissions'
  and (
    (storage.foldername(name))[2]=auth.uid()::text
    or public.bes_v1133_is_leader(auth.uid())
  )
);

-- Realtime delivery for open teacher/admin sessions.
do $do$
begin
  if exists(select 1 from pg_publication where pubname='supabase_realtime') then
    begin alter publication supabase_realtime add table public.work_hub_items; exception when duplicate_object then null; end;
    begin alter publication supabase_realtime add table public.work_hub_comments; exception when duplicate_object then null; end;
    begin alter publication supabase_realtime add table public.work_hub_notifications; exception when duplicate_object then null; end;
  end if;
end $do$;

insert into public.bes_schema_registry(component,version,installed_at,metadata) values
('application','11.3.3',now(),jsonb_build_object('release','Work Assignment Delivery')),
('runtime_core','2.3.3',now(),jsonb_build_object('work_notifications',true,'file_responses',true)),
('work_assignment_delivery','11.3.3',now(),jsonb_build_object('notification_table','work_hub_notifications','storage_bucket','work-hub-submissions','max_file_mb',25))
on conflict(component) do update set version=excluded.version,installed_at=excluded.installed_at,metadata=excluded.metadata;

commit;
