import fs from 'node:fs';
let passed=0,failed=0;
const read=(file)=>fs.readFileSync(file,'utf8');
const exists=(file)=>fs.existsSync(file);
const pass=(name,condition)=>{if(condition){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const versionJson=JSON.parse(read('public/version.json'));
const releaseJson=JSON.parse(read('public/release-manifest.json'));
const versionSource=read('src/config/version.js');
const grammar=read('src/pages/GrammarBuilder.jsx');
const css=read('src/pages/GrammarBuilder.css');
const apiEntries=fs.readdirSync('api').filter((name)=>!name.startsWith('_')&&/\.(?:js|mjs|ts|py|go)$/i.test(name));
pass('package version 11.5.1',pkg.version==='11.5.1');
pass('version registry 11.5.1',versionSource.includes("APP_VERSION = '11.5.1'")&&versionJson.version==='11.5.1'&&releaseJson.version==='11.5.1');
pass('runtime core 2.5.1',versionJson.runtimeCore==='2.5.1'&&releaseJson.runtime==='2.5.1');
pass('Grammar Builder V2.4 label',grammar.includes('V2.4'));
pass('Modern SaaS design attribute',grammar.includes('data-design="modern-saas"'));
pass('compact product header',grammar.includes('gb-brand-lockup')&&grammar.includes('gb-brand-mark'));
pass('project context strip',grammar.includes('gb-context-strip')&&grammar.includes('ContextMetric'));
pass('five project context metrics',(grammar.match(/<ContextMetric/g)||[]).length===5);
pass('segmented seven-step workflow',grammar.includes('WORKFLOW_STEPS')&&css.includes('Modern progress navigator'));
pass('two-card setup layout',css.includes('.gb-page[data-design="modern-saas"] .gb-setup-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))'));
pass('approved modern workbench marker',css.includes('V11.5.1 — Modern SaaS Workspace'));
pass('modern Blueprint illustration',grammar.includes('gb-blueprint-visual')&&css.includes('.gb-blueprint-visual span'));
pass('modern AI robot illustration',grammar.includes('gb-ai-robot')&&css.includes('.gb-ai-robot::before'));
pass('AI task colour system',css.includes('.gb-ai-task-grid button:nth-child(2)')&&css.includes('--task:#df4f93'));
pass('clear AI selected state',css.includes('.gb-ai-task-grid button.active::after')&&css.includes('content:"✓"'));
pass('clear build-mode selected state',css.includes('.gb-mode-grid button.active::after')&&css.includes('content:"✓"'));
pass('modern context summary cards',css.includes('.gb-context-metric>i')&&css.includes('.gb-context-metric strong'));
pass('responsive workbench',css.includes('@media(max-width:1000px)')&&css.includes('@media(max-width:720px)'));
pass('domain-only focus retained',grammar.includes('GRAMMAR_DOMAIN_GROUPS')&&grammar.includes('Yêu cầu cụ thể khác'));
pass('real Brian AI gateway retained',grammar.includes('callAI({')&&grammar.includes('getActiveAiConfig'));
pass('Teacher Vault retained',grammar.includes('TEACHER VAULT'));
pass('Item Bank retained',grammar.includes('addQuestionsFromTextToBank'));
pass('Connected Workflow retained',grammar.includes('const DESTINATIONS')&&grammar.includes('createTransfer'));
pass('Vercel functions <=12',apiEntries.length<=12);
pass('no obsolete lesson AI function',!exists('api/lesson-ai.mjs'));
pass('public npm registry only',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.5.1 Grammar Builder Modern SaaS Check: ${passed}/${passed+failed} passed`);
console.log(`Deployable API entries: ${apiEntries.length}`);
if(failed)process.exit(1);
