
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, Camera, Check, ChevronRight, ClipboardCheck, Database, Download, FileCheck2, FileText, History, IdCard, MonitorUp, RefreshCw, Search, ShieldCheck, Upload, UserRound, Users, X } from 'lucide-react';
import { recognizeStudentRecordImage, STUDENT_RECORD_FIELD_LABELS } from '../../utils/studentRecordScanner.js';
import { deleteStudentRecordMedia, getStudentRecordMedia, saveStudentRecordMedia } from '../../utils/studentRecordMediaStore.js';
import './StudentRecordsTab.css';

const EMPTY_SOURCE = Object.freeze({ fields: {}, captures: [], updatedAt: '' });
const PAPER_DOCS = Object.freeze([
  { key: 'completionCertificate', label: 'Bằng / GCN hoàn thành', helper: 'THCS đối với THPT; Tiểu học đối với THCS' },
  { key: 'birthCertificate', label: 'Giấy khai sinh', helper: 'Bản sao, có dấu đỏ và chữ ký sống' },
  { key: 'grade10Admission', label: 'Giấy trúng tuyển lớp 10', helper: 'Áp dụng với khối 11, 12' },
  { key: 'transcript', label: 'Học bạ', helper: 'Kiểm tra chữ ký, ảnh giáp lai và dấu trường' },
]);
const REQUIRED_COMPARE_FIELDS = Object.freeze(['fullName','gender','birthDate','birthPlace','hometown','birthRegistrationPlace','currentAddress','permanentAddress','citizenId','phone','fatherName','fatherPhone','motherName','motherPhone']);

function nowIso(){return new Date().toISOString();}
function uid(prefix='scan'){if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID();return prefix+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,9);}
function text(value){return String(value??'').trim();}
function normalized(value){return text(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/\s+/g,' ');}
function displayDate(value){if(!value)return '—';if(/^\d{2}\/\d{2}\/\d{4}$/.test(value))return value;const date=new Date(value);return Number.isFinite(date.getTime())?new Intl.DateTimeFormat('vi-VN').format(date):value;}
function sourceLabel(source){if(source==='vnedu')return 'vnEdu';if(source==='moet')return 'MOET';return 'Hồ sơ giấy';}
function documentLabel(type){const map={birth_certificate:'Giấy khai sinh',transcript:'Học bạ',grade10_admission:'Giấy trúng tuyển lớp 10',completion_certificate:'Bằng / GCN hoàn thành'};return map[type]||'Hồ sơ giấy khác';}
function studentCanonical(student={}){return{fullName:text(student.fullName),gender:text(student.gender),birthDate:text(student.birthDate)?displayDate(student.birthDate):'',currentAddress:text(student.address),phone:text(student.phone),fatherName:text(student.parentName),fatherPhone:text(student.parentPhone)};}
function makeRecord(student){return{canonical:studentCanonical(student),sources:{paper:{...EMPTY_SOURCE,fields:{},captures:[]},vnedu:{...EMPTY_SOURCE,fields:{},captures:[]},moet:{...EMPTY_SOURCE,fields:{},captures:[]}},checklist:Object.fromEntries(PAPER_DOCS.map((item)=>[item.key,'missing'])),notes:'',verifiedAt:'',audit:[]};}
function ensureRecord(raw,student){const base=makeRecord(student);return{...base,...(raw||{}),canonical:{...base.canonical,...((raw||{}).canonical||{})},sources:{paper:{...base.sources.paper,...((raw||{}).sources?.paper||{}),fields:{...((raw||{}).sources?.paper?.fields||{})},captures:[...((raw||{}).sources?.paper?.captures||[])]},vnedu:{...base.sources.vnedu,...((raw||{}).sources?.vnedu||{}),fields:{...((raw||{}).sources?.vnedu?.fields||{})},captures:[...((raw||{}).sources?.vnedu?.captures||[])]},moet:{...base.sources.moet,...((raw||{}).sources?.moet||{}),fields:{...((raw||{}).sources?.moet?.fields||{})},captures:[...((raw||{}).sources?.moet?.captures||[])]}},checklist:{...base.checklist,...((raw||{}).checklist||{})},audit:Array.isArray(raw?.audit)?raw.audit:[]};}
function recordProgress(record,grade){const docs=PAPER_DOCS.filter((doc)=>doc.key!=='grade10Admission'||['11','12'].includes(String(grade)));const paperDone=docs.filter((doc)=>record.checklist?.[doc.key]==='complete').length;const sourceFields=['vnedu','moet'].reduce((sum,key)=>sum+Object.keys(record.sources?.[key]?.fields||{}).length,0);const compareKnown=REQUIRED_COMPARE_FIELDS.filter((key)=>(record.canonical?.[key]||record.sources?.vnedu?.fields?.[key]||record.sources?.moet?.fields?.[key])).length;const paperScore=docs.length?paperDone/docs.length:0;const digitalScore=Math.min(1,sourceFields/18);const compareScore=Math.min(1,compareKnown/10);return Math.round((paperScore*.45+digitalScore*.35+compareScore*.20)*100);}
function issueList(record){const issues=[];REQUIRED_COMPARE_FIELDS.forEach((key)=>{const label=STUDENT_RECORD_FIELD_LABELS[key]||key;const values=[['Hồ sơ gốc',record.canonical?.[key]],['vnEdu',record.sources?.vnedu?.fields?.[key]],['MOET',record.sources?.moet?.fields?.[key]]].filter(([,value])=>text(value));if(key==='citizenId'&&!text(record.sources?.moet?.fields?.[key]))issues.push({key:'moet-missing-'+key,tone:'danger',label:'MOET thiếu '+label,detail:'Chưa nhận diện được thông tin bắt buộc này trên ảnh MOET.'});if(values.length>=2){const first=normalized(values[0][1]);const mismatch=values.find(([,value])=>normalized(value)!==first);if(mismatch)issues.push({key:'mismatch-'+key,tone:'danger',label:'Sai lệch '+label,detail:values.map(([source,value])=>source+': '+value).join(' · ')});}});return issues;}
function csvEscape(value){const v=String(value??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;}
function downloadCsv(name,rows){const content='\ufeff'+rows.map((row)=>row.map(csvEscape).join(',')).join('\r\n');const blob=new Blob([content],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function StudentRecordsTab({workspace,onCommit,currentUser}){
  const activeStudents=useMemo(()=>(workspace.students||[]).filter((student)=>student.active!==false),[workspace.students]);
  const records=workspace.studentRecords&&typeof workspace.studentRecords==='object'?workspace.studentRecords:{};
  const [selectedId,setSelectedId]=useState(()=>activeStudents[0]?.id||'');
  const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [section,setSection]=useState('paper');
  const [scanOpen,setScanOpen]=useState(false);const [scanTarget,setScanTarget]=useState('auto');const [scanFile,setScanFile]=useState(null);const [scanResult,setScanResult]=useState(null);const [scanFields,setScanFields]=useState({});const [scanBusy,setScanBusy]=useState(false);const [scanProgress,setScanProgress]=useState(0);const [scanMessage,setScanMessage]=useState('');const [preview,setPreview]=useState(null);const fileRef=useRef(null);
  useEffect(()=>{if(!activeStudents.some((student)=>String(student.id)===String(selectedId)))setSelectedId(activeStudents[0]?.id||'');},[activeStudents,selectedId]);
  const selectedStudent=activeStudents.find((student)=>String(student.id)===String(selectedId))||null;
  const selectedRecord=selectedStudent?ensureRecord(records[selectedStudent.id],selectedStudent):null;
  const selectedIssues=selectedRecord?issueList(selectedRecord):[];
  const grade=String(workspace.classProfile?.grade||'').trim();
  const summaries=useMemo(()=>{let complete=0,needs=0,mismatches=0;activeStudents.forEach((student)=>{const record=ensureRecord(records[student.id],student);const progress=recordProgress(record,grade);const issues=issueList(record);if(progress>=95&&!issues.length)complete+=1;else needs+=1;if(issues.length)mismatches+=1;});return{total:activeStudents.length,complete,needs,mismatches};},[activeStudents,grade,records]);
  const visibleStudents=useMemo(()=>activeStudents.filter((student)=>{const record=ensureRecord(records[student.id],student);const progress=recordProgress(record,grade);const issues=issueList(record);if(filter==='complete'&&!(progress>=95&&!issues.length))return false;if(filter==='missing'&&progress>=95)return false;if(filter==='issues'&&!issues.length)return false;const needle=normalized(query);return!needle||normalized([student.fullName,student.code,student.parentName,student.parentPhone].join(' ')).includes(needle);}),[activeStudents,filter,grade,query,records]);
  const commitRecord=async(studentId,nextRecord,message)=>onCommit({...workspace,studentRecords:{...records,[studentId]:nextRecord}},message);
  const patchRecord=async(patch,message='Đã cập nhật hồ sơ học sinh.')=>{if(!selectedStudent||!selectedRecord)return;const next={...selectedRecord,...patch,audit:[...(selectedRecord.audit||[]),{id:uid('audit'),at:nowIso(),by:currentUser?.name||currentUser?.email||'GVCN',action:message}].slice(-80)};await commitRecord(selectedStudent.id,next,message);};
  const setDocStatus=async(key,status)=>patchRecord({checklist:{...selectedRecord.checklist,[key]:status}},'Đã cập nhật checklist hồ sơ.');
  const openScanner=(target='auto')=>{if(!selectedStudent)return;setScanTarget(target);setScanFile(null);setScanResult(null);setScanFields({});setScanProgress(0);setScanMessage('');setScanOpen(true);};
  const recognize=async(file)=>{if(!file)return;setScanFile(file);setScanBusy(true);setScanProgress(0);setScanMessage('Đang chuẩn bị OCR…');try{const result=await recognizeStudentRecordImage(file,{onProgress:({status,progress})=>{setScanProgress(Math.max(0,Math.min(1,Number(progress||0))));setScanMessage(status==='recognizing text'?'Đang đọc nội dung…':status==='loading tesseract core'?'Đang tải bộ OCR…':'Đang nhận diện…');}});setScanResult(result);setScanFields(result.fields||{});setScanMessage(Object.keys(result.fields||{}).length?'Đã nhận diện '+Object.keys(result.fields).length+' trường dữ liệu.':'OCR đã đọc ảnh nhưng chưa tách được trường dữ liệu. Có thể sửa thủ công bên dưới.');}catch(error){setScanMessage(error?.message||'Không thể nhận diện ảnh.');}finally{setScanBusy(false);}};
  const resolvedTarget=()=>scanTarget!=='auto'?scanTarget:scanResult?.sourceType==='vnedu'?'vnedu':scanResult?.sourceType==='moet'?'moet':'paper';
  const saveScan=async()=>{if(!selectedStudent||!selectedRecord||!scanFile)return;const target=resolvedTarget();const captureId=uid('capture');const mediaKey=await saveStudentRecordMedia({workspaceId:workspace.id,studentId:selectedStudent.id,captureId,file:scanFile});const capture={id:captureId,mediaKey,name:scanFile.name||'Ảnh hồ sơ',type:scanFile.type,size:scanFile.size,sourceType:scanResult?.sourceType||'unknown',engine:scanResult?.engine||'',confidence:scanResult?.confidence||0,rawText:scanResult?.rawText||scanResult?.text||'',createdAt:nowIso()};const nextSources={...selectedRecord.sources,[target]:{...selectedRecord.sources[target],fields:{...selectedRecord.sources[target].fields,...scanFields},captures:[...selectedRecord.sources[target].captures,capture],updatedAt:nowIso()}};let checklist={...selectedRecord.checklist};if(target==='paper'){const map={birth_certificate:'birthCertificate',transcript:'transcript',grade10_admission:'grade10Admission',completion_certificate:'completionCertificate'};const docKey=map[scanResult?.sourceType];if(docKey)checklist[docKey]='review';}await patchRecord({sources:nextSources,checklist},'Đã quét và lưu ảnh hồ sơ.');setScanOpen(false);setSection(target==='paper'?'paper':target);};
  const removeCapture=async(sourceKey,capture)=>{if(!window.confirm('Xóa ảnh hồ sơ này khỏi thiết bị?'))return;await deleteStudentRecordMedia(capture.mediaKey).catch(()=>{});const source=selectedRecord.sources[sourceKey];await patchRecord({sources:{...selectedRecord.sources,[sourceKey]:{...source,captures:source.captures.filter((item)=>item.id!==capture.id)}}},'Đã xóa ảnh hồ sơ.');if(preview?.capture?.id===capture.id)setPreview(null);};
  const openCapture=async(sourceKey,capture)=>{const stored=await getStudentRecordMedia(capture.mediaKey);if(!stored?.blob){alert('Ảnh không còn trên thiết bị này.');return;}const url=URL.createObjectURL(stored.blob);setPreview({sourceKey,capture,url});};
  const closePreview=()=>{if(preview?.url)URL.revokeObjectURL(preview.url);setPreview(null);};
  const updateCanonical=async(key,value)=>patchRecord({canonical:{...selectedRecord.canonical,[key]:value}},'Đã xác nhận dữ liệu gốc.');
  const verifyComplete=async()=>patchRecord({verifiedAt:nowIso()},'Đã xác nhận hoàn tất kiểm tra hồ sơ.');
  const exportReport=()=>{const categories=[['1','Bằng tốt nghiệp THCS / GCN hoàn thành chương trình','completionCertificate'],['2','Giấy khai sinh bản sao','birthCertificate'],['3','Giấy chứng nhận trúng tuyển vào lớp 10','grade10Admission'],['4','Học bạ học sinh','transcript'],['5','Thông tin học sinh trên CSDL (MOET)','moet'],['6','Thông tin trên vnEdu','vnedu'],['7','Nội dung khác','other']];const rows=[['TT','Nội dung kiểm tra','Tên học sinh sai sót/thiếu','Yêu cầu bổ sung/điều chỉnh']];categories.forEach(([index,label,key])=>{const names=[],actions=[];activeStudents.forEach((student)=>{const record=ensureRecord(records[student.id],student);if(key==='moet'||key==='vnedu'){const fields=record.sources[key]?.fields||{};const issues=issueList(record).filter((issue)=>issue.label.includes(key==='moet'?'MOET':'vnEdu')||issue.key.startsWith('mismatch-'));if(!Object.keys(fields).length||issues.length){names.push(student.fullName);actions.push(student.fullName+': '+(!Object.keys(fields).length?'Chưa kiểm tra/nhận diện dữ liệu '+(key==='moet'?'MOET':'vnEdu'):issues.map((i)=>i.label).join('; ')));}}else if(key!=='other'&&record.checklist?.[key]!=='complete'){names.push(student.fullName);actions.push(student.fullName+': '+(record.checklist?.[key]==='review'?'Cần GVCN xác nhận hồ sơ':'Cần bổ sung hồ sơ'));}});rows.push([index,label,names.join('; '),actions.join(' | ')]);});downloadCsv('bien-ban-kiem-tra-ho-so-'+(workspace.classProfile?.className||'lop')+'.csv',rows);};

  if(!activeStudents.length)return <div className="sr-empty"><Users size={32}/><h3>Chưa có danh sách học sinh</h3><p>Thêm học sinh vào lớp chủ nhiệm trước khi tạo hồ sơ số.</p></div>;
  return <div className="sr-app">
    <header className="sr-app-head"><div className="sr-title"><span><IdCard size={22}/></span><div><h2>Hồ sơ học sinh</h2><p>{workspace.classProfile?.className||'Lớp chủ nhiệm'} · Năm học {workspace.classProfile?.schoolYear||'—'} · GVCN: {workspace.classProfile?.adviserName||currentUser?.name||currentUser?.email||'—'}</p></div></div><div className="sr-head-actions"><button type="button" className="sr-outline" onClick={()=>openScanner('paper')}><Camera size={17}/>Quét hồ sơ thông minh</button><button type="button" className="sr-outline" onClick={()=>openScanner('auto')}><MonitorUp size={17}/>Quét màn hình</button><button type="button" className="sr-outline" onClick={exportReport}><Download size={17}/>Xuất biên bản</button></div></header>
    <div className="sr-summary-grid"><article className="is-blue"><Users size={19}/><div><b>{summaries.total}</b><span>học sinh</span></div></article><article className="is-green"><Check size={19}/><div><b>{summaries.complete}</b><span>hoàn tất</span></div></article><article className="is-amber"><ClipboardCheck size={19}/><div><b>{summaries.needs}</b><span>cần bổ sung</span></div></article><article className="is-red"><AlertTriangle size={19}/><div><b>{summaries.mismatches}</b><span>có sai lệch</span></div></article></div>
    <div className="sr-layout">
      <aside className="sr-students"><div className="sr-search"><Search size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Tìm theo tên, mã học sinh…"/></div><div className="sr-filters">{[['all','Tất cả',summaries.total],['missing','Thiếu hồ sơ',summaries.needs],['issues','Sai thông tin',summaries.mismatches],['complete','Hoàn tất',summaries.complete]].map(([id,label,count])=><button key={id} type="button" className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}<b>{count}</b></button>)}</div><div className="sr-student-list">{visibleStudents.map((student)=>{const record=ensureRecord(records[student.id],student);const progress=recordProgress(record,grade);const issues=issueList(record);return <button type="button" key={student.id} className={String(student.id)===String(selectedId)?'selected':''} onClick={()=>setSelectedId(student.id)}><span className="sr-avatar">{text(student.fullName).split(/\s+/).slice(-2).map((part)=>part[0]||'').join('').toUpperCase()}</span><div><strong>{student.fullName}</strong><small>{workspace.classProfile?.className||''} · {student.code||'Chưa có mã HS'}</small><div className="sr-progress"><i style={{width:progress+'%'}}/></div></div><span className="sr-student-status"><b>{progress}%</b>{issues.length?<em>{issues.length} lỗi</em>:<em className="ok">Ổn</em>}</span><ChevronRight size={16}/></button>;})}</div></aside>
      <main className="sr-detail">{selectedStudent&&selectedRecord?<><section className="sr-student-hero"><span className="sr-hero-avatar"><UserRound size={30}/></span><div className="sr-hero-copy"><h2>{selectedStudent.fullName}</h2><p>{workspace.classProfile?.className||''} · Mã HS {selectedStudent.code||'—'}</p><div><span>{displayDate(selectedStudent.birthDate)}</span><span>{selectedStudent.gender||'—'}</span><span>{selectedStudent.parentPhone||selectedStudent.phone||'—'}</span></div></div><div className="sr-ring" style={{'--sr-progress':recordProgress(selectedRecord,grade)+'%'}}><b>{recordProgress(selectedRecord,grade)}%</b><span>Hồ sơ số</span></div><div className={'sr-verify '+(selectedRecord.verifiedAt?'done':'')}><ShieldCheck size={18}/><div><b>{selectedRecord.verifiedAt?'Đã xác nhận':'Đang theo dõi'}</b><span>{selectedRecord.verifiedAt?displayDate(selectedRecord.verifiedAt):selectedIssues.length+' vấn đề cần xử lý'}</span></div></div></section>
      <nav className="sr-subtabs">{[['paper',<FileText size={16}/>,'Hồ sơ giấy'],['vnedu',<Database size={16}/>,'vnEdu'],['moet',<Database size={16}/>,'MOET'],['compare',<RefreshCw size={16}/>,'Đối chiếu'],['history',<History size={16}/>,'Lịch sử']].map(([id,icon,label])=><button key={id} type="button" className={section===id?'active':''} onClick={()=>setSection(id)}>{icon}{label}</button>)}</nav>
      {section==='paper'?<section className="sr-section"><div className="sr-section-head"><div><h3>Checklist hồ sơ</h3><p>Đúng theo nội dung BGH yêu cầu kiểm tra.</p></div><button type="button" onClick={()=>openScanner('paper')}><Camera size={16}/>Chụp hồ sơ</button></div><div className="sr-doc-grid">{PAPER_DOCS.filter((doc)=>doc.key!=='grade10Admission'||['11','12'].includes(grade)).map((doc)=>{const status=selectedRecord.checklist?.[doc.key]||'missing';return <article key={doc.key} className={'is-'+status}><span>{status==='complete'?<Check size={20}/>:status==='review'?<ClipboardCheck size={20}/>:<AlertTriangle size={20}/>}</span><div><b>{doc.label}</b><small>{doc.helper}</small></div><select value={status} onChange={(e)=>setDocStatus(doc.key,e.target.value)}><option value="missing">Thiếu</option><option value="review">Cần kiểm tra</option><option value="complete">Đã đủ</option></select></article>;})}</div><SourceCaptures sourceKey="paper" record={selectedRecord} openCapture={openCapture} removeCapture={removeCapture}/></section>:null}
      {section==='vnedu'||section==='moet'?<section className="sr-section"><div className="sr-section-head"><div><h3>{section==='vnedu'?'Thông tin trên vnEdu':'Thông tin trên CSDL (MOET)'}</h3><p>Chụp màn hình, OCR tự nhận diện rồi GVCN xác nhận.</p></div><button type="button" onClick={()=>openScanner(section)}><MonitorUp size={16}/>Quét màn hình</button></div><div className="sr-field-grid">{REQUIRED_COMPARE_FIELDS.map((key)=><label key={key}><span>{STUDENT_RECORD_FIELD_LABELS[key]}</span><input value={selectedRecord.sources[section].fields?.[key]||''} onChange={(e)=>{const source=selectedRecord.sources[section];patchRecord({sources:{...selectedRecord.sources,[section]:{...source,fields:{...source.fields,[key]:e.target.value},updatedAt:nowIso()}}},'Đã cập nhật dữ liệu '+sourceLabel(section)+'.');}} placeholder="Chưa có dữ liệu"/></label>)}</div><SourceCaptures sourceKey={section} record={selectedRecord} openCapture={openCapture} removeCapture={removeCapture}/></section>:null}
      {section==='compare'?<section className="sr-section"><div className="sr-section-head"><div><h3>Đối chiếu 3 nguồn</h3><p>Hồ sơ gốc ↔ vnEdu ↔ MOET.</p></div></div><div className="sr-compare-wrap"><table className="sr-compare"><thead><tr><th>Thông tin</th><th>Hồ sơ gốc</th><th>vnEdu</th><th>MOET</th></tr></thead><tbody>{REQUIRED_COMPARE_FIELDS.map((key)=>{const canonical=selectedRecord.canonical?.[key]||'';const vn=selectedRecord.sources.vnedu.fields?.[key]||'';const moet=selectedRecord.sources.moet.fields?.[key]||'';const values=[canonical,vn,moet].filter(text).map(normalized);const mismatch=values.length>=2&&new Set(values).size>1;return <tr key={key} className={mismatch?'mismatch':''}><th>{STUDENT_RECORD_FIELD_LABELS[key]}</th><td><input value={canonical} onChange={(e)=>updateCanonical(key,e.target.value)} placeholder="Chưa xác nhận"/></td><td>{vn||'—'}</td><td>{moet||'—'}</td></tr>;})}</tbody></table></div><div className="sr-issues"><h3>Cần xử lý ngay ({selectedIssues.length})</h3>{selectedIssues.length?selectedIssues.map((issue)=><article key={issue.key}><AlertTriangle size={17}/><div><b>{issue.label}</b><p>{issue.detail}</p></div><ChevronRight size={16}/></article>):<div className="sr-no-issues"><Check size={22}/><span>Chưa phát hiện sai lệch giữa các nguồn đã nhập.</span></div>}</div></section>:null}
      {section==='history'?<section className="sr-section"><div className="sr-section-head"><div><h3>Lịch sử hồ sơ</h3><p>Ghi nhận những lần quét, xác nhận và chỉnh sửa.</p></div></div><div className="sr-history">{[...(selectedRecord.audit||[])].reverse().map((entry)=><article key={entry.id}><span/><div><b>{entry.action}</b><p>{entry.by}</p></div><time>{displayDate(entry.at)}</time></article>)}{!selectedRecord.audit?.length?<p className="sr-muted">Chưa có lịch sử.</p>:null}</div></section>:null}
      <footer className="sr-detail-footer"><button type="button" className="sr-outline" onClick={()=>openScanner('auto')}><Upload size={16}/>Thêm ảnh minh chứng</button><button type="button" className="sr-primary" onClick={verifyComplete}><Check size={16}/>Xác nhận hoàn tất</button></footer></>:null}</main>
    </div>
    {scanOpen?<div className="sr-modal-layer" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget&&!scanBusy)setScanOpen(false);}}><section className="sr-scan-modal" role="dialog" aria-modal="true" aria-label="Quét hồ sơ thông minh"><header><div><span><Camera size={20}/></span><div><h3>Quét hồ sơ thông minh</h3><p>{selectedStudent?.fullName} · {workspace.classProfile?.className}</p></div></div><button type="button" disabled={scanBusy} onClick={()=>setScanOpen(false)}><X size={20}/></button></header><div className="sr-scan-body"><label className="sr-scan-target"><span>Nguồn ảnh</span><select value={scanTarget} onChange={(e)=>setScanTarget(e.target.value)}><option value="auto">Tự nhận diện</option><option value="paper">Hồ sơ giấy</option><option value="vnedu">vnEdu</option><option value="moet">MOET</option></select></label><button type="button" className="sr-dropzone" disabled={scanBusy} onClick={()=>fileRef.current?.click()}><Camera size={28}/><b>{scanFile?scanFile.name:'Chụp ảnh hoặc chọn ảnh'}</b><span>Ảnh được OCR trên trình duyệt; GVCN xác nhận trước khi lưu.</span></button><input ref={fileRef} hidden type="file" accept="image/*" capture="environment" onChange={(e)=>recognize(e.target.files?.[0])}/>{scanBusy||scanMessage?<div className="sr-scan-progress"><div><i style={{width:Math.round(scanProgress*100)+'%'}}/></div><span>{scanMessage||'Đang nhận diện…'} {scanBusy?Math.round(scanProgress*100)+'%':''}</span></div>:null}{scanResult?<div className="sr-scan-result"><div className="sr-scan-result-head"><div><b>{scanResult.sourceType==='vnedu'?'vnEdu':scanResult.sourceType==='moet'?'MOET':documentLabel(scanResult.sourceType)}</b><span>{scanResult.engine}{scanResult.confidence?' · '+Math.round(scanResult.confidence)+'%':''}</span></div><FileCheck2 size={22}/></div><div className="sr-scan-fields">{Object.keys(STUDENT_RECORD_FIELD_LABELS).map((key)=><label key={key}><span>{STUDENT_RECORD_FIELD_LABELS[key]}</span><input value={scanFields[key]||''} onChange={(e)=>setScanFields({...scanFields,[key]:e.target.value})} placeholder="Không nhận diện"/></label>)}</div></div>:null}</div><footer><button type="button" className="sr-outline" disabled={scanBusy} onClick={()=>setScanOpen(false)}>Hủy</button><button type="button" className="sr-primary" disabled={scanBusy||!scanFile} onClick={saveScan}><Check size={16}/>Xác nhận & lưu</button></footer></section></div>:null}
    {preview?<div className="sr-modal-layer" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)closePreview();}}><section className="sr-preview"><header><b>{preview.capture.name}</b><button type="button" onClick={closePreview}><X size={19}/></button></header><img src={preview.url} alt={preview.capture.name}/></section></div>:null}
  </div>;
}
function SourceCaptures({sourceKey,record,openCapture,removeCapture}){const captures=record.sources?.[sourceKey]?.captures||[];return <div className="sr-captures"><div className="sr-captures-head"><h4>Ảnh đã lưu</h4><span>{captures.length} ảnh · lưu riêng trên thiết bị này</span></div>{captures.length?<div className="sr-capture-grid">{captures.map((capture)=><article key={capture.id}><span><FileText size={19}/></span><div><b>{capture.name}</b><small>{capture.sourceType||'Ảnh hồ sơ'} · {capture.engine||'Không OCR'}</small></div><button type="button" onClick={()=>openCapture(sourceKey,capture)}>Xem</button><button type="button" className="danger" onClick={()=>removeCapture(sourceKey,capture)}>Xóa</button></article>)}</div>:<p className="sr-muted">Chưa có ảnh cho nguồn này.</p>}</div>;}
