import React, { useEffect, useMemo, useState } from 'react';
import './SettingsAppearanceEngine.css';

const STORAGE_KEY = 'bes-appearance-v2';
const DEFAULTS = { theme:'system',accent:'violet',accentCustom:'#7447E8',accentMode:'global',density:'comfortable',textScale:100,motion:'balanced',background:'mesh',adaptivePerformance:true,reduceMotion:false,highContrast:false,projector:false,batterySaver:false };
const PALETTES = { brian:{label:'Brian Blue',value:'#3478F6'},cyan:{label:'Ocean Cyan',value:'#10A7C8'},mint:{label:'Mint',value:'#18A889'},emerald:{label:'Emerald',value:'#20A55A'},amber:{label:'Amber',value:'#D88B00'},tangerine:{label:'Tangerine',value:'#F06E1A'},coral:{label:'Coral',value:'#EE5B56'},rose:{label:'Rose',value:'#E84B7A'},violet:{label:'Violet',value:'#7447E8'},indigo:{label:'Indigo',value:'#4D55D8'},graphite:{label:'Graphite',value:'#546171'} };

function stored(){try{return{...DEFAULTS,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return{...DEFAULTS}}}
function appTheme(value){if(['dark','oled'].includes(value))return'dark';if(['light','paper'].includes(value))return'light';if(value==='auto-time'){const h=new Date().getHours();return h>=18||h<6?'dark':'light'}return matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light'}
function appAccent(value){if(['violet','indigo','lavender','magenta'].includes(value))return'violet';if(['mint','emerald','lime','green'].includes(value))return'green';if(['amber','tangerine','orange'].includes(value))return'orange';if(['coral','rose'].includes(value))return'pink';if(value==='cyan')return'teal';return'blue'}
function appDensity(value){return value==='spacious'?'relaxed':(['compact','ultra'].includes(value)?'compact':'medium')}
function appMotion(value){return value==='off'?'off':(['lively','custom'].includes(value)?'full':'lite')}
function nearestScale(value){return[100,110,120,130].reduce((best,n)=>Math.abs(n-value)<Math.abs(best-value)?n:best,100)}
function Toggle({checked,onChange,label}){return <button type="button" className={`settings-engine-toggle ${checked?'is-on':''}`} aria-pressed={checked} aria-label={label} onClick={()=>onChange(!checked)}><span/></button>}

export default function SettingsAppearanceEngine({language='vi',setTheme,setAccent,setDensity,setMotionMode,setPerformanceMode,setFontScale}){
 const vi=language==='vi';
 const [state,setState]=useState(stored);
 const [ready,setReady]=useState(()=>Boolean(window.BESAppearance));
 const palettes=useMemo(()=>Object.entries(window.BESAppearance?.palettes||PALETTES).filter(([key])=>!['custom','monochrome'].includes(key)),[ready]);
 const syncApp=(next)=>{setTheme?.(appTheme(next.theme));setAccent?.(appAccent(next.accent));setDensity?.(appDensity(next.density));setMotionMode?.(appMotion(next.motion));setPerformanceMode?.(next.adaptivePerformance?'auto':(next.batterySaver?'low':'high'));setFontScale?.(nearestScale(Number(next.textScale||100)))};
 useEffect(()=>{const sync=(event)=>{const next={...DEFAULTS,...(event?.detail?.state||window.BESAppearance?.getState?.()||stored())};setReady(Boolean(window.BESAppearance));setState(next);syncApp(next)};sync();window.addEventListener('bes:appearance-ready',sync);window.addEventListener('bes:appearance-changed',sync);return()=>{window.removeEventListener('bes:appearance-ready',sync);window.removeEventListener('bes:appearance-changed',sync)}},[]);
 const update=(patch)=>{const next={...state,...patch,updatedAt:Date.now()};setState(next);syncApp(next);if(window.BESAppearance?.setState)window.BESAppearance.setState(patch);else{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next))}catch{}window.dispatchEvent(new CustomEvent('bes:appearance-changed',{detail:{state:next}}))}};
 const tier=window.BESAppearance?.getPerformanceTier?.()||document.documentElement.dataset.besPerformance||'adaptive';
 return <div className="settings-engine-integrated">
  <div className="settings-engine-banner"><div className="settings-engine-mark" aria-hidden="true"><i/><i/><i/><i/></div><div><strong>Appearance Engine V2</strong><small>{vi?'Màu sắc, chuyển động và Adaptive UI dùng chung một nguồn thiết lập.':'Color, motion and Adaptive UI share one source of truth.'}</small></div><span className={ready?'is-ready':''}><i/>{ready?(vi?'Đang hoạt động':'Active'):(vi?'Đang kết nối':'Connecting')}</span><button type="button" onClick={()=>window.BESAppearance?.open?.('theme')}>{vi?'Mở nâng cao':'Advanced'} ↗</button></div>
  <section><header><div><strong>{vi?'Chủ đề':'Theme'}</strong><small>{vi?'Áp dụng ngay trên toàn hệ thống.':'Applies immediately across the system.'}</small></div></header><div className="settings-engine-choices">{[['light',vi?'Sáng':'Light','☀'],['dark',vi?'Tối':'Dark','◐'],['system',vi?'Hệ thống':'System','◒'],['auto-time',vi?'Theo giờ':'By time','◷']].map(([value,label,icon])=><button type="button" key={value} className={state.theme===value?'is-selected':''} onClick={()=>update({theme:value})}><span>{icon}</span>{label}</button>)}</div></section>
  <section><header><div><strong>{vi?'Màu nhấn hệ thống':'System accent'}</strong><small>{vi?'Nút, toggle, focus và badge đổi màu thật.':'Buttons, toggles, focus and badges update live.'}</small></div><div className="settings-engine-modes">{[['global',vi?'Toàn hệ thống':'Global'],['app',vi?'Theo ứng dụng':'Per app'],['smart',vi?'Thông minh':'Smart']].map(([value,label])=><button type="button" key={value} className={state.accentMode===value?'is-selected':''} onClick={()=>update({accentMode:value})}>{label}</button>)}</div></header><div className="settings-engine-palette">{palettes.map(([key,item])=><button type="button" key={key} className={state.accent===key?'is-selected':''} style={{'--swatch':item.value}} title={item.label} aria-label={item.label} onClick={()=>update({accent:key})}><span/></button>)}<label className={state.accent==='custom'?'is-selected':''}><input type="color" value={state.accentCustom} onChange={(e)=>update({accent:'custom',accentCustom:e.target.value,accentMode:'global'})}/><span style={{'--swatch':state.accentCustom}}>+</span></label></div></section>
  <div className="settings-engine-fields"><label><span>{vi?'Mật độ hiển thị':'Display density'}</span><select value={state.density} onChange={(e)=>update({density:e.target.value})}><option value="spacious">{vi?'Thoáng':'Spacious'}</option><option value="comfortable">{vi?'Vừa':'Comfortable'}</option><option value="compact">{vi?'Gọn':'Compact'}</option><option value="ultra">{vi?'Siêu gọn':'Ultra compact'}</option></select></label><label><span>{vi?'Kích thước chữ':'Text size'}</span><select value={nearestScale(state.textScale)} onChange={(e)=>update({textScale:Number(e.target.value)})}><option>100</option><option>110</option><option>120</option><option>130</option></select></label><label><span>{vi?'Chuyển động':'Motion'}</span><select value={state.motion} onChange={(e)=>update({motion:e.target.value})}><option value="off">{vi?'Tắt':'Off'}</option><option value="subtle">{vi?'Nhẹ':'Subtle'}</option><option value="balanced">{vi?'Cân bằng':'Balanced'}</option><option value="lively">{vi?'Sinh động':'Lively'}</option></select></label><label><span>{vi?'Hiệu ứng nền':'Background'}</span><select value={state.background} onChange={(e)=>update({background:e.target.value})}><option value="none">{vi?'Không':'None'}</option><option value="gradient">Gradient</option><option value="mesh">Mesh</option><option value="paper">Paper</option></select></label></div>
  <section className="settings-engine-adaptive"><header><div><strong>Adaptive UI</strong><small>{vi?'Các công tắc này tác động thật lên hiệu năng và trợ năng.':'These switches actively change performance and accessibility.'}</small></div><b>{String(tier).toUpperCase()}</b></header><div>{[["adaptivePerformance",vi?'Tự tối ưu hiệu suất':'Adaptive performance'],["reduceMotion",vi?'Giảm chuyển động':'Reduce motion'],["highContrast",vi?'Tương phản cao':'High contrast'],["projector",vi?'Chế độ máy chiếu':'Projector mode'],["batterySaver",vi?'Tiết kiệm pin':'Battery saver']].map(([key,label])=><label key={key}><span>{label}</span><Toggle checked={Boolean(state[key])} onChange={(value)=>update({[key]:value})} label={label}/></label>)}</div></section>
 </div>
}
