const esc = (value = '') => String(value)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#039;');

export const TEXTLAB_TEMPLATES = [
  ['quiz','Quiz Show','Trắc nghiệm','quiz','QUESTION | A | B | C | D | ANSWER'],
  ['true-false','True / False','Đúng hoặc sai','truefalse','STATEMENT | TRUE/FALSE | CORRECTION'],
  ['match-up','Match Up','Nối thuật ngữ','pairs','LEFT | RIGHT'],
  ['matching-pairs','Matching Pairs','Ghép cặp','memory','LEFT | RIGHT'],
  ['memory-match','Memory Match','Ghép cặp ghi nhớ','memory','LEFT | RIGHT'],
  ['find-match','Find the Match','Tìm cặp đúng','pairs','LEFT | RIGHT'],
  ['category-sort','Category Sort','Phân loại theo nhóm','sort','GROUP: item, item, item'],
  ['rank-order','Rank Order','Sắp xếp thứ tự','order','ITEM 1\nITEM 2\nITEM 3'],
  ['sentence-builder','Sentence Builder','Ghép câu','sentence','Complete sentence here.'],
  ['paragraph-builder','Paragraph Builder','Sắp xếp đoạn','order','Sentence 1\nSentence 2\nSentence 3'],
  ['missing-word','Missing Word','Điền từ','cloze','Sentence with [answer].'],
  ['cloze-passage','Cloze Passage','Đoạn văn điền khuyết','cloze','Passage with [answer] gaps.'],
  ['word-scramble','Word Scramble','Xáo chữ','scramble','WORD | CLUE'],
  ['word-search','Word Search','Tìm từ','wordsearch','WORD, WORD, WORD'],
  ['crossword','Crossword Lite','Ô chữ đơn giản','scramble','WORD | CLUE'],
  ['hangman','Hangman','Đoán từ','hangman','WORD | CLUE'],
  ['bingo','Vocabulary Bingo','Bingo từ vựng','bingo','ITEM, ITEM, ITEM'],
  ['flashcards','Flashcards','Thẻ học','cards','FRONT | BACK'],
  ['spin-selector','Spin Selector','Vòng quay lựa chọn','wheel','ITEM\nITEM\nITEM'],
  ['open-box','Open the Box','Mở hộp bí mật','boxes','ITEM\nITEM\nITEM'],
  ['flip-tiles','Flip Tiles','Lật ô khám phá','cards','FRONT | BACK'],
  ['random-cards','Random Cards','Thẻ ngẫu nhiên','cards','FRONT | BACK'],
  ['speaking-cards','Speaking Cards','Thẻ nói','cards','PROMPT | SUPPORT'],
  ['evidence-hunt','Evidence Hunt','Tìm bằng chứng','quiz','QUESTION | A | B | C | D | ANSWER'],
  ['reference-chain','Reference Chain','Từ quy chiếu','quiz','QUESTION | A | B | C | D | ANSWER'],
  ['heading-match','Heading Match','Ghép tiêu đề','pairs','HEADING | PARAGRAPH'],
  ['main-idea','Main Idea','Ý chính','quiz','QUESTION | A | B | C | D | ANSWER'],
  ['sentence-insertion','Sentence Insertion','Chèn câu','quiz','QUESTION | A | B | C | D | ANSWER'],
  ['error-correction','Error Correction','Sửa lỗi','truefalse','SENTENCE | FALSE | CORRECTION'],
  ['summary-builder','Summary Builder','Viết tóm tắt','open','PROMPT'],
  ['retelling','Retelling','Kể lại','open','PROMPT'],
  ['creative-ending','Creative Ending','Viết kết thúc','open','PROMPT'],
  ['debate-cards','Debate Cards','Thẻ tranh luận','cards','STATEMENT | SUPPORT'],
  ['one-minute-speaking','One-minute Speaking','Nói một phút','open','PROMPT'],
  ['whack-answer','Whack the Answer','Chọn nhanh đáp án','quiz','QUESTION | A | B | C | D | ANSWER'],
  ['conveyor-memory','Conveyor Memory','Ghi nhớ băng chuyền','cards','FRONT | BACK'],
].map(([id,title,titleVi,kind,format], index) => ({id,title,titleVi,kind,format,index:index+1}));

export const sampleFor = (kind) => ({
  quiz: 'TITLE: Healthy Habits\n\nWhich habit supports better sleep? | Regular exercise | Late-night gaming | Skipping meals | Excess caffeine | A\nWhich drink is usually the healthiest choice? | Water | Energy drink | Soda | Syrup | A',
  truefalse: 'TITLE: Healthy Habits\n\nRegular physical activity can improve sleep quality. | TRUE | —\nSkipping breakfast always improves concentration. | FALSE | A balanced breakfast can support concentration.',
  pairs: 'TITLE: Environmental Vocabulary\n\nrenewable energy | energy from sources that can naturally be replaced\ncarbon footprint | greenhouse gases produced by a person or activity\nbiodiversity | variety of living species in an ecosystem',
  memory: 'TITLE: Word Pairs\n\nrapid | fast\nassist | help\naccurate | correct\nreliable | dependable',
  sort: 'TITLE: Word Classes\n\nNOUNS: decision, achievement, pollution\nVERBS: decide, achieve, pollute\nADJECTIVES: decisive, achievable, polluted',
  order: 'TITLE: Making Tea\n\nBoil the water.\nPut tea in the cup.\nPour in the hot water.\nWait for three minutes.',
  sentence: 'TITLE: Sentence Builder\n\nStudents should develop healthy study habits.\nTechnology can support independent learning.',
  cloze: 'TITLE: Complete the Text\n\nRegular [exercise] can improve both physical and mental health. A balanced [diet] also provides essential nutrients.',
  scramble: 'TITLE: Word Scramble\n\nEDUCATION | the process of teaching and learning\nSUSTAINABLE | able to continue without harming resources',
  wordsearch: 'TITLE: Environment\n\nCLIMATE, ENERGY, FOREST, OCEAN, RECYCLE, SOLAR',
  bingo: 'TITLE: Vocabulary Bingo\n\nclimate, energy, recycle, forest, ocean, solar, wind, water, habitat, species, carbon, plastic',
  cards: 'TITLE: Discussion Cards\n\nWhat is one healthy habit? | Give a reason and an example.\nHow can schools reduce waste? | Suggest two practical actions.',
  wheel: 'TITLE: Speaking Wheel\n\nDescribe your ideal school.\nName one environmental problem.\nExplain a healthy daily routine.\nTalk about a person you admire.',
  boxes: 'TITLE: Mystery Questions\n\nDescribe a memorable lesson.\nGive three ways to save energy.\nExplain why teamwork matters.\nCreate a question for a classmate.',
  hangman: 'TITLE: Guess the Word\n\nBIODIVERSITY | variety of living species\nEDUCATION | teaching and learning process',
  open: 'TITLE: Writing Task\n\nWrite a short response using at least three details from the lesson.'
}[kind] || 'TITLE: My Activity\n\nITEM 1\nITEM 2');

function parse(raw, kind){
  const lines = String(raw||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);
  const titleLine = lines.find(x=>/^title\s*:/i.test(x));
  const title = titleLine ? titleLine.replace(/^title\s*:/i,'').trim() : 'Brian TextLab Activity';
  const body = lines.filter(x=>x!==titleLine);
  const splitPipe = line => line.split('|').map(x=>x.trim());
  if(['quiz'].includes(kind)) return {title,items:body.map(splitPipe).filter(x=>x.length>=3).map(x=>({q:x[0],options:x.slice(1,-1),answer:x[x.length-1]}))};
  if(kind==='truefalse') return {title,items:body.map(splitPipe).filter(x=>x.length>=2).map(x=>({q:x[0],answer:/^(true|đúng|dung)$/i.test(x[1]),correction:x[2]||''}))};
  if(['pairs','memory','cards'].includes(kind)) return {title,items:body.map(splitPipe).filter(x=>x.length>=2).map(x=>({a:x[0],b:x.slice(1).join(' | ')}))};
  if(kind==='sort') return {title,groups:body.map(line=>{const p=line.split(':');return {name:p[0]?.trim(),items:(p.slice(1).join(':')||'').split(',').map(x=>x.trim()).filter(Boolean)}}).filter(x=>x.name&&x.items.length)};
  if(['order','sentence'].includes(kind)) return {title,items:body};
  if(kind==='cloze') return {title,text:body.join(' ')};
  if(['scramble','hangman'].includes(kind)) return {title,items:body.map(splitPipe).map(x=>({word:x[0]||'',clue:x[1]||''})).filter(x=>x.word)};
  if(['wordsearch','bingo','wheel','boxes'].includes(kind)) return {title,items:body.join(',').split(',').map(x=>x.trim()).filter(Boolean)};
  return {title,prompt:body.join('\n')};
}

const baseCss = `
*{box-sizing:border-box}body{margin:0;background:#eef5fb;color:#102235;font:16px/1.45 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.app{max-width:980px;margin:auto;padding:28px}.hero,.panel{background:#fff;border:2px solid #102235;border-radius:24px;box-shadow:0 8px 0 #102235;margin-bottom:20px}.hero{padding:26px}.eyebrow{font-weight:900;letter-spacing:.15em;color:#087ac1}.hero h1{font-size:clamp(30px,6vw,58px);line-height:1;margin:8px 0}.panel{padding:22px}button{font:inherit;font-weight:800;border:2px solid #102235;border-radius:999px;padding:12px 18px;background:#fff;cursor:pointer}button:hover{transform:translateY(-2px)}button.primary{background:#102235;color:#fff}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px}.choice,.card,.tile{border:2px solid #9ab8d0;border-radius:18px;padding:16px;background:#f7fbff}.choice.correct{background:#dff7e8;border-color:#16834d}.choice.wrong{background:#ffe0e3;border-color:#b7273e}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.score{font-size:22px;font-weight:900}.pair-selected{outline:4px solid #00a7ff}.pair-done{opacity:.35;pointer-events:none}.hidden{display:none!important}.order-item{display:flex;gap:10px;align-items:center;margin:8px 0}.blank{min-width:100px;border:0;border-bottom:3px solid #087ac1;background:#eef7ff;font:inherit;padding:4px 8px}.wheel{width:300px;height:300px;max-width:80vw;border-radius:50%;border:10px solid #102235;display:grid;place-items:center;margin:20px auto;background:conic-gradient(#f65 0 25%,#fc5 0 50%,#6cd 0 75%,#8db 0);font-size:22px;font-weight:900;text-align:center;padding:30px;transition:transform 2s cubic-bezier(.2,.8,.2,1)}.box{min-height:120px}.memory{min-height:110px;display:grid;place-items:center;font-size:20px;font-weight:900}.memory.revealed{background:#fff4c8}.open-answer{width:100%;min-height:180px;padding:14px;font:inherit;border:2px solid #102235;border-radius:16px}@media(max-width:600px){.app{padding:12px}.panel,.hero{border-radius:16px;padding:16px}}
`;

const shell = (data, inner, script='') => `<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(data.title)}</title><style>${baseCss}</style></head><body><main class="app"><header class="hero"><div class="eyebrow">BRIAN TEXTLAB · OFFLINE HTML</div><h1>${esc(data.title)}</h1><p>Không AI · Hoạt động chạy trực tiếp trên trình duyệt</p></header>${inner}</main><script>${script}<\/script></body></html>`;

function quizHtml(data){
 const items=data.items||[]; const body=items.map((it,i)=>`<section class="panel q" data-answer="${esc(String(it.answer).toUpperCase())}"><h2>${i+1}. ${esc(it.q)}</h2><div class="grid">${it.options.map((o,j)=>`<button class="choice" data-key="${String.fromCharCode(65+j)}">${String.fromCharCode(65+j)}. ${esc(o)}</button>`).join('')}</div></section>`).join('');
 return shell(data,`${body}<div class="panel"><div id="score" class="score">Điểm: 0/${items.length}</div><div class="toolbar"><button onclick="location.reload()">Làm lại</button></div></div>`,`let score=0;document.querySelectorAll('.q').forEach(q=>q.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(q.dataset.done)return;q.dataset.done='1';const ok=b.dataset.key===q.dataset.answer;b.classList.add(ok?'correct':'wrong');if(ok)score++;q.querySelectorAll('.choice').forEach(x=>{if(x.dataset.key===q.dataset.answer)x.classList.add('correct')});document.getElementById('score').textContent='Điểm: '+score+'/${items.length}';}));`);
}
function trueFalseHtml(data){const items=data.items||[];return shell(data,items.map((it,i)=>`<section class="panel tf" data-answer="${it.answer?'true':'false'}"><h2>${i+1}. ${esc(it.q)}</h2><div class="toolbar"><button data-v="true">ĐÚNG</button><button data-v="false">SAI</button></div><p class="feedback"></p></section>`).join('')+`<div class="panel score" id="score">Điểm: 0/${items.length}</div>`,`let score=0;document.querySelectorAll('.tf').forEach((q,i)=>q.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(q.dataset.done)return;q.dataset.done='1';let ok=b.dataset.v===q.dataset.answer;b.classList.add(ok?'correct':'wrong');if(ok)score++;q.querySelector('.feedback').textContent=ok?'Chính xác!':'Chưa đúng. Hãy xem lại đáp án.';document.getElementById('score').textContent='Điểm: '+score+'/${items.length}';}));`);}
function pairsHtml(data,memory=false){const items=data.items||[];if(memory){let cards=[];items.forEach((x,i)=>{cards.push({t:x.a,k:i});cards.push({t:x.b,k:i})});cards.sort(()=>Math.random()-.5);return shell(data,`<section class="panel"><div class="grid">${cards.map((c,i)=>`<button class="memory" data-k="${c.k}" data-t="${esc(c.t)}">?</button>`).join('')}</div><p id="status"></p></section>`,`let first=null,lock=false,done=0;document.querySelectorAll('.memory').forEach(c=>c.onclick=()=>{if(lock||c.classList.contains('pair-done')||c===first)return;c.textContent=c.dataset.t;c.classList.add('revealed');if(!first){first=c;return}if(first.dataset.k===c.dataset.k){first.classList.add('pair-done');c.classList.add('pair-done');done+=2;first=null;if(done===${cards.length})document.getElementById('status').textContent='Hoàn thành!';}else{lock=true;setTimeout(()=>{first.textContent='?';c.textContent='?';first.classList.remove('revealed');c.classList.remove('revealed');first=null;lock=false},800)}});`)}
 let cards=[];items.forEach((x,i)=>{cards.push({t:x.a,k:i,s:'a'});cards.push({t:x.b,k:i,s:'b'})});cards.sort(()=>Math.random()-.5);return shell(data,`<section class="panel"><div class="grid">${cards.map(c=>`<button class="tile" data-k="${c.k}" data-s="${c.s}">${esc(c.t)}</button>`).join('')}</div><p id="status">Chọn hai thẻ tương ứng.</p></section>`,`let first=null,done=0;document.querySelectorAll('.tile').forEach(c=>c.onclick=()=>{if(c.classList.contains('pair-done'))return;if(!first){first=c;c.classList.add('pair-selected');return}if(first!==c&&first.dataset.k===c.dataset.k&&first.dataset.s!==c.dataset.s){first.classList.remove('pair-selected');first.classList.add('pair-done');c.classList.add('pair-done');done++;document.getElementById('status').textContent='Đúng! '+done+'/${items.length} cặp';first=null}else{first.classList.remove('pair-selected');first=c;c.classList.add('pair-selected')}});`)}
function sortHtml(data){let items=[];(data.groups||[]).forEach(g=>g.items.forEach(x=>items.push({x,g:g.name})));items.sort(()=>Math.random()-.5);return shell(data,`<section class="panel"><div class="grid">${items.map((it,i)=>`<div class="card"><b>${esc(it.x)}</b><select data-a="${esc(it.g)}"><option value="">Chọn nhóm</option>${(data.groups||[]).map(g=>`<option>${esc(g.name)}</option>`).join('')}</select></div>`).join('')}</div><div class="toolbar"><button class="primary" id="check">Kiểm tra</button><span id="score" class="score"></span></div></section>`,`document.getElementById('check').onclick=()=>{let s=0;document.querySelectorAll('select').forEach(x=>{let ok=x.value===x.dataset.a;x.parentElement.classList.add(ok?'correct':'wrong');if(ok)s++});document.getElementById('score').textContent='Điểm: '+s+'/${items.length}'};`)}
function orderHtml(data,sentence=false){const original=data.items||[];let parts=sentence?original.flatMap(x=>x.split(/\s+/).filter(Boolean)):original;let shuffled=[...parts].sort(()=>Math.random()-.5);return shell(data,`<section class="panel"><div id="list">${shuffled.map((x,i)=>`<div class="order-item"><button data-dir="up">↑</button><button data-dir="down">↓</button><span>${esc(x)}</span></div>`).join('')}</div><div class="toolbar"><button id="check" class="primary">Kiểm tra</button><span id="result" class="score"></span></div></section>`,`window.__correctOrder=${'${JSON.stringify(parts)}'};document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>{let r=b.parentElement,p=r.parentElement;b.dataset.dir==='up'&&r.previousElementSibling?p.insertBefore(r,r.previousElementSibling):b.dataset.dir==='down'&&r.nextElementSibling?p.insertBefore(r.nextElementSibling,r):0});document.getElementById('check').onclick=()=>{let got=[...document.querySelectorAll('.order-item span')].map(x=>x.textContent);document.getElementById('result').textContent=JSON.stringify(got)===JSON.stringify(window.__correctOrder)?'Chính xác!':'Chưa đúng, hãy thử lại.'};`)}
function clozeHtml(data){let answers=[];let html=esc(data.text||'').replace(/\[([^\]]+)\]/g,(_,a)=>{answers.push(a);return `<input class="blank" data-a="${esc(a)}">`});return shell(data,`<section class="panel"><p style="font-size:22px">${html}</p><div class="toolbar"><button class="primary" id="check">Kiểm tra</button><span id="score" class="score"></span></div></section>`,`document.getElementById('check').onclick=()=>{let s=0;document.querySelectorAll('.blank').forEach(x=>{let ok=x.value.trim().toLowerCase()===x.dataset.a.toLowerCase();x.style.background=ok?'#dff7e8':'#ffe0e3';if(ok)s++});document.getElementById('score').textContent='Điểm: '+s+'/${answers.length}'};`)}
function scrambleHtml(data,hangman=false){const items=data.items||[]; if(hangman){return shell(data,items.map((it,i)=>`<section class="panel hang" data-a="${esc(it.word.toUpperCase())}"><h2>${esc(it.clue)}</h2><p class="mask" style="font-size:32px;letter-spacing:.25em"></p><input maxlength="1"><button>Đoán chữ</button><p class="msg"></p></section>`).join(''),`document.querySelectorAll('.hang').forEach(h=>{let found=new Set,answer=h.dataset.a;let draw=()=>h.querySelector('.mask').textContent=[...answer].map(c=>c===' '?' ':found.has(c)?c:'_').join('');draw();h.querySelector('button').onclick=()=>{let c=h.querySelector('input').value.toUpperCase();if(c)found.add(c);draw();if([...answer].every(c=>c===' '||found.has(c)))h.querySelector('.msg').textContent='Chính xác!'}});`)} return shell(data,items.map((it,i)=>`<section class="panel scr" data-a="${esc(it.word.toUpperCase())}"><h2>${[...it.word.toUpperCase()].sort(()=>Math.random()-.5).join(' ')}</h2><p>${esc(it.clue)}</p><input><button>Kiểm tra</button><span></span></section>`).join(''),`document.querySelectorAll('.scr').forEach(x=>x.querySelector('button').onclick=()=>x.querySelector('span').textContent=x.querySelector('input').value.trim().toUpperCase()===x.dataset.a?' ✓ Chính xác':' ✗ Thử lại');`)}
function wheelHtml(data){const items=data.items||[];return shell(data,`<section class="panel"><div id="wheel" class="wheel">Nhấn quay</div><div class="toolbar"><button class="primary" id="spin">QUAY</button></div></section>`,`window.__wheelItems=${'${JSON.stringify(items)}'};let n=0;document.getElementById('spin').onclick=()=>{n+=720+Math.floor(Math.random()*720);let w=document.getElementById('wheel');w.style.transform='rotate('+n+'deg)';setTimeout(()=>w.textContent=window.__wheelItems[Math.floor(Math.random()*window.__wheelItems.length)]||'Không có mục',2000)};`)}
function cardsHtml(data,boxes=false){const items=data.items||[];return shell(data,`<section class="panel"><div class="grid">${items.map((it,i)=>`<button class="${boxes?'box':'card'}" data-b="${esc(it.b||it)}">${boxes?'Hộp '+(i+1):esc(it.a||it)}</button>`).join('')}</div></section>`,`document.querySelectorAll('[data-b]').forEach(c=>c.onclick=()=>{let old=c.textContent;c.textContent=c.dataset.b;c.classList.toggle('revealed');if(!c.classList.contains('revealed'))c.textContent=old});`)}
function bingoHtml(data){const items=(data.items||[]).slice(0,25);return shell(data,`<section class="panel"><div class="grid">${items.map(x=>`<button class="tile">${esc(x)}</button>`).join('')}</div><p id="status"></p></section>`,`document.querySelectorAll('.tile').forEach(x=>x.onclick=()=>{x.classList.toggle('correct');document.getElementById('status').textContent='Đã đánh dấu '+document.querySelectorAll('.tile.correct').length+' ô'});`)}
function openHtml(data){return shell(data,`<section class="panel"><h2>${esc(data.prompt||'Viết câu trả lời của bạn.')}</h2><textarea class="open-answer" placeholder="Nhập câu trả lời..."></textarea><div class="toolbar"><button onclick="localStorage.setItem('textlab-answer',document.querySelector('textarea').value)">Lưu trên thiết bị</button><button onclick="document.querySelector('textarea').value=''">Xóa</button></div></section>`,`document.querySelector('textarea').value=localStorage.getItem('textlab-answer')||'';`)}
function wordsearchHtml(data){const words=(data.items||[]).map(x=>x.toUpperCase()).filter(Boolean);return shell(data,`<section class="panel"><h2>Tìm các từ</h2><p>${words.map(esc).join(' · ')}</p><div class="grid">${words.map(w=>`<button class="tile">${[...w].sort(()=>Math.random()-.5).join(' ')}</button>`).join('')}</div><p>Phiên bản nhẹ: nhấn từng ô khi đã tìm/giải được từ.</p></section>`,`document.querySelectorAll('.tile').forEach(x=>x.onclick=()=>x.classList.toggle('correct'));`)}

export function buildInteractiveHtml(template, raw){const data=parse(raw,template.kind);switch(template.kind){case'quiz':return quizHtml(data);case'truefalse':return trueFalseHtml(data);case'pairs':return pairsHtml(data);case'memory':return pairsHtml(data,true);case'sort':return sortHtml(data);case'order':return orderHtml(data);case'sentence':return orderHtml(data,true);case'cloze':return clozeHtml(data);case'scramble':return scrambleHtml(data);case'hangman':return scrambleHtml(data,true);case'wheel':return wheelHtml(data);case'cards':return cardsHtml(data);case'boxes':return cardsHtml(data,true);case'bingo':return bingoHtml(data);case'wordsearch':return wordsearchHtml(data);default:return openHtml(data)}}

export function downloadHtml(filename, html){const blob=new Blob([html],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
