import fs from 'node:fs';
let passed=0,failed=0;
const read=(p)=>fs.readFileSync(p,'utf8');
const pass=(name,ok)=>{if(ok){console.log(`✓ ${name}`);passed+=1;}else{console.error(`✗ ${name}`);failed+=1;}};
const pkg=JSON.parse(read('package.json'));
const webApps=read('src/pages/WebApps.jsx');
const launcherPrefs=read('src/utils/launcherPreferences.js');
const css=read('src/styles/v1136.css');
const main=read('src/main.jsx');
pass('package version 11.3.6',pkg.version==='11.3.6');
pass('version registry 11.3.6',read('src/config/version.js').includes("APP_VERSION = '11.3.6'")&&read('src/config/version.js').includes("RUNTIME_CORE_VERSION = '2.3.6'"));
pass('launcher config schema 5',launcherPrefs.includes('schemaVersion: 5')&&launcherPrefs.includes("launcherStyle: 'radial'")&&launcherPrefs.includes("['radial', 'water']"));
pass('launcher style selector',webApps.includes('function LauncherStyleSelector')&&webApps.includes('launcher-style-options')&&webApps.includes('onChange?.(option.id)'));
pass('live circular launcher',webApps.includes('function LauncherDock')&&webApps.includes("style = 'radial'")&&css.includes('.launcher-live-dock.is-radial'));
pass('animated water-box launcher',webApps.includes("style === 'water'")&&css.includes('.launcher-live-dock.is-water')&&css.includes('@keyframes launcher-water-float'));
pass('aligned application card grid',css.includes('Strictly aligned cards')&&css.includes('grid-template-columns:repeat(4,minmax(0,1fr))')&&css.includes('grid-auto-rows:244px'));
pass('responsive card grid',css.includes('@media(max-width:1180px)')&&css.includes('@media(max-width:620px)'));
pass('reduced motion support',css.includes('@media(prefers-reduced-motion:reduce)'));
pass('new stylesheet imported',main.includes("import './styles/v1136.css';"));
pass('launcher cloud persistence retained',launcherPrefs.includes(".from('bes_launcher_settings')")&&webApps.includes('saveLauncherConfigToCloud'));
pass('admin hidden apps retained',webApps.includes('HIDDEN_APPS_FOLDER')&&webApps.includes('globallyHiddenIds'));
pass('work submission archive retained',read('src/pages/WorkHub.jsx').includes('Lưu vào Kho học liệu'));
pass('notification alert hotfix retained',read('src/components/StatusMenuBar.jsx').includes('playNoticeTone'));
pass('Student Practice option hotfix retained',read('src/styles/v1132.css').includes('V11.3.2 HF1'));
pass('no internal npm registry',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.3.6 Launcher Gallery Check: ${passed}/${passed+failed} passed`);
if(failed) process.exit(1);
