import fs from 'node:fs';
const read=(f)=>fs.readFileSync(f,'utf8');
const exists=(f)=>fs.existsSync(f);
const checks=[];
const pass=(name,value)=>checks.push([name,Boolean(value)]);
const pkg=JSON.parse(read('package.json'));
const main=read('src/main.jsx');
const index=read('index.html');
const api=read('api/ai.js');
const upload=read('api/google-drive-upload.js');
const runtime=read('src/services/runtime/core.js');
const sql=read('supabase/brian_v10_99_production_hardening.sql');
const hardening=read('src/pages/ProductionHardening.jsx');
const version=JSON.parse(read('public/version.json'));
pass('package version 10.99.0',pkg.version==='10.99.0');
pass('single version config exists',exists('src/config/version.js')&&read('src/config/version.js').includes("APP_VERSION = '10.99.0'"));
pass('generated version registry clean',version.version==='10.99.0'&&version.runtimeCore==='1.6.0'&&version.releaseName==='Production Hardening & Core Cleanup');
pass('service worker version synchronized',read('public/sw.js').includes("const VERSION = '10.99.0'"));
pass('runtime core 1.6.0',runtime.includes('RUNTIME_CORE_VERSION'));
pass('unified roles exist',exists('src/utils/roles.js')&&runtime.includes('loadAssignedRole'));
pass('role management UI exists',hardening.includes("from('system_roles')")&&hardening.includes('Save role'));
pass('production hardening route',main.includes("'production-hardening'")&&exists('src/pages/ProductionHardening.jsx'));
pass('unified utility rail',main.includes('UnifiedUtilityRail')&&exists('src/components/UnifiedUtilityRail.jsx'));
pass('legacy command center removed',!index.includes('bes-command-center-v10871'));
pass('legacy AI patch removed',!index.includes('bes-ai-chat-v10881')&&!index.includes('bes-ai-launcher-slot-v10882'));
pass('legacy platform control removed',!index.includes('bes-platform-control-v10980'));
pass('AI endpoint authenticates',api.includes('requireApprovedUser')&&api.includes('enforceRateLimit'));
pass('AI endpoint audits',api.includes('appendApiAudit'));
pass('upload capped and signature validated',upload.includes('20 * 1024 * 1024')&&upload.includes('hasExpectedSignature')&&upload.includes("feature: 'drive_upload'"));
pass('vulnerable xlsx removed',!pkg.dependencies?.xlsx&&Boolean(pkg.dependencies?.['read-excel-file']));
pass('spreadsheet parser isolated',exists('src/utils/safeSpreadsheet.js')&&read('src/utils/safeSpreadsheet.js').includes("read-excel-file/browser"));
pass('CSS entrypoint split',read('src/index.css').includes("styles/legacy/01-foundation.css")&&exists('src/styles/legacy/06-current-features.css'));
pass('legacy scripts archived',exists('archive/legacy-releases/scripts')&&Object.keys(pkg.scripts||{}).length<=20);
pass('server role table migration',sql.includes('create table if not exists public.system_roles'));
pass('server AI quota migration',sql.includes('bes_v1099_consume_ai_quota'));
pass('server snapshot migration',sql.includes('bes_v1099_create_snapshot')&&sql.includes('bes_v1099_restore_snapshot'));
pass('CSP no longer allows unsafe-eval',!read('vercel.json').includes("'unsafe-eval'"));
pass('Playwright config exists',exists('playwright.config.js')&&exists('tests/e2e/security.spec.js'));
pass('v1099 styles loaded',main.includes("./styles/v1099.css"));
const failed=checks.filter(([,ok])=>!ok);
checks.forEach(([name,ok])=>console.log(`${ok?'✓':'✗'} ${name}`));
console.log(`V10.99 Production Hardening Check: ${checks.length-failed.length}/${checks.length} passed`);
if(failed.length)process.exit(1);
