import React, { useMemo, useRef, useState } from 'react';
import './evidence-workspace.css';

const PEOPLE=['Nguyễn Thị Mai','Trần Minh Đức','Phạm Thu Hà','Lê Hoàng Nam','Đỗ Thị Hương'];
const TYPES=['Dự giờ','Thao giảng','Chuyên đề','Bồi dưỡng học sinh giỏi','Kiểm tra nội bộ','Thi đua','Khác'];
const CRITERIA=['Hoạt động chuyên môn','Đổi mới phương pháp','Ứng dụng công nghệ','Chất lượng học sinh','Phát triển đội ngũ','Công tác quản lý'];
const STATUSES=['Chờ xác minh','Cần bổ sung','Đã xác minh','Đã lưu kho'];
const today=()=>new Date().toISOString().slice(0,10);
const formatDate=value=>{if(!value)return 'Chưa cập nhật';const [y,m,d]=value.split('-');return `${d}/${m}/${y}`};
const slug=(value='')=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const initials=(name='')=>name.split(' ').slice(-2).map(part=>part[0]).join('').toUpperCase();
const isWorkspaceItem=item=>Boolean(item?.status&&item?.criterion&&item?.owner&&Array.isArray(item?.attachments));

export function createDefaultEvidence(){return [
  {id:1,title:'Minh chứng thao giảng Unit 5 – Lớp 11A1',type:'Thao giảng',criterion:'Đổi mới phương pháp',owner:'Nguyễn Thị Mai',dateISO:today(),status:'Đã xác minh',description:'Hình ảnh, kế hoạch bài dạy và phiếu nhận xét sau tiết thao giảng.',links:['Kế hoạch chuyên đề ứng dụng AI'],attachments:[{id:11,name:'ke-hoach-bai-day.pdf',size:245000},{id:12,name:'hinh-anh-thao-giang.jpg',size:480000}],comments:[],history:[{id:111,action:'Đã xác minh minh chứng',actor:'Demo Teacher Admin',time:new Date().toLocaleString('vi-VN')}]},
  {id:2,title:'Minh chứng bồi dưỡng học sinh giỏi tháng 7',type:'Bồi dưỡng học sinh giỏi',criterion:'Chất lượng học sinh',owner:'Trần Minh Đức',dateISO:today(),status:'Chờ xác minh',description:'Kế hoạch, danh sách học sinh và sản phẩm luyện tập.',links:['Hoàn thiện kế hoạch bồi dưỡng học sinh giỏi'],attachments:[{id:21,name:'danh-sach-hoc-sinh.xlsx',size:96000}],comments:[],history:[]},
  {id:3,title:'Minh chứng sinh hoạt chuyên đề AI',type:'Chuyên đề',criterion:'Ứng dụng công nghệ',owner:'Đỗ Thị Hương',dateISO:today(),status:'Cần bổ sung',description:'Tài liệu trình chiếu và phản hồi sau chuyên đề.',links:['Kế hoạch chuyên đề ứng dụng AI'],attachments:[{id:31,name:'slides-chuyen-de.pptx',size:920000}],comments:[],history:[]}
]}

function Icon({name,size=18}){const paths={plus:<path d="M12 5v14M5 12h14"/>,search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>,file:<><path d="M5 3h10l4 4v14H5z"/><path d="M15 3v5h5M8 13h8M8 17h6"/></>,edit:<><path d="m4 20 4-1 11-11-3-3L5 16z"/><path d="m14 6 3 3"/></>,trash:<><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13"/></>,check:<path d="m5 12 4 4L19 6"/>,archive:<><path d="M4 7h16v13H4zM3 4h18v3H3z"/><path d="M9 11h6"/></>,link:<><path d="M10 13a5 5 0 0 0 7 0l2-2a5 5 0 0 0-7-7l-1 1"/><path d="M14 11a5 5 0 0 0-7 0l-2 2a5 5 0 0 0 7 7l1-1"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}

function EvidenceForm({item,onClose,onSave}){
  const fileRef=useRef(null);const [error,setError]=useState('');
  const [form,setForm]=useState(()=>({title:item?.title||'',type:item?.type||TYPES[0],criterion:item?.criterion||CRITERIA[0],owner:item?.owner||PEOPLE[0],dateISO:item?.dateISO||today(),description:item?.description||'',links:(item?.links||[]).join('\n'),attachments:item?.attachments||[]}));
  const addFiles=files=>setForm(current=>({...current,attachments:[...current.attachments,...Array.from(files||[]).map((file,index)=>({id:`${Date.now()}-${index}`,name:file.name,size:file.size,type:file.type}))]}));
  const submit=event=>{event.preventDefault();if(!form.title.trim())return setError('Vui lòng nhập tên minh chứng.');if(!form.attachments.length)return setError('Vui lòng đính kèm ít nhất một tệp.');onSave({...item,...form,title:form.title.trim(),description:form.description.trim(),links:form.links.split('\n').map(value=>value.trim()).filter(Boolean)})};
  return <div className="ew-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><form className="ew-modal" data-testid="evidence-editor-modal" onSubmit={submit}>
    <header><div><span>KHO MINH CHỨNG</span><h2>{item?'Chỉnh sửa minh chứng':'Thêm minh chứng mới'}</h2><p>Lưu thông tin, liên kết công việc và tệp minh chứng.</p></div><button type="button" onClick={onClose} aria-label="Đóng biểu mẫu"><Icon name="close"/></button></header>
    <div className="ew-form-grid">
      <label className="span-2">Tên minh chứng<input aria-label="Tên minh chứng" autoFocus value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label>
      <label>Loại minh chứng<select aria-label="Loại minh chứng" value={form.type} onChange={event=>setForm({...form,type:event.target.value})}>{TYPES.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Tiêu chí<select aria-label="Tiêu chí minh chứng" value={form.criterion} onChange={event=>setForm({...form,criterion:event.target.value})}>{CRITERIA.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Người phụ trách<select aria-label="Người phụ trách minh chứng" value={form.owner} onChange={event=>setForm({...form,owner:event.target.value})}>{PEOPLE.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Ngày thực hiện<input aria-label="Ngày thực hiện minh chứng" type="date" value={form.dateISO} onChange={event=>setForm({...form,dateISO:event.target.value})}/></label>
      <label className="span-2">Mô tả<textarea aria-label="Mô tả minh chứng" rows="4" value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label>
      <label className="span-2">Liên kết nhiệm vụ, hồ sơ hoặc kế hoạch<textarea aria-label="Liên kết minh chứng" rows="3" value={form.links} onChange={event=>setForm({...form,links:event.target.value})} placeholder="Mỗi liên kết một dòng"/></label>
      <div className="span-2 ew-file-field"><div><strong>Tệp minh chứng</strong><small>PDF, Word, hình ảnh, bảng tính hoặc video.</small></div><button type="button" onClick={()=>fileRef.current?.click()}>Chọn tệp</button><input ref={fileRef} hidden multiple type="file" onChange={event=>addFiles(event.target.files)}/></div>
      {!!form.attachments.length&&<div className="span-2 ew-file-list">{form.attachments.map(file=><span key={file.id}><Icon name="file" size={15}/>{file.name}<button type="button" onClick={()=>setForm(current=>({...current,attachments:current.attachments.filter(value=>value.id!==file.id)}))}>×</button></span>)}</div>}
    </div>{error&&<p className="ew-error">{error}</p>}<footer><button type="button" onClick={onClose}>Hủy</button><button className="ew-primary" type="submit">{item?'Lưu thay đổi':'Thêm minh chứng'}</button></footer>
  </form></div>
}

function EvidenceDetail({item,onClose,onEdit,onUpdate,onDelete,setToast}){
  const [comment,setComment]=useState('');
  const changeStatus=(status,action)=>{onUpdate(item.id,{status,history:[...(item.history||[]),{id:Date.now(),action,actor:'Demo Teacher Admin',time:new Date().toLocaleString('vi-VN')}]});setToast(action)};
  const send=()=>{if(!comment.trim())return;const entry={id:Date.now(),author:'Demo Teacher Admin',text:comment.trim(),time:new Date().toLocaleString('vi-VN')};onUpdate(item.id,{comments:[...(item.comments||[]),entry],history:[...(item.history||[]),{id:`h-${entry.id}`,action:'Đã thêm phản hồi',actor:entry.author,time:entry.time}]});setComment('');setToast('Đã lưu phản hồi.')};
  return <div className="ew-detail-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="ew-detail" data-testid="evidence-detail-panel">
    <header><div><span className={`ew-status ${slug(item.status)}`}>{item.status}</span><h2>{item.title}</h2><p>{item.description||'Chưa có mô tả.'}</p></div><button onClick={onClose} aria-label="Đóng chi tiết minh chứng"><Icon name="close"/></button></header>
    <div className="ew-actions"><button onClick={()=>onEdit(item)}><Icon name="edit"/>Chỉnh sửa</button>{item.status!=='Đã xác minh'&&item.status!=='Đã lưu kho'&&<button className="success" onClick={()=>changeStatus('Đã xác minh','Đã xác minh minh chứng')}><Icon name="check"/>Xác minh</button>}<button className="warning" onClick={()=>changeStatus('Cần bổ sung','Đã yêu cầu bổ sung minh chứng')}>Yêu cầu bổ sung</button>{item.status==='Đã xác minh'&&<button onClick={()=>changeStatus('Đã lưu kho','Đã lưu minh chứng vào kho')}><Icon name="archive"/>Lưu kho</button>}<button className="danger" onClick={()=>{if(window.confirm('Xóa minh chứng này?')){onDelete(item.id);onClose()}}}><Icon name="trash"/>Xóa</button></div>
    <section className="ew-summary"><article><span>Loại</span><strong>{item.type}</strong></article><article><span>Tiêu chí</span><strong>{item.criterion}</strong></article><article><span>Người phụ trách</span><strong>{item.owner}</strong></article><article><span>Ngày thực hiện</span><strong>{formatDate(item.dateISO)}</strong></article></section>
    <section><h3>Liên kết công việc</h3><div className="ew-links">{item.links?.length?item.links.map((link,index)=><span key={`${link}-${index}`}><Icon name="link" size={15}/>{link}</span>):<p>Chưa có liên kết.</p>}</div></section>
    <section><h3>Tệp minh chứng</h3><div className="ew-files">{(item.attachments||[]).map(file=><button key={file.id} onClick={()=>setToast(`Tệp ${file.name} đang ở chế độ dữ liệu mẫu.`)}><Icon name="file"/><span><strong>{file.name}</strong><small>{Math.max(1,Math.round((file.size||0)/1024))} KB</small></span></button>)}</div></section>
    <section><h3>Phản hồi</h3>{(item.comments||[]).map(entry=><article className="ew-comment" key={entry.id}><strong>{entry.author}</strong><small>{entry.time}</small><p>{entry.text}</p></article>)}<textarea aria-label="Phản hồi minh chứng" rows="3" value={comment} onChange={event=>setComment(event.target.value)} placeholder="Nhập nhận xét hoặc nội dung cần bổ sung..."/><button className="ew-send" onClick={send}>Gửi phản hồi</button></section>
    <section><h3>Lịch sử xử lý</h3><div className="ew-history">{(item.history||[]).slice().reverse().map(entry=><article key={entry.id}><i/><div><strong>{entry.action}</strong><small>{entry.actor} · {entry.time}</small></div></article>)}</div></section>
  </aside></div>
}

export default function EvidenceWorkspace({evidence=[],setEvidence,updateEvidence,deleteEvidence,setToast}){
  const [query,setQuery]=useState('');const [status,setStatus]=useState('Tất cả');const [type,setType]=useState('Tất cả');const [criterion,setCriterion]=useState('Tất cả');const [editor,setEditor]=useState(null);const [detailId,setDetailId]=useState(null);const [selected,setSelected]=useState([]);
  const compatible=evidence.filter(isWorkspaceItem);
  const sourceEvidence=compatible.length?compatible:createDefaultEvidence();
  const visible=useMemo(()=>sourceEvidence.filter(item=>{const text=`${item.title||''} ${item.owner||''} ${item.type||''} ${item.criterion||''} ${item.description||''}`.toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(status==='Tất cả'||item.status===status)&&(type==='Tất cả'||item.type===type)&&(criterion==='Tất cả'||item.criterion===criterion)}),[sourceEvidence,query,status,type,criterion]);
  const detail=sourceEvidence.find(item=>item.id===detailId)||null;
  const counts={pending:sourceEvidence.filter(item=>item.status==='Chờ xác minh').length,revision:sourceEvidence.filter(item=>item.status==='Cần bổ sung').length,verified:sourceEvidence.filter(item=>item.status==='Đã xác minh').length,archived:sourceEvidence.filter(item=>item.status==='Đã lưu kho').length};
  const applyUpdate=(id,patch)=>{if(compatible.length)updateEvidence(id,patch);else setEvidence(createDefaultEvidence().map(item=>item.id===id?{...item,...patch}:item))};
  const applyDelete=id=>{if(compatible.length)deleteEvidence(id);else{setEvidence(createDefaultEvidence().filter(item=>item.id!==id));setToast('Đã xóa minh chứng.')}};
  const save=data=>{if(editor?.id){applyUpdate(editor.id,{...data,history:[...(editor.history||[]),{id:Date.now(),action:'Đã chỉnh sửa minh chứng',actor:'Demo Teacher Admin',time:new Date().toLocaleString('vi-VN')}]});setToast('Đã cập nhật minh chứng.')}else{const id=Date.now();setEvidence(items=>[{...data,id,status:'Chờ xác minh',comments:[],history:[{id:`new-${id}`,action:'Đã thêm minh chứng',actor:data.owner,time:new Date().toLocaleString('vi-VN')}]},...(items.filter(isWorkspaceItem).length?items.filter(isWorkspaceItem):createDefaultEvidence())]);setToast('Đã thêm minh chứng mới.')}setEditor(null)};
  const bulkUpdate=nextStatus=>{if(!selected.length)return;setEvidence(sourceEvidence.map(item=>selected.includes(item.id)?{...item,status:nextStatus}:item));setToast(`Đã cập nhật ${selected.length} minh chứng.`);setSelected([])};
  const allVisibleSelected=visible.length>0&&visible.every(item=>selected.includes(item.id));
  return <main className="ew-workspace">
    <section className="ew-hero"><div><span>QUẢN TRỊ CHUYÊN MÔN</span><h1>Minh chứng và xác minh</h1><p>Tập hợp, phân loại và theo dõi toàn bộ minh chứng hoạt động của tổ chuyên môn.</p></div><button className="ew-primary" onClick={()=>setEditor({})}><Icon name="plus"/>Thêm minh chứng</button></section>
    <section className="ew-stats"><article><span>Chờ xác minh</span><strong>{counts.pending}</strong></article><article><span>Cần bổ sung</span><strong>{counts.revision}</strong></article><article><span>Đã xác minh</span><strong>{counts.verified}</strong></article><article><span>Đã lưu kho</span><strong>{counts.archived}</strong></article></section>
    <section className="ew-toolbar"><label className="ew-search"><Icon name="search"/><input aria-label="Tìm minh chứng" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Tìm theo tên, người phụ trách, loại hoặc tiêu chí..."/></label><select aria-label="Lọc trạng thái minh chứng" value={status} onChange={event=>setStatus(event.target.value)}><option>Tất cả</option>{STATUSES.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Lọc loại minh chứng" value={type} onChange={event=>setType(event.target.value)}><option>Tất cả</option>{TYPES.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Lọc tiêu chí minh chứng" value={criterion} onChange={event=>setCriterion(event.target.value)}><option>Tất cả</option>{CRITERIA.map(value=><option key={value}>{value}</option>)}</select></section>
    {!!selected.length&&<section className="ew-bulk"><strong>Đã chọn {selected.length} minh chứng</strong><button onClick={()=>bulkUpdate('Đã xác minh')}>Xác minh</button><button onClick={()=>bulkUpdate('Cần bổ sung')}>Yêu cầu bổ sung</button><button onClick={()=>bulkUpdate('Đã lưu kho')}>Lưu kho</button></section>}
    <section className="ew-table-card"><div className="ew-table-head"><input aria-label="Chọn tất cả minh chứng" type="checkbox" checked={allVisibleSelected} onChange={event=>setSelected(event.target.checked?visible.map(item=>item.id):[])}/><span>Minh chứng</span><span>Phân loại</span><span>Phụ trách</span><span>Trạng thái</span><span/></div><div className="ew-table-body">{visible.map(item=><article className="ew-row" data-testid={`evidence-${item.id}`} key={item.id}><input aria-label={`Chọn ${item.title}`} type="checkbox" checked={selected.includes(item.id)} onChange={event=>setSelected(current=>event.target.checked?[...new Set([...current,item.id])]:current.filter(id=>id!==item.id))}/><button className="ew-main" onClick={()=>setDetailId(item.id)}><span className="ew-file-icon"><Icon name="file"/></span><span><strong>{item.title}</strong><small>{formatDate(item.dateISO)} · {(item.attachments||[]).length} tệp</small></span></button><div><strong>{item.type}</strong><small>{item.criterion}</small></div><div className="ew-owner"><span>{initials(item.owner)}</span><strong>{item.owner}</strong></div><span className={`ew-status ${slug(item.status)}`}>{item.status}</span><button aria-label={`Mở ${item.title}`} onClick={()=>setDetailId(item.id)}>›</button></article>)}{!visible.length&&<div className="ew-empty"><Icon name="file" size={32}/><h3>Không tìm thấy minh chứng</h3><p>Hãy thay đổi bộ lọc hoặc thêm minh chứng mới.</p></div>}</div></section>
    {editor&&<EvidenceForm item={editor.id?editor:null} onClose={()=>setEditor(null)} onSave={save}/>} {detail&&<EvidenceDetail item={detail} onClose={()=>setDetailId(null)} onEdit={item=>{setDetailId(null);setEditor(item)}} onUpdate={applyUpdate} onDelete={applyDelete} setToast={setToast}/>}
  </main>
}
