import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const checks=[];
const read=(file)=>fs.readFileSync(path.join(root,file),'utf8');
const exists=(file)=>fs.existsSync(path.join(root,file));
const check=(name,value)=>checks.push({name,pass:Boolean(value)});
const pkg=JSON.parse(read('package.json'));
const version=JSON.parse(read('public/version.json'));
const main=read('src/main.jsx');
const page=read('src/pages/AutomationCenter.jsx');
const engine=read('src/utils/automationEngine.js');
const perms=read('src/utils/permissions.js');
const apps=read('src/data/apps.js');
const nav=read('src/components/GlobalFlatNavigation.jsx');
const command=read('src/components/GlobalCommandPalette.jsx');
const work=read('src/pages/WorkHub.jsx');
const resources=read('src/pages/ResourceLibrary.jsx');
const learning=read('src/pages/LearningIntelligence.jsx');
check('package version 10.96.0',pkg.version==='10.96.0');
check('version manifest 10.96.0',version.version==='10.96.0');
check('V10.96 CSS loaded',main.includes("./styles/v1096.css"));
check('Automation Center page exists',exists('src/pages/AutomationCenter.jsx'));
check('Automation route registered',main.includes("'automation-center'")&&main.includes('<AutomationCenter'));
check('Automation app registered',apps.includes("slug: 'automation-center'"));
check('Automation permission registered',perms.includes("'automation-center': 'route:automation-center'"));
check('Navigation registered',nav.includes("'automation-center'"));
check('Command palette registered',command.includes("route: 'automation-center'"));
check('Rule builder present',page.includes('Tạo quy tắc mới')&&page.includes('requires_approval'));
check('Approval queue present',page.includes('Phê duyệt & chạy')&&engine.includes('pending_approval'));
check('Manual trigger present',engine.includes("value: 'manual'"));
check('Schedule trigger present',engine.includes("value: 'schedule'")&&engine.includes('isRuleDue'));
check('Event trigger present',engine.includes("value: 'event'")&&engine.includes('processAutomationEvent'));
check('Local fallback present',engine.includes('bes-automation-rules-v1096')&&engine.includes("mode: 'local'"));
check('Cloud tables used',engine.includes("'automation_rules'")&&engine.includes("'automation_runs'")&&engine.includes("'automation_events'"));
check('Resource approval event connected',resources.includes("emitAutomationEvent('resource_approved'"));
check('Work submission event connected',work.includes("emitAutomationEvent('work_submitted'"));
check('Learning risk event connected',learning.includes("emitAutomationEvent('learner_risk'"));
check('Work Hub draft transfer connected',work.includes('bes-v1096-automation-work-draft'));
check('Migration exists',exists('supabase/brian_v10_96_automation_center.sql'));
check('Preflight exists',exists('supabase/brian_v10_96_preflight.sql'));
check('Verify SQL exists',exists('supabase/brian_v10_96_verify.sql'));
check('Runtime upgraded',read('src/services/runtime/core.js').includes("version: '1.3.0'"));
check('Platform manifests exist',['public/bes-release-v10.96.0.json','public/bes-modules-v10.96.0.json','public/bes-feature-flags-v10.96.0.json','public/bes-migrations-v10.96.0.json','public/bes-platform-build-v10.96.0.json'].every(exists));
check('Platform runtime exists',exists('public/bes-platform-control-v10960.js'));
check('Service worker upgraded',read('public/sw.js').includes("const VERSION = '10.96.0'"));
check('Version requires SQL',version.requiresSql===true&&version.requiredMigration==='brian_v10_96_automation_center.sql');
check('Schedule boundary disclosed',read('V10_96_0_AUTOMATION_CENTER.md').includes('while Brian English Studio or its installed PWA is open'));
const failed=checks.filter(x=>!x.pass);
for(const item of checks) console.log(`${item.pass?'PASS':'FAIL'}  ${item.name}`);
console.log(`\nV10.96 Automation Center checks: ${checks.length-failed.length}/${checks.length} passed.`);
if(failed.length) process.exit(1);
