import { ClassroomDeck, ClassroomScreen, ClassroomWidget, StudentList } from '../types';

export const SAMPLE_STUDENT_LIST: StudentList = {
  id: 'sl_sample_1',
  name: 'Lớp 10A1 - Anh Văn',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  students: [
    { id: 's1', displayName: 'Nguyễn Văn An', number: '01', absent: false, excluded: false },
    { id: 's2', displayName: 'Trần Thị Bình', number: '02', absent: false, excluded: false },
    { id: 's3', displayName: 'Lê Hoàng Cường', number: '03', absent: false, excluded: false },
    { id: 's4', displayName: 'Phạm Minh Dung', number: '04', absent: false, excluded: false },
    { id: 's5', displayName: 'Vũ Đức Em', number: '05', absent: false, excluded: false },
    { id: 's6', displayName: 'Đặng Phương Giang', number: '06', absent: false, excluded: false },
    { id: 's7', displayName: 'Bùi Thị Hoa', number: '07', absent: false, excluded: false },
    { id: 's8', displayName: 'Đỗ Hải Nam', number: '08', absent: false, excluded: false },
    { id: 's9', displayName: 'Hoàng Anh Quân', number: '09', absent: false, excluded: false },
    { id: 's10', displayName: 'Ngô Thanh Trang', number: '10', absent: false, excluded: false },
    { id: 's11', displayName: 'Lý Quốc Việt', number: '11', absent: false, excluded: false },
    { id: 's12', displayName: 'Phan Như Yến', number: '12', absent: false, excluded: false },
  ],
};

export function createSampleDeck(): {
  deck: ClassroomDeck;
  screens: ClassroomScreen[];
  widgets: ClassroomWidget[];
} {
  const deckId = 'deck_sample_english_unit_review';
  const now = Date.now();

  const screens: ClassroomScreen[] = [
    {
      id: 'screen_1_welcome',
      deckId,
      title: '1. Chào lớp',
      order: 0,
      background: { type: 'gradient', value: 'linear-gradient(135deg, #e8f0fe 0%, #f1f3f4 100%)' },
      transition: 'fade',
      widgetIds: ['w1_welcome_text', 'w1_clock', 'w1_calendar', 'w1_agenda'],
      notes: 'Chào lớp, điểm danh nhanh và nhắc sinh hoạt đầu giờ.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'screen_2_objectives',
      deckId,
      title: '2. Mục tiêu bài học',
      order: 1,
      background: { type: 'color', value: '#ffffff' },
      transition: 'fade',
      widgetIds: ['w2_header', 'w2_objectives_text', 'w2_checklist', 'w2_qr'],
      notes: 'Trình chiếu mục tiêu Unit Review. Yêu cầu HS quét mã QR lấy tài liệu PDF.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'screen_3_warmup',
      deckId,
      title: '3. Hoạt động khởi động',
      order: 2,
      background: { type: 'gradient', value: 'linear-gradient(135deg, #fce8e6 0%, #fff8e1 100%)' },
      transition: 'fade',
      widgetIds: ['w3_header', 'w3_spinner', 'w3_timer', 'w3_work_symbol'],
      notes: 'Khởi động 5 phút với Vòng quay từ vựng theo cặp.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'screen_4_groupwork',
      deckId,
      title: '4. Luyện tập nhóm',
      order: 3,
      background: { type: 'color', value: '#f8f9fa' },
      transition: 'fade',
      widgetIds: ['w4_header', 'w4_group_maker', 'w4_sound_level', 'w4_timer', 'w4_instructions'],
      notes: 'Chia 4 nhóm thảo luận bài đọc. Bật đo tiếng ồn giữ trật tự.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'screen_5_presentation',
      deckId,
      title: '5. Trình bày',
      order: 4,
      background: { type: 'color', value: '#e8f0fe' },
      transition: 'fade',
      widgetIds: ['w5_header', 'w5_randomizer', 'w5_scoreboard', 'w5_stopwatch'],
      notes: 'Gọi đại diện nhóm ngẫu nhiên trình bày và tính điểm thi đua.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'screen_6_quiz',
      deckId,
      title: '6. Kiểm tra nhanh',
      order: 5,
      background: { type: 'color', value: '#fef7e0' },
      transition: 'fade',
      widgetIds: ['w6_header', 'w6_poll', 'w6_traffic_light', 'w6_visual_timer'],
      notes: 'Bình chọn trắc nghiệm trút kiến thức. Giữ đèn xanh khi làm bài.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'screen_7_wrapup',
      deckId,
      title: '7. Kết thúc',
      order: 6,
      background: { type: 'gradient', value: 'linear-gradient(135deg, #e6f4ea 0%, #f1f3f4 100%)' },
      transition: 'fade',
      widgetIds: ['w7_header', 'w7_exit_ticket', 'w7_homework', 'w7_countdown'],
      notes: 'Giao bài tập về nhà và nhắc đếm ngược tới tiết kiểm tra giữa kỳ.',
      createdAt: now,
      updatedAt: now,
    },
  ];

  const widgets: ClassroomWidget[] = [
    // Screen 1: Welcome
    {
      id: 'w1_welcome_text',
      type: 'text',
      screenId: 'screen_1_welcome',
      x: 40,
      y: 40,
      width: 800,
      height: 120,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: {
        fontSize: 38,
        textColor: '#1a73e8',
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 20,
        boxShadow: '0 4px 12px rgba(0,0,0,0.05)',
      },
      settings: {
        content: '🌟 CHÀO MỪNG CÁC EM ĐẾN VỚI TIẾT HỌC TIẾNG ANH - UNIT REVIEW!',
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w1_clock',
      type: 'clock',
      screenId: 'screen_1_welcome',
      x: 870,
      y: 40,
      width: 350,
      height: 220,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: true, // Pinned clock
      style: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 16,
        boxShadow: '0 4px 12px rgba(0,0,0,0.05)',
      },
      settings: {
        mode: 'digital',
        is24Hour: true,
        showSeconds: true,
        showDate: true,
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w1_calendar',
      type: 'calendar',
      screenId: 'screen_1_welcome',
      x: 870,
      y: 280,
      width: 350,
      height: 380,
      rotation: 0,
      zIndex: 3,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 16,
      },
      settings: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w1_agenda',
      type: 'timetable',
      screenId: 'screen_1_welcome',
      x: 40,
      y: 180,
      width: 800,
      height: 480,
      rotation: 0,
      zIndex: 4,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 20,
      },
      settings: {
        items: [
          { id: 'ag1', title: 'Khởi động (Warm-up Vocabulary)', duration: 5, status: 'current' },
          { id: 'ag2', title: 'Luyện tập nhóm (Reading & Speaking)', duration: 15, status: 'pending' },
          { id: 'ag3', title: 'Trình bày sản phẩm nhóm', duration: 10, status: 'pending' },
          { id: 'ag4', title: 'Kiểm tra nhanh (Quick Poll)', duration: 10, status: 'pending' },
          { id: 'ag5', title: 'Tổng kết & Exit Ticket', duration: 5, status: 'pending' },
        ],
      },
      createdAt: now,
      updatedAt: now,
    },

    // Screen 2: Objectives
    {
      id: 'w2_header',
      type: 'text',
      screenId: 'screen_2_objectives',
      x: 40,
      y: 30,
      width: 1180,
      height: 70,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: {
        fontSize: 28,
        textColor: '#202124',
        backgroundColor: '#f1f3f4',
        borderRadius: 12,
        padding: 12,
      },
      settings: { content: '🎯 MỤC TIÊU TIẾT HỌC & TÀI LIỆU BÀI GIẢNG' },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w2_objectives_text',
      type: 'sticky-note',
      screenId: 'screen_2_objectives',
      x: 40,
      y: 120,
      width: 560,
      height: 520,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: {
        backgroundColor: '#fef7e0',
        borderRadius: 16,
        padding: 24,
      },
      settings: {
        title: '3 Mục tiêu chính hôm nay:',
        content: `1. Ôn tập 20 từ vựng chủ đề Environment & Planet Protection.
2. Vận dụng cấu trúc Conditional Type 2 trong thảo luận nhóm.
3. Hoàn thành bài trắc nghiệm kiểm tra phản xạ nói.`,
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w2_checklist',
      type: 'checklist',
      screenId: 'screen_2_objectives',
      x: 630,
      y: 120,
      width: 590,
      height: 280,
      rotation: 0,
      zIndex: 3,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 20 },
      settings: {
        items: [
          { id: 'ck1', text: 'Mở bài giảng PDF trên điện thoại hoặc bảng', completed: true },
          { id: 'ck2', text: 'Chuẩn bị sổ tay từ vựng', completed: true },
          { id: 'ck3', text: 'Phân công trưởng nhóm thảo luận', completed: false },
        ],
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w2_qr',
      type: 'qr-code',
      screenId: 'screen_2_objectives',
      x: 630,
      y: 420,
      width: 590,
      height: 220,
      rotation: 0,
      zIndex: 4,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {
        url: 'https://drive.google.com',
        title: 'Quét mã QR để xem file bài học PDF:',
      },
      createdAt: now,
      updatedAt: now,
    },

    // Screen 3: Warmup
    {
      id: 'w3_header',
      type: 'text',
      screenId: 'screen_3_warmup',
      x: 40,
      y: 30,
      width: 1180,
      height: 60,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { fontSize: 26, textColor: '#1a73e8', padding: 8 },
      settings: { content: '⚡ KHỞI ĐỘNG: VÒNG QUAY TỪ VỰNG NHANH' },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w3_spinner',
      type: 'spinner',
      screenId: 'screen_3_warmup',
      x: 40,
      y: 100,
      width: 580,
      height: 550,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {
        options: [
          'Eco-friendly',
          'Renewable energy',
          'Deforestation',
          'Carbon footprint',
          'Biodiversity',
          'Global warming',
        ],
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w3_timer',
      type: 'timer',
      screenId: 'screen_3_warmup',
      x: 650,
      y: 100,
      width: 570,
      height: 320,
      rotation: 0,
      zIndex: 3,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 20 },
      settings: {
        durationSeconds: 300, // 5 mins
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w3_work_symbol',
      type: 'work-symbols',
      screenId: 'screen_3_warmup',
      x: 650,
      y: 440,
      width: 570,
      height: 210,
      rotation: 0,
      zIndex: 4,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {
        activeSymbol: 'pair',
      },
      createdAt: now,
      updatedAt: now,
    },

    // Screen 4: Group work
    {
      id: 'w4_header',
      type: 'text',
      screenId: 'screen_4_groupwork',
      x: 40,
      y: 20,
      width: 1180,
      height: 60,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { fontSize: 26, textColor: '#137333', padding: 8 },
      settings: { content: '👥 LUYỆN TẬP NHÓM - CHIA NHÓM THẢO LUẬN' },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w4_group_maker',
      type: 'group-maker',
      screenId: 'screen_4_groupwork',
      x: 40,
      y: 90,
      width: 600,
      height: 560,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {
        groupCount: 4,
        studentListId: 'sl_sample_1',
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w4_sound_level',
      type: 'sound-level',
      screenId: 'screen_4_groupwork',
      x: 660,
      y: 90,
      width: 560,
      height: 270,
      rotation: 0,
      zIndex: 3,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {
        threshold: 65,
        sensitivity: 'medium',
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w4_timer',
      type: 'timer',
      screenId: 'screen_4_groupwork',
      x: 660,
      y: 380,
      width: 560,
      height: 270,
      rotation: 0,
      zIndex: 4,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {
        durationSeconds: 900, // 15 mins
      },
      createdAt: now,
      updatedAt: now,
    },

    // Screen 5: Presentation
    {
      id: 'w5_header',
      type: 'text',
      screenId: 'screen_5_presentation',
      x: 40,
      y: 20,
      width: 1180,
      height: 60,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { fontSize: 26, textColor: '#1a73e8', padding: 8 },
      settings: { content: '🎤 BÁO CÁO TRÌNH BÀY & CHẤM ĐIỂM THI ĐUẢ' },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w5_randomizer',
      type: 'randomizer',
      screenId: 'screen_5_presentation',
      x: 40,
      y: 90,
      width: 450,
      height: 560,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {
        studentListId: 'sl_sample_1',
        fairnessMode: true,
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w5_scoreboard',
      type: 'scoreboard',
      screenId: 'screen_5_presentation',
      x: 510,
      y: 90,
      width: 420,
      height: 560,
      rotation: 0,
      zIndex: 3,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {
        teams: [
          { id: 't1', name: 'Nhóm 1 (Green)', score: 15, color: '#34a853' },
          { id: 't2', name: 'Nhóm 2 (Blue)', score: 20, color: '#4285f4' },
          { id: 't3', name: 'Nhóm 3 (Yellow)', score: 18, color: '#fbbc04' },
          { id: 't4', name: 'Nhóm 4 (Red)', score: 12, color: '#ea4335' },
        ],
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w5_stopwatch',
      type: 'stopwatch',
      screenId: 'screen_5_presentation',
      x: 950,
      y: 90,
      width: 270,
      height: 560,
      rotation: 0,
      zIndex: 4,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {},
      createdAt: now,
      updatedAt: now,
    },

    // Screen 6: Quiz
    {
      id: 'w6_header',
      type: 'text',
      screenId: 'screen_6_quiz',
      x: 40,
      y: 20,
      width: 1180,
      height: 60,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { fontSize: 26, textColor: '#b06000', padding: 8 },
      settings: { content: '❓ KIỂM TRA NHANH - CÂU HỎI TRẮC NGHIỆM' },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w6_poll',
      type: 'poll',
      screenId: 'screen_6_quiz',
      x: 40,
      y: 90,
      width: 680,
      height: 560,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 20 },
      settings: {
        question: 'If we plant more trees, what _____ to the air quality?',
        options: [
          { id: 'o1', text: 'A. will happen', votes: 18 },
          { id: 'o2', text: 'B. would happen', votes: 4 },
          { id: 'o3', text: 'C. happened', votes: 1 },
          { id: 'o4', text: 'D. happens', votes: 2 },
        ],
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w6_traffic_light',
      type: 'traffic-light',
      screenId: 'screen_6_quiz',
      x: 740,
      y: 90,
      width: 480,
      height: 270,
      rotation: 0,
      zIndex: 3,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {
        state: 'green',
        labels: {
          green: 'Làm bài yên lặng',
          yellow: 'Còn 1 phút nữa',
          red: 'Dừng bút chú ý',
        },
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w6_visual_timer',
      type: 'visual-timer',
      screenId: 'screen_6_quiz',
      x: 740,
      y: 380,
      width: 480,
      height: 270,
      rotation: 0,
      zIndex: 4,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 16 },
      settings: {
        durationSeconds: 180, // 3 mins
        displayMode: 'circle',
      },
      createdAt: now,
      updatedAt: now,
    },

    // Screen 7: Wrapup
    {
      id: 'w7_header',
      type: 'text',
      screenId: 'screen_7_wrapup',
      x: 40,
      y: 20,
      width: 1180,
      height: 60,
      rotation: 0,
      zIndex: 1,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { fontSize: 26, textColor: '#137333', padding: 8 },
      settings: { content: '🏁 KẾT THÚC TIẾT HỌC & BÀI TẬP VỀ NHÀ' },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w7_exit_ticket',
      type: 'sticky-note',
      screenId: 'screen_7_wrapup',
      x: 40,
      y: 90,
      width: 560,
      height: 270,
      rotation: 0,
      zIndex: 2,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#e6f4ea', borderRadius: 16, padding: 20 },
      settings: {
        title: '🎟️ EXIT TICKET (Phiếu ra về)',
        content: `Viết ra giấy 1 từ vựng mới em thích nhất hôm nay và 1 câu ví dụ dùng từ đó. Nộp lại tại bàn giáo viên khi ra về!`,
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w7_homework',
      type: 'checklist',
      screenId: 'screen_7_wrapup',
      x: 40,
      y: 380,
      width: 560,
      height: 270,
      rotation: 0,
      zIndex: 3,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 20 },
      settings: {
        items: [
          { id: 'hw1', text: 'Hoàn thành bài tập 1, 2, 3 trang 45 Sách Bài Tập', completed: false },
          { id: 'hw2', text: 'Học thuộc lòng 10 từ vựng chủ đề Environment', completed: false },
          { id: 'hw3', text: 'Chuẩn bị bài Unit 6: Gender Equality', completed: false },
        ],
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'w7_countdown',
      type: 'countdown',
      screenId: 'screen_7_wrapup',
      x: 630,
      y: 90,
      width: 590,
      height: 560,
      rotation: 0,
      zIndex: 4,
      opacity: 1,
      locked: false,
      hidden: false,
      pinned: false,
      style: { backgroundColor: '#ffffff', borderRadius: 16, padding: 24 },
      settings: {
        title: '⏰ Đếm ngược tới Bài Kiểm Tra Giữa Kỳ:',
        targetTimestamp: Date.now() + 14 * 24 * 60 * 60 * 1000, // 14 days
      },
      createdAt: now,
      updatedAt: now,
    },
  ];

  const deck: ClassroomDeck = {
    id: deckId,
    title: 'Tiết học tiếng Anh – Unit Review',
    description: 'Bài giảng ôn tập từ vựng, ngữ pháp và thảo luận nhóm môn Tiếng Anh',
    tags: ['Tiếng Anh', 'Lớp 10', 'Unit Review'],
    favorite: true,
    createdAt: now,
    updatedAt: now,
    lastOpenedAt: now,
    settings: {
      aspectRatio: '16:9',
      autoSave: true,
      safeArea: true,
    },
    screenIds: screens.map((s) => s.id),
  };

  return { deck, screens, widgets };
}
