from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
component_path = ROOT / 'src/components/GlobalAttendanceNavigationTab.jsx'
css_path = ROOT / 'src/components/attendance/AttendanceMaterial3.css'


def replace_once(text: str, needle: str, replacement: str, label: str) -> str:
    count = text.count(needle)
    if count != 1:
        raise RuntimeError(f'{label}: expected one anchor, found {count}')
    return text.replace(needle, replacement, 1)


attendance = component_path.read_text()

attendance = replace_once(
    attendance,
    "import AttendanceMonthlyReport from './attendance/AttendanceMonthlyReport.jsx';\nimport AttendanceClassEditor from './attendance/AttendanceClassEditor.jsx';\nimport './attendance/AttendanceMaterial3.css';",
    "import AttendanceMonthlyReport from './attendance/AttendanceMonthlyReport.jsx';\nimport AttendanceClassEditor from './attendance/AttendanceClassEditor.jsx';\nimport { ATTENDANCE_PROOF_BUCKET, buildAttendanceProofPath, prepareAttendanceProofImage } from '../utils/attendanceProofImage.js';\nimport './attendance/AttendanceMaterial3.css';",
    'proof utility import',
)

attendance = replace_once(
    attendance,
    "const SESSION_COLUMNS = 'id,class_id,class_type,class_name,subject,teacher_id,teacher_name,teacher_email,attendance_date,checked_at,checked_by,total_students,present_count,absent_count,note,session_status,lesson_periods,cancellation_reason,teaching_room,teaching_time_range,created_at';",
    "const SESSION_COLUMNS = 'id,class_id,class_type,class_name,subject,teacher_id,teacher_name,teacher_email,attendance_date,checked_at,checked_by,total_students,present_count,absent_count,note,session_status,lesson_periods,cancellation_reason,teaching_room,teaching_time_range,proof_path,created_at';",
    'session proof column',
)

attendance = replace_once(
    attendance,
    "  const [reportMonth, setReportMonth] = useState(today.slice(0, 7));\n  const fileRef = useRef(null);",
    "  const [reportMonth, setReportMonth] = useState(today.slice(0, 7));\n  const [proofFile, setProofFile] = useState(null);\n  const [proofPreviewUrl, setProofPreviewUrl] = useState('');\n  const [historyProofUrl, setHistoryProofUrl] = useState('');\n  const [historyProofLoading, setHistoryProofLoading] = useState(false);\n  const fileRef = useRef(null);\n  const proofInputRef = useRef(null);",
    'proof state',
)

invalid_anchor = """  const invalidAbsentRows = useMemo(() => draft.filter((row) => row.present === false && (\n    !row.absence_reason_code || (row.absence_reason_code === 'other' && !String(row.absence_note || '').trim())\n  )), [draft]);\n\n  function toggleAbsent(memberKeyValue) {"""
invalid_replacement = """  const invalidAbsentRows = useMemo(() => draft.filter((row) => row.present === false && (\n    !row.absence_reason_code || (row.absence_reason_code === 'other' && !String(row.absence_note || '').trim())\n  )), [draft]);\n\n  useEffect(() => {\n    if (proofPreviewUrl) URL.revokeObjectURL(proofPreviewUrl);\n    setProofFile(null);\n    setProofPreviewUrl('');\n    if (proofInputRef.current) proofInputRef.current.value = '';\n  }, [selectedClassId, attendanceDate]);\n\n  useEffect(() => () => {\n    if (proofPreviewUrl) URL.revokeObjectURL(proofPreviewUrl);\n  }, [proofPreviewUrl]);\n\n  function toggleAbsent(memberKeyValue) {"""
attendance = replace_once(attendance, invalid_anchor, invalid_replacement, 'proof selection reset effects')

function_anchor = """  function updateAbsenceField(memberKeyValue, patch) {\n    if (isDayLocked) return;\n    setDraft((current) => current.map((row) => row.member_key === memberKeyValue ? { ...row, ...patch } : row));\n  }\n\n  async function confirmAttendance() {"""
function_replacement = """  function updateAbsenceField(memberKeyValue, patch) {\n    if (isDayLocked) return;\n    setDraft((current) => current.map((row) => row.member_key === memberKeyValue ? { ...row, ...patch } : row));\n  }\n\n  function clearProofSelection() {\n    if (proofPreviewUrl) URL.revokeObjectURL(proofPreviewUrl);\n    setProofFile(null);\n    setProofPreviewUrl('');\n    if (proofInputRef.current) proofInputRef.current.value = '';\n  }\n\n  function chooseProofFile(file) {\n    if (!file) return;\n    if (!String(file.type || '').startsWith('image/')) {\n      setError('Vui lòng chọn một tệp hình ảnh để làm minh chứng.');\n      return;\n    }\n    if (proofPreviewUrl) URL.revokeObjectURL(proofPreviewUrl);\n    setProofFile(file);\n    setProofPreviewUrl(URL.createObjectURL(file));\n    setError('');\n  }\n\n  async function uploadAttendanceProof(session) {\n    if (!proofFile || !session?.id || !client) return '';\n    const prepared = await prepareAttendanceProofImage(proofFile);\n    const proofPath = buildAttendanceProofPath(session.id);\n    const { error: uploadError } = await client.storage\n      .from(ATTENDANCE_PROOF_BUCKET)\n      .upload(proofPath, prepared, { contentType: 'image/jpeg', upsert: false });\n    if (uploadError) throw uploadError;\n\n    const { error: attachError } = await client.rpc('bes_set_extra_attendance_proof', {\n      p_session_id: session.id,\n      p_proof_path: proofPath,\n    });\n    if (attachError) {\n      await client.storage.from(ATTENDANCE_PROOF_BUCKET).remove([proofPath]);\n      throw attachError;\n    }\n    clearProofSelection();\n    return proofPath;\n  }\n\n  async function removeAttendanceProofPaths(paths) {\n    const cleanPaths = Array.from(new Set((paths || []).map((value) => String(value || '').trim()).filter(Boolean)));\n    if (!client || !cleanPaths.length) return;\n    const { error: removeError } = await client.storage.from(ATTENDANCE_PROOF_BUCKET).remove(cleanPaths);\n    if (removeError) console.warn('Không thể dọn ảnh minh chứng điểm danh:', removeError.message || removeError);\n  }\n\n  async function confirmAttendance() {"""
attendance = replace_once(attendance, function_anchor, function_replacement, 'proof helper functions')

confirm_anchor = """      const created = Array.isArray(data) ? data[0] : data;\n      setDaySession(created || null);\n      setNotice(`Đã chốt điểm danh ${selectedClass.class_name} ngày ${formatDate(attendanceDate)} · GV ${sessionTeacher} · ${summary.present}/${summary.total} có mặt.`);\n      await loadAll();\n      await loadDaySession();\n      await loadTeacherDaySessions();\n      await loadMonthlySessions();"""
confirm_replacement = """      const created = Array.isArray(data) ? data[0] : data;\n      setDaySession(created || null);\n      let proofSaved = false;\n      let proofUploadFailure = '';\n      if (proofFile && created?.id) {\n        try {\n          await uploadAttendanceProof(created);\n          proofSaved = true;\n        } catch (proofError) {\n          proofUploadFailure = proofError?.message || 'Không thể tải ảnh minh chứng lên hệ thống.';\n          clearProofSelection();\n        }\n      }\n      await loadAll();\n      await loadDaySession();\n      await loadTeacherDaySessions();\n      await loadMonthlySessions();\n      setNotice(`Đã chốt điểm danh ${selectedClass.class_name} ngày ${formatDate(attendanceDate)} · GV ${sessionTeacher} · ${summary.present}/${summary.total} có mặt.${proofSaved ? ' · Đã lưu ảnh minh chứng.' : ''}`);\n      if (proofUploadFailure) setError(`Điểm danh đã được chốt, nhưng ảnh minh chứng chưa được lưu: ${proofUploadFailure}`);"""
attendance = replace_once(attendance, confirm_anchor, confirm_replacement, 'proof upload after confirm')

cancel_anchor = """      const created = Array.isArray(data) ? data[0] : data;\n      setDaySession(created || null);\n      setShowCancelSession(false);\n      setNotice(`Đã hủy buổi học ${selectedClass.class_name} ngày ${formatDate(attendanceDate)}.`);"""
cancel_replacement = """      const created = Array.isArray(data) ? data[0] : data;\n      setDaySession(created || null);\n      setShowCancelSession(false);\n      clearProofSelection();\n      setNotice(`Đã hủy buổi học ${selectedClass.class_name} ngày ${formatDate(attendanceDate)}.`);"""
attendance = replace_once(attendance, cancel_anchor, cancel_replacement, 'clear proof on cancelled session')

class_delete_anchor = """    try {\n      const { error: deleteError } = await client.rpc('bes_delete_extra_class', { p_class_id: classRow.id });\n      if (deleteError) throw deleteError;\n      if (String(selectedClassId) === String(classRow.id)) setSelectedClassId('');"""
class_delete_replacement = """    try {\n      const classProofPaths = sessions.filter((session) => String(session.class_id) === String(classRow.id)).map((session) => session.proof_path);\n      const { error: deleteError } = await client.rpc('bes_delete_extra_class', { p_class_id: classRow.id });\n      if (deleteError) throw deleteError;\n      await removeAttendanceProofPaths(classProofPaths);\n      if (String(selectedClassId) === String(classRow.id)) setSelectedClassId('');"""
attendance = replace_once(attendance, class_delete_anchor, class_delete_replacement, 'class proof cleanup')

session_delete_anchor = """      const { error: deleteError } = await client.rpc('bes_delete_extra_attendance_session', { p_session_id: session.id });\n      if (deleteError) throw deleteError;\n      setSelectedSessionId(''); setRecords([]);"""
session_delete_replacement = """      const { error: deleteError } = await client.rpc('bes_delete_extra_attendance_session', { p_session_id: session.id });\n      if (deleteError) throw deleteError;\n      await removeAttendanceProofPaths([session.proof_path]);\n      setSelectedSessionId(''); setRecords([]);"""
attendance = replace_once(attendance, session_delete_anchor, session_delete_replacement, 'single session proof cleanup')

bulk_start_anchor = """    const failed = [];\n    const deletedIds = new Set();\n    try {"""
bulk_start_replacement = """    const failed = [];\n    const deletedIds = new Set();\n    const proofPathsToRemove = [];\n    try {"""
attendance = replace_once(attendance, bulk_start_anchor, bulk_start_replacement, 'bulk proof cleanup state')

bulk_success_anchor = """        } else {\n          deletedIds.add(String(session.id));\n        }\n      }\n      if (deletedIds.has(String(selectedSessionId))) {"""
bulk_success_replacement = """        } else {\n          deletedIds.add(String(session.id));\n          if (session.proof_path) proofPathsToRemove.push(session.proof_path);\n        }\n      }\n      await removeAttendanceProofPaths(proofPathsToRemove);\n      if (deletedIds.has(String(selectedSessionId))) {"""
attendance = replace_once(attendance, bulk_success_anchor, bulk_success_replacement, 'bulk proof cleanup execution')

history_anchor = """  const selectedSession = sessions.find((session) => String(session.id) === String(selectedSessionId)) || monthlySessions.find((session) => String(session.id) === String(selectedSessionId));\n  const selectedAbsentRecords = records.filter((record) => record.status === 'absent');"""
history_replacement = """  const selectedSession = sessions.find((session) => String(session.id) === String(selectedSessionId)) || monthlySessions.find((session) => String(session.id) === String(selectedSessionId));\n\n  useEffect(() => {\n    let cancelled = false;\n    setHistoryProofUrl('');\n    if (!client || view !== 'history' || !canAccessAttendanceView('history') || !selectedSession?.proof_path) {\n      setHistoryProofLoading(false);\n      return undefined;\n    }\n    setHistoryProofLoading(true);\n    client.storage.from(ATTENDANCE_PROOF_BUCKET).createSignedUrl(selectedSession.proof_path, 300)\n      .then(({ data, error: signedUrlError }) => {\n        if (cancelled) return;\n        setHistoryProofLoading(false);\n        if (signedUrlError) {\n          setHistoryProofUrl('');\n          return;\n        }\n        setHistoryProofUrl(data?.signedUrl || '');\n      });\n    return () => { cancelled = true; };\n  }, [view, selectedSession?.id, selectedSession?.proof_path, currentUser?.permissions, systemRole]);\n\n  const selectedAbsentRecords = records.filter((record) => record.status === 'absent');"""
attendance = replace_once(attendance, history_anchor, history_replacement, 'history signed proof url')

footer_anchor = '                  <footer className="attendance-confirm-bar">'
proof_card = """                  <section className={`att-m3-proof-card ${isDayLocked ? 'is-locked' : ''}`}>\n                    <div className="att-m3-proof-card-head"><span aria-hidden="true">📷</span><div><strong>Minh chứng hình ảnh</strong><small>Không bắt buộc · 01 ảnh cho mỗi buổi điểm danh</small></div>{daySession?.proof_path ? <em>Đã lưu</em> : null}</div>\n                    <input ref={proofInputRef} type="file" accept="image/*" capture="environment" hidden disabled={isDayLocked} onChange={(event) => chooseProofFile(event.target.files?.[0])} />\n                    {proofPreviewUrl && !isDayLocked ? <div className="att-m3-proof-preview"><img src={proofPreviewUrl} alt="Ảnh minh chứng đang chọn" /><div><b>Ảnh đã sẵn sàng</b><span>Ảnh sẽ được nén và lưu khi xác nhận điểm danh.</span><p><button type="button" onClick={() => proofInputRef.current?.click()}>Đổi ảnh</button><button type="button" className="is-remove" onClick={clearProofSelection}>Xóa ảnh</button></p></div></div> : !isDayLocked ? <button className="att-m3-proof-picker" type="button" onClick={() => proofInputRef.current?.click()}><span aria-hidden="true">📷</span><b>Chụp ảnh / Chọn ảnh</b><small>Tùy chọn, không ảnh hưởng việc xác nhận điểm danh</small></button> : <div className="att-m3-proof-locked-note">{daySession?.proof_path ? 'Buổi này đã có ảnh minh chứng. Xem ảnh tại tab Lịch sử.' : 'Buổi này đã chốt và không có ảnh minh chứng.'}</div>}\n                  </section>\n                  <footer className="attendance-confirm-bar">"""
attendance = replace_once(attendance, footer_anchor, proof_card, 'quick attendance proof card')

history_detail_anchor = """                {selectedSession.session_status === 'cancelled' ? <>"""
history_detail_replacement = """                {selectedSession.proof_path ? <section className="attendance-history-proof"><header><div><span aria-hidden="true">📷</span><div><strong>Minh chứng hình ảnh</strong><small>Ảnh được lưu riêng tư và chỉ mở bằng liên kết tạm thời.</small></div></div>{historyProofUrl ? <a href={historyProofUrl} target="_blank" rel="noreferrer">Mở ảnh lớn</a> : null}</header>{historyProofLoading ? <div className="attendance-history-proof-loading">Đang tải ảnh minh chứng…</div> : historyProofUrl ? <a className="attendance-history-proof-image" href={historyProofUrl} target="_blank" rel="noreferrer"><img src={historyProofUrl} alt={`Minh chứng điểm danh ${selectedSession.class_name} ngày ${formatDate(selectedSession.attendance_date)}`} /></a> : <div className="attendance-history-proof-loading">Không thể tải ảnh minh chứng lúc này.</div>}</section> : null}\n\n                {selectedSession.session_status === 'cancelled' ? <>"""
attendance = replace_once(attendance, history_detail_anchor, history_detail_replacement, 'history proof viewer')

component_path.write_text(attendance)

css = css_path.read_text()
if '/* Optional private attendance photo proof */' not in css:
    css += r'''

/* Optional private attendance photo proof */
.att-m3-proof-card{margin-top:12px;padding:12px;border:1px solid color-mix(in srgb,var(--att-m3-primary) 18%,var(--att-m3-outline-variant));border-radius:18px;background:color-mix(in srgb,var(--att-m3-primary-container) 34%,var(--att-m3-surface));box-shadow:0 1px 5px rgba(35,42,58,.06)}
.att-m3-proof-card-head{display:flex;align-items:center;gap:10px}.att-m3-proof-card-head>span{display:grid;place-items:center;width:34px;height:34px;border-radius:12px;background:var(--att-m3-primary-container);font-size:18px}.att-m3-proof-card-head>div{display:grid;gap:2px;min-width:0}.att-m3-proof-card-head strong{font-size:12px;color:var(--att-m3-on-surface)}.att-m3-proof-card-head small{font-size:9px;color:var(--att-m3-on-variant)}.att-m3-proof-card-head em{margin-left:auto;padding:5px 8px;border-radius:999px;background:var(--att-m3-success-container);color:var(--att-m3-success);font-size:9px;font-style:normal;font-weight:900}.att-m3-proof-picker{display:grid;grid-template-columns:auto 1fr;column-gap:9px;row-gap:1px;align-items:center;width:100%;margin-top:10px;padding:10px 12px;border:1px dashed color-mix(in srgb,var(--att-m3-primary) 38%,var(--att-m3-outline-variant));border-radius:14px;background:var(--att-m3-surface);color:var(--att-m3-primary);font:inherit;text-align:left;cursor:pointer}.att-m3-proof-picker>span{grid-row:1/3;font-size:18px}.att-m3-proof-picker b{font-size:11px}.att-m3-proof-picker small{font-size:9px;color:var(--att-m3-on-variant)}.att-m3-proof-picker:hover{background:color-mix(in srgb,var(--att-m3-primary-container) 38%,var(--att-m3-surface))}.att-m3-proof-picker:focus-visible,.att-m3-proof-preview button:focus-visible,.attendance-history-proof a:focus-visible{outline:2px solid var(--att-m3-primary);outline-offset:2px}.att-m3-proof-preview{display:grid;grid-template-columns:118px 1fr;gap:12px;align-items:center;margin-top:10px;padding:9px;border-radius:14px;background:var(--att-m3-surface)}.att-m3-proof-preview img{width:118px;height:78px;object-fit:cover;border-radius:11px}.att-m3-proof-preview>div{display:grid;gap:3px}.att-m3-proof-preview b{font-size:11px}.att-m3-proof-preview span{font-size:9px;color:var(--att-m3-on-variant)}.att-m3-proof-preview p{display:flex;gap:6px;margin:4px 0 0}.att-m3-proof-preview button{height:30px;border:0;border-radius:10px;padding:0 10px;background:var(--att-m3-secondary-container);color:var(--att-m3-primary);font:inherit;font-size:9px;font-weight:900;cursor:pointer}.att-m3-proof-preview button.is-remove{background:var(--att-m3-danger-container);color:var(--att-m3-danger)}.att-m3-proof-locked-note{margin-top:9px;padding:9px 11px;border-radius:12px;background:var(--att-m3-surface-container);color:var(--att-m3-on-variant);font-size:9px;font-weight:700}.att-m3-proof-card.is-locked{background:var(--att-m3-surface-container)}
.attendance-history-proof{margin:12px 0;padding:12px;border-radius:18px;background:color-mix(in srgb,var(--att-m3-primary-container) 38%,var(--att-m3-surface));border:1px solid color-mix(in srgb,var(--att-m3-primary) 16%,var(--att-m3-outline-variant))}.attendance-history-proof>header{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px}.attendance-history-proof>header>div{display:flex;align-items:center;gap:9px}.attendance-history-proof>header>div>span{display:grid;place-items:center;width:34px;height:34px;border-radius:12px;background:var(--att-m3-primary-container);font-size:18px}.attendance-history-proof>header>div>div{display:grid;gap:2px}.attendance-history-proof strong{font-size:12px}.attendance-history-proof small{font-size:9px;color:var(--att-m3-on-variant)}.attendance-history-proof>header>a{flex:0 0 auto;padding:7px 10px;border-radius:10px;background:var(--att-m3-primary);color:var(--att-m3-on-primary);font-size:9px;font-weight:900;text-decoration:none}.attendance-history-proof-image{display:block;overflow:hidden;border-radius:14px;background:var(--att-m3-surface)}.attendance-history-proof-image img{display:block;width:100%;max-height:330px;object-fit:contain;background:#111}.attendance-history-proof-loading{display:grid;place-items:center;min-height:92px;border-radius:14px;background:var(--att-m3-surface);color:var(--att-m3-on-variant);font-size:10px;font-weight:750}
@media(max-width:760px){.att-m3-proof-preview{grid-template-columns:92px 1fr}.att-m3-proof-preview img{width:92px;height:68px}.attendance-history-proof>header{align-items:flex-start;flex-direction:column}.attendance-history-proof>header>a{align-self:flex-start}}
'''
    css_path.write_text(css)

print('Applied attendance photo proof to latest main-compatible component and styles.')
