import fs from 'node:fs';
const read=(p)=>fs.existsSync(p)?fs.readFileSync(p,'utf8'):'';
const page=read('src/pages/WorkDashboard.jsx');
const css=read('src/styles/work-dashboard-luxury-v1167.css');
const checks=[]; const add=(n,v)=>checks.push([n,Boolean(v)]);
add('Luxury stylesheet imported after base dashboard CSS', page.indexOf("work-dashboard-luxury-v1167.css") > page.indexOf("work-dashboard-v1167.css"));
add('Large hero is removed to match approved card-first mockup', css.includes('.wd5-hero{display:none!important}'));
add('Five equal metric widgets remain', css.includes('grid-template-columns:repeat(5,minmax(0,1fr))'));
add('Metric icons use premium square gradient treatment', css.includes('border-radius:15px!important') && css.includes('wdlux-icon-breathe'));
add('Main cards have equal fixed row height', css.includes('.wd5-main-grid{grid-template-columns:repeat(2,minmax(0,1fr));grid-auto-rows:540px}'));
add('Management cards have equal fixed row height', css.includes('.wd5-triple-grid{grid-template-columns:repeat(3,minmax(0,1fr));grid-auto-rows:300px'));
add('Cards use aligned header body footer structure', css.includes('.wd5-card-head') && css.includes('.wd5-card-body') && css.includes('.wd5-card-foot'));
add('Card content scrolls independently', css.includes('.wd5-scroll-list::-webkit-scrollbar'));
add('Task rows have premium hover interaction', css.includes('.wd5-task-row:hover') && css.includes('translateX(4px)'));
add('Filters have active polished state', css.includes('.wd5-filter-bar button.active'));
add('Schedule has illustrated empty state', css.includes('.wd5-schedule-card .wd5-empty span::before'));
add('Lower cards no longer reserve large decorative-art column', css.includes('.wd5-feature-art{display:none!important}'));
add('Subtle staged entrance animation exists', css.includes('@keyframes wdlux-rise'));
add('Reduced motion is respected', css.includes('@media(prefers-reduced-motion:reduce)'));
add('Dark mode is covered', css.includes('html[data-theme="dark"] .wd5-card'));
add('Responsive one-column fallback exists', css.includes('@media(max-width:1080px)'));
add('Readable typography remains at least 13px equivalent', !/font-size:\s*(?:[0-9]|1[0-2])px/.test(css));
const failed=checks.filter(([,v])=>!v);
checks.forEach(([n,v])=>console.log(`${v?'✓':'✗'} ${n}`));
if(failed.length){console.error(`\n❌ Dashboard Luxury Cards audit FAILED (${checks.length-failed.length}/${checks.length})`);process.exit(1)}
console.log(`\n✅ Dashboard Luxury Cards audit PASS (${checks.length}/${checks.length})`);
