import fs from 'node:fs';
const checks=[];const add=(name,pass)=>checks.push({name,pass:Boolean(pass)});const read=(p)=>fs.existsSync(p)?fs.readFileSync(p,'utf8'):'';
const apps=read('src/data/apps.js');const tool=read('src/pages/ToolPage.jsx');const page=read('src/pages/THPTPracticeHub.jsx');const util=read('src/utils/thptPracticeHub.js');const css=read('src/pages/THPTPracticeHub.css');const sql=read('supabase/thpt_practice_hub_v11_6_7.sql');const web=read('src/pages/WebApps.jsx');
add('App card registered',apps.includes("slug: 'thpt-practice-hub'")&&apps.includes("titleVi: 'Luyện thi THPT'"));
add('ToolPage lazy route registered',tool.includes("import('./THPTPracticeHub.jsx')")&&tool.includes("tool?.slug === 'thpt-practice-hub'"));
add('App order includes THPT hub',web.includes("'thpt-practice-hub'"));
add('Page supports teacher and TTCM workflow',page.includes('Gửi bài TTCM duyệt')&&page.includes("review(item, 'approved')")&&page.includes("review(item, 'revision')"));
add('HTML file validation is limited to 20 MB',util.includes('20 * 1024 * 1024')&&util.includes("endsWith('.html')")&&util.includes("endsWith('.htm')"));
add('IndexedDB local store exists',util.includes("indexedDB.open(DB_NAME")&&util.includes("createObjectStore(STORE_NAME"));
add('Cloud table and bucket are supported',util.includes("thpt_html_lessons")&&util.includes("thpt-html-lessons"));
add('Player uses sandboxed iframe',page.includes('<iframe')&&page.includes('sandbox=')&&!page.includes('target="_blank"'));
add('Player supports fullscreen and reload',page.includes('requestFullscreen')&&page.includes('webkitRequestFullscreen')&&page.includes('setPlayerKey'));
add('Responsive CSS exists',css.includes('@media(max-width:720px)')&&css.includes('.thpt-card-grid'));
add('Supabase migration includes RLS',sql.includes('enable row level security')&&sql.includes('thpt_lessons_select')&&sql.includes('storage.buckets'));
const failed=checks.filter(x=>!x.pass);checks.forEach(x=>console.log(`${x.pass?'✓':'✗'} ${x.name}`));if(failed.length){console.error(`\n❌ THPT Practice Hub audit FAILED (${checks.length-failed.length}/${checks.length})`);process.exit(1);}console.log(`\n✅ THPT Practice Hub audit PASS (${checks.length}/${checks.length})`);
