import fs from 'node:fs';
const read=(file)=>fs.readFileSync(file,'utf8');
const exists=(file)=>fs.existsSync(file);
const checks=[];const pass=(name,value)=>checks.push([name,Boolean(value)]);
const pkg=JSON.parse(read('package.json'));
const main=read('src/main.jsx');
const apps=read('src/data/apps.js');
const permissions=read('src/utils/permissions.js');
const transfer=read('src/components/ContentTransferHub.jsx');
const page=read('src/pages/ContentEcosystem.jsx');
const util=read('src/utils/contentEcosystem.js');
const sql=read('supabase/brian_v11_2_final_content_ecosystem.sql');
pass('package version 11.2.0',pkg.version==='11.2.0');
pass('version config 11.2.0',read('src/config/version.js').includes("APP_VERSION = '11.2.0'")&&read('src/config/version.js').includes("RUNTIME_CORE_VERSION = '2.2.0'"));
pass('Content Ecosystem route registered',main.includes("'content-ecosystem'")&&main.includes('<ContentEcosystem'));
pass('Content Ecosystem app card',apps.includes("slug: 'content-ecosystem'")&&apps.includes('Hệ sinh thái nội dung dạy học'));
pass('Content Ecosystem permission',permissions.includes("'content-ecosystem': 'route:content-ecosystem'")&&permissions.includes("ROUTE_PERMISSION_IDS['content-ecosystem']"));
pass('Content Ecosystem page exists',exists('src/pages/ContentEcosystem.jsx')&&page.includes('Thư viện tài sản')&&page.includes('Canvas nội dung'));
pass('asset library support',page.includes('content_ecosystem_assets')&&page.includes('saveAsset'));
pass('structured locked canvas',page.includes('locked')&&page.includes('moveBlock')&&page.includes('serializeCanvas'));
pass('production recipes',util.includes('ECOSYSTEM_RECIPES')&&page.includes('runRecipe'));
pass('multi app targets',util.includes('ECOSYSTEM_TARGETS')&&util.includes("'reading-studio'")&&util.includes("'assessment-core'"));
pass('content kit support',page.includes('createKit')&&page.includes('sendKitToLessonPack'));
pass('global transfer destination',transfer.includes("id: 'content-ecosystem'"));
pass('V11.2 stylesheet loaded',main.includes("./styles/v1120.css")&&exists('src/styles/v1120.css'));
pass('database asset table',sql.includes('create table if not exists public.content_ecosystem_assets'));
pass('database kit and run tables',sql.includes('create table if not exists public.content_ecosystem_kits')&&sql.includes('create table if not exists public.content_ecosystem_runs'));
pass('database RLS',sql.includes('content_ecosystem_assets_owner_all_v1120')&&sql.includes('content_ecosystem_kits_owner_all_v1120'));
pass('Realtime registration',sql.includes('alter publication supabase_realtime add table public.content_ecosystem_assets'));
pass('schema registry 11.2',sql.includes("('content_ecosystem','11.2.0'"));
pass('V11.2 scripts registered',Boolean(pkg.scripts?.['verify:v11.2'])&&Boolean(pkg.scripts?.['release:guard:v11.2']));
pass('no internal npm registry',!read('package-lock.json').includes('applied-caas-gateway'));
const failed=checks.filter(([,ok])=>!ok);checks.forEach(([name,ok])=>console.log(`${ok?'✓':'✗'} ${name}`));
console.log(`V11.2 Final Content Ecosystem Check: ${checks.length-failed.length}/${checks.length} passed`);
if(failed.length)process.exit(1);
