import fs from 'node:fs';
let passed=0,failed=0;
const read=(p)=>fs.readFileSync(p,'utf8');
const pass=(name,ok)=>{if(ok){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const workHub=read('src/pages/WorkHub.jsx');
const archiveUtil=read('src/utils/workHubResourceArchive.js');
const archiveApi=read('api/work-hub-archive-resource.js');
const css=read('src/styles/v1133.css');
const sql=read('supabase/brian_v11_3_5_work_submission_archive.sql');
const status=read('src/components/StatusMenuBar.jsx');
pass('package version 11.3.5',pkg.version==='11.3.5');
pass('version registry 11.3.5',read('src/config/version.js').includes("APP_VERSION = '11.3.5'")&&read('src/config/version.js').includes("RUNTIME_CORE_VERSION = '2.3.5'"));
pass('leader-only archive button',workHub.includes('Lưu vào Kho học liệu')&&workHub.includes('leader && archiveOpen'));
pass('archive metadata form',workHub.includes('Lưu và duyệt học liệu')&&workHub.includes('RESOURCE_CATEGORY_FALLBACK'));
pass('server archive endpoint',archiveApi.includes("roles: ['admin', 'department_head']")&&archiveApi.includes('work-hub-submissions')&&archiveApi.includes('resource_items'));
pass('Google Drive final category upload',archiveApi.includes('resourceCategoryFolderName')&&archiveApi.includes('uploadFile')&&archiveApi.includes("status: 'approved'"));
pass('duplicate protection',archiveApi.includes(".eq('checksum', checksum)")&&archiveApi.includes('reused: Boolean(duplicate)'));
pass('attachment archive linkage',archiveApi.includes('library_resource_id')&&archiveApi.includes('archived_to_library_at'));
pass('local Resource Library sync',archiveUtil.includes('fromCloudRow')&&archiveUtil.includes('updateResourceLibrary'));
pass('archive UI styles',css.includes('V11.3.5')&&css.includes('work-library-archive-form'));
pass('database registry migration',sql.includes("'work_submission_archive','11.3.5'")&&sql.includes('work_hub_comments_resource_archive_v1135'));
pass('bulk assignment remains',workHub.includes('Chọn nhiều người')&&workHub.includes('Cả tổ (')&&workHub.includes('Xoá cả đợt giao'));
pass('notification sound remains',status.includes('playNoticeTone')&&css.includes('V11.3.3 HF1'));
pass('Student Practice option hotfix remains',read('src/styles/v1132.css').includes('V11.3.2 HF1'));
pass('no internal registry',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.3.5 Work Submission Archive Check: ${passed}/${passed+failed} passed`);
if(failed) process.exit(1);
