import fs from 'node:fs';
let passed=0, failed=0;
const read=(p)=>fs.readFileSync(p,'utf8');
const exists=(p)=>fs.existsSync(p);
const pass=(name,ok)=>{if(ok){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const main=read('src/main.jsx');
const webApps=read('src/pages/WebApps.jsx');
const vault=read('src/pages/HiddenAppsVault.jsx');
const visibility=read('src/utils/appVisibility.js');
const registry=read('src/data/appVisibilityRegistry.js');
const nav=read('src/components/GlobalFlatNavigation.jsx');
const palette=read('src/components/GlobalCommandPalette.jsx');
const home=read('src/pages/Home.jsx');
const sql=read('supabase/brian_v11_3_2_app_visibility.sql');
pass('package version 11.3.2',pkg.version==='11.3.2');
pass('version registry 11.3.2',read('src/config/version.js').includes("APP_VERSION = '11.3.2'")&&read('src/config/version.js').includes("RUNTIME_CORE_VERSION = '2.3.2'"));
pass('Hidden Apps Vault page exists',exists('src/pages/HiddenAppsVault.jsx')&&vault.includes('Hidden Apps Vault')&&vault.includes('Thư mục ứng dụng đã ẩn'));
pass('admin-only app vault route',main.includes("currentRoute === 'app-vault'")&&read('src/utils/permissions.js').includes("route === 'admin' || route === 'app-vault'"));
pass('teacher direct-route guard',main.includes('temporarilyHidden')&&main.includes('isAppHiddenForUser')&&main.includes('Ứng dụng đang tạm ẩn'));
pass('app directory hidden folder',webApps.includes('HIDDEN_APPS_FOLDER')&&webApps.includes('hidden-app-folder-card')&&webApps.includes('globallyHiddenIds'));
pass('visibility registry covers tools and route shortcuts',registry.includes('ROUTE_APP_SHORTCUTS')&&registry.includes('visibilityIdForRoute')&&registry.includes('getAppVisibilityCatalog'));
pass('cloud/local visibility service',visibility.includes("from('app_visibility_settings')")&&visibility.includes('setAppHidden')&&visibility.includes('restoreAllHiddenApps'));
pass('Realtime visibility refresh',visibility.includes("table: 'app_visibility_settings'")&&visibility.includes("event: '*'"));
pass('global navigation filters hidden apps',nav.includes('isAppHiddenForUser')&&nav.includes('visibilityIdForRoute')&&nav.includes("route:app-vault"));
pass('command palette filters hidden apps',palette.includes('isAppHiddenForUser')&&palette.includes('visibilityIdForRoute')&&palette.includes('Hidden Apps Vault'));
pass('homepage filters hidden apps',home.includes('canShowId')&&home.includes('featuredWindows')&&home.includes('visibilityId'));
pass('RLS table and admin-only writes',sql.includes('create table if not exists public.app_visibility_settings')&&sql.includes('bes_v1132_is_admin')&&sql.includes('app_visibility_update_v1132'));
pass('teacher and department roles hidden by default',sql.includes("array['department_head','teacher','student']"));
pass('V11.3.2 stylesheet loaded',main.includes("./styles/v1132.css")&&exists('src/styles/v1132.css'));
pass('no internal registry',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.3.2 Admin Hidden Apps Vault Check: ${passed}/${passed+failed} passed`);
if(failed) process.exit(1);
