import fs from 'node:fs';
let passed=0,failed=0;
const read=(f)=>fs.readFileSync(f,'utf8');
const pass=(name,condition)=>{if(condition){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const version=JSON.parse(read('public/version.json'));
const release=JSON.parse(read('public/release-manifest.json'));
const catalog=read('src/data/aiProviderCatalog.js');
const hub=read('src/utils/aiProviderHubRuntime.js');
const routing=read('src/utils/aiSmartRouting.js');
const gemini=read('src/utils/gemini.js');
const workspace=read('src/pages/AIWorkspace.jsx');
const selector=read('src/components/AISmartModelSelector.jsx');
const main=read('src/main.jsx');
const apps=read('src/data/apps.js');
const apiEntries=fs.existsSync('api')?fs.readdirSync('api').filter((name)=>!name.startsWith('_')&&/\.(?:js|mjs|ts|py|go)$/i.test(name)):[];
pass('package version 11.5.7',pkg.version==='11.5.7');
pass('version registry 11.5.7',version.version==='11.5.7'&&release.version==='11.5.7');
pass('runtime core 2.5.7',version.runtimeCore==='2.5.7'&&release.runtime==='2.5.7');
pass('expanded provider catalog', ['cerebras','github-models','cohere','cloudflare','huggingface','nvidia','vercel','sambanova','ollama','lmstudio','localai'].every((id)=>catalog.includes(`id: '${id}'`)));
pass('direct API key actions',catalog.includes('apiKeyUrl')&&hub.includes('data-provider-select')&&hub.includes('target="_blank"'));
pass('full-width Provider Hub runtime',hub.includes('v1157-provider-hub')&&main.includes('BRIAN_V1157_PROVIDER_HUB_RUNTIME'));
pass('eight routing modes', ['smart','free','fast','quality','long-context','vision','local','manual'].every((id)=>routing.includes(`id: '${id}'`)));
pass('smart candidate routing',gemini.includes('buildAiRoutingCandidates')&&gemini.includes('bes-ai-routing-success'));
pass('OpenRouter auth normalization',gemini.includes("replace(/^Bearer\\s+/i, '')")&&gemini.includes('Authorization = `Bearer ${key}`'));
pass('local providers may omit key',gemini.includes('requiresApiKey !== false')&&gemini.includes('if (key) headers.Authorization'));
pass('global provider/model selector',selector.includes('Chế độ AI')&&hub.includes('data-inline-model'));
pass('AI Workspace can use another model',workspace.includes('Dùng mô hình khác')&&workspace.includes('excludeProviders'));
pass('actual provider metadata shown',workspace.includes('actualRoute')&&workspace.includes('fallbackUsed'));
pass('paid providers require opt-in',hub.includes('v1157-allow-paid')&&routing.includes('prefs.allowPaid'));
pass('Listening Lab remains removed',!apps.includes("slug: 'listening-lab'"));
pass('Vercel functions <=12',apiEntries.length<=12);
pass('public npm registry only',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.5.7 Free AI Provider Hub Check: ${passed}/${passed+failed} passed`);
console.log(`Deployable API entries: ${apiEntries.length}`);
if(failed)process.exit(1);
