import fs from 'node:fs';
const read=(file)=>fs.readFileSync(file,'utf8');
const exists=(file)=>fs.existsSync(file);
const checks=[];const pass=(name,value)=>checks.push([name,Boolean(value)]);
const pkg=JSON.parse(read('package.json'));
const main=read('src/main.jsx');
const apps=read('src/data/apps.js');
const permissions=read('src/utils/permissions.js');
const lessonPack=read('src/pages/LessonPack.jsx');
const teacher=read('src/pages/ClassroomDelivery.jsx');
const student=read('src/pages/ClassroomJoin.jsx');
const util=read('src/utils/classroomDelivery.js');
const sql=read('supabase/brian_v11_1_classroom_delivery.sql');
pass('package version 11.1.0',pkg.version==='11.1.0');
pass('version config 11.1.0',read('src/config/version.js').includes("APP_VERSION = '11.1.0'")&&read('src/config/version.js').includes("RUNTIME_CORE_VERSION = '2.1.0'"));
pass('Classroom Delivery route registered',main.includes("'classroom-delivery'")&&main.includes('<ClassroomDelivery'));
pass('public student join route',main.includes("'classroom-join'")&&main.includes('<ClassroomJoin')&&main.includes("PUBLIC_ROUTES")&&main.includes("'classroom-join'"));
pass('public join hides global chrome',main.includes("['homeroom-portal', 'classroom-join']"));
pass('Classroom Delivery app card',apps.includes("slug: 'classroom-delivery'")&&apps.includes('Điều phối lớp học'));
pass('Classroom Delivery permission',permissions.includes("'classroom-delivery': 'route:classroom-delivery'")&&permissions.includes("ROUTE_PERMISSION_IDS['classroom-delivery']"));
pass('teacher classroom page exists',exists('src/pages/ClassroomDelivery.jsx')&&teacher.includes('Phòng chờ')&&teacher.includes('Điều khiển lớp'));
pass('student join page exists',exists('src/pages/ClassroomJoin.jsx')&&student.includes('joinClassroomSession')&&student.includes('submitClassroomResponse'));
pass('join code and QR support',teacher.includes('getQrImageUrl')&&teacher.includes('joinCode'));
pass('team scoring support',teacher.includes('updateTeamScore')&&teacher.includes('+10'));
pass('timer and live navigation',teacher.includes('currentItemDurationSeconds')&&teacher.includes('startItem'));
pass('response collection modes',teacher.includes('multiple-choice')&&teacher.includes('short-answer')&&teacher.includes('check-in'));
pass('student polling and heartbeat',student.includes('setInterval')&&student.includes('pingClassroomParticipant'));
pass('results CSV export',teacher.includes('text/csv')&&teacher.includes('exportResults'));
pass('offline classroom export',util.includes('buildOfflineClassroomHtml')&&teacher.includes('Gói offline'));
pass('Lesson Pack opens Classroom Delivery',lessonPack.includes("#/classroom-delivery?pack="));
pass('V11.1 stylesheet loaded',main.includes("./styles/v1110.css")&&exists('src/styles/v1110.css'));
pass('database session tables',sql.includes('create table if not exists public.classroom_sessions')&&sql.includes('create table if not exists public.classroom_participants'));
pass('database response and teams tables',sql.includes('create table if not exists public.classroom_responses')&&sql.includes('create table if not exists public.classroom_teams'));
pass('anonymous join RPC',sql.includes('classroom_join_session')&&sql.includes('to anon,authenticated'));
pass('public state RPC',sql.includes('classroom_get_public_state')&&sql.includes('participant_token'));
pass('response RPC',sql.includes('classroom_submit_response')&&sql.includes('on conflict(session_id,participant_id,item_id)'));
pass('database RLS',sql.includes('classroom_sessions_host_all_v1110')&&sql.includes('classroom_responses_host_read_v1110'));
pass('Realtime registration',sql.includes('alter publication supabase_realtime add table public.classroom_participants'));
pass('V11.1 scripts registered',Boolean(pkg.scripts?.['verify:v11.1'])&&Boolean(pkg.scripts?.['release:guard:v11.1']));
const failed=checks.filter(([,ok])=>!ok);checks.forEach(([name,ok])=>console.log(`${ok?'✓':'✗'} ${name}`));
console.log(`V11.1 Classroom Delivery Check: ${checks.length-failed.length}/${checks.length} passed`);
if(failed.length)process.exit(1);
