import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const checks = [];
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const exists = (file) => fs.existsSync(path.join(root, file));
const check = (name, condition) => checks.push({ name, pass: Boolean(condition) });

const pkg = JSON.parse(read('package.json'));
const version = JSON.parse(read('public/version.json'));
const main = read('src/main.jsx');
const index = read('index.html');
const apps = read('src/data/apps.js');
const permissions = read('src/utils/permissions.js');
const nav = read('src/components/GlobalFlatNavigation.jsx');
const command = read('src/components/GlobalCommandPalette.jsx');
const page = read('src/pages/PlatformReadiness.jsx');
const pwa = read('src/utils/pwa.js');
const accessibility = read('src/utils/accessibility.js');
const readiness = read('src/utils/platformReadiness.js');
const serviceWorker = read('public/sw.js');
const vercel = JSON.parse(read('vercel.json'));
const runtime = read('src/services/runtime/core.js');

check('package version 10.95.0', pkg.version === '10.95.0');
check('version manifest 10.95.0', version.version === '10.95.0');
check('index version meta 10.95.0', index.includes('content="10.95.0"'));
check('V10.95 stylesheet loaded', main.includes("./styles/v1095.css"));
check('PlatformReadiness page exists', exists('src/pages/PlatformReadiness.jsx'));
check('Platform Readiness lazy route', main.includes("./pages/PlatformReadiness.jsx"));
check('platform route registered', main.includes("'platform-readiness'"));
check('platform app registered', apps.includes("slug: 'platform-readiness'"));
check('platform permission registered', permissions.includes("'platform-readiness': 'route:platform-readiness'"));
check('platform navigation registered', nav.includes("'platform-readiness'"));
check('platform command palette registered', command.includes("route: 'platform-readiness'"));
check('skip navigation installed', main.includes('bes-skip-link') && main.includes('bes-main-content'));
check('accessibility announcer installed', main.includes('GlobalAccessibilityAnnouncer'));
check('PWA update banner installed', main.includes('PwaUpdateBanner'));
check('manifest linked', index.includes('rel="manifest"') && exists('public/manifest.webmanifest'));
check('service worker exists', exists('public/sw.js'));
check('offline page exists', exists('public/offline.html'));
check('PWA icons exist', ['public/pwa/icon-192.png','public/pwa/icon-512.png','public/pwa/maskable-192.png','public/pwa/maskable-512.png'].every(exists));
check('service worker excludes API caching', serviceWorker.includes("url.pathname.startsWith('/api/')"));
check('service worker navigation fallback', serviceWorker.includes('networkFirstNavigation') && serviceWorker.includes('/offline.html'));
check('PWA install prompt supported', pwa.includes('beforeinstallprompt') && pwa.includes('requestPwaInstall'));
check('accessibility preferences persisted', accessibility.includes('bes-accessibility-v1095') && accessibility.includes('saveAccessibilityPreferences'));
check('high contrast control exists', page.includes('preferences.contrast') && read('src/styles/v1095.css').includes('data-a11y-contrast'));
check('reduced motion control exists', page.includes('preferences.motion') && read('src/styles/v1095.css').includes('data-a11y-motion'));
check('security audit exists', readiness.includes('runSecurityAudit') && readiness.includes('service-role'));
check('security report excludes secret values', readiness.includes('suspiciousStorage') && !readiness.includes('window.localStorage.getItem(key) }'));
check('Web Vitals collector exists', exists('src/utils/webVitals.js') && read('src/utils/webVitals.js').includes('largest-contentful-paint'));
check('performance budget script exists', exists('scripts/performance-budget-v10.95.0.mjs'));
check('Vercel security headers configured', Array.isArray(vercel.headers) && JSON.stringify(vercel.headers).includes('X-Content-Type-Options'));
check('CSP is report-only', JSON.stringify(vercel.headers).includes('Content-Security-Policy-Report-Only'));
check('runtime core upgraded', runtime.includes("version: '1.2.0'"));
check('V10.95 module manifest exists', exists('public/bes-modules-v10.95.0.json'));
check('V10.95 flags manifest exists', exists('public/bes-feature-flags-v10.95.0.json'));
check('V10.95 platform runtime exists', exists('public/bes-platform-control-v10950.js'));
check('no SQL migration required', version.requiresSql === false);

const failed = checks.filter((item) => !item.pass);
for (const item of checks) console.log(`${item.pass ? 'PASS' : 'FAIL'}  ${item.name}`);
console.log(`\nV10.95 Platform Readiness checks: ${checks.length - failed.length}/${checks.length} passed.`);
if (failed.length) process.exit(1);
