import fs from 'node:fs';
let passed=0,failed=0;
const read=(f)=>fs.readFileSync(f,'utf8');
const pass=(name,condition)=>{if(condition){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const version=JSON.parse(read('public/version.json'));
const release=JSON.parse(read('public/release-manifest.json'));
const gemini=read('src/utils/gemini.js');
const workspace=read('src/pages/AIWorkspace.jsx');
const fallback=read('src/utils/aiWorkspaceFallback.js');
const css=read('src/styles/v1093.css');
const apps=read('src/data/apps.js');
const apiEntries=fs.readdirSync('api').filter((name)=>!name.startsWith('_')&&/\.(?:js|mjs|ts|py|go)$/i.test(name));
pass('package version 11.5.6',pkg.version==='11.5.6');
pass('version registry 11.5.6',version.version==='11.5.6'&&release.version==='11.5.6');
pass('runtime core 2.5.6',version.runtimeCore==='2.5.6'&&release.runtime==='2.5.6');
pass('adaptive OpenRouter retry handles low affordable token values',gemini.includes('affordable >= 80')&&gemini.includes('affordable - 24'));
pass('structured credit-limit error is preserved',gemini.includes("error.code = 'AI_PROVIDER_CREDIT_LIMIT'")&&gemini.includes('capacityError'));
pass('AI Workspace imports local fallback engine',workspace.includes('buildWorkspaceLocalFallback')&&workspace.includes('friendlyAiWorkspaceError'));
pass('missing API key uses internal fallback',workspace.includes("useLocalFallback('missing-api-key'"));
pass('credit and network errors auto recover',workspace.includes('isProviderCapacityError(runError)')&&workspace.includes('metadata.autoFallback'));
pass('response budgets available',workspace.includes('RESPONSE_BUDGETS')&&workspace.includes('Tiết kiệm')&&workspace.includes('Cân bằng')&&workspace.includes('Chi tiết'));
pass('continuation mode available',workspace.includes('Tạo tiếp phần')&&workspace.includes('continueOutput'));
pass('internal exam starter bank available',fallback.includes('EXAM_BANK')&&fallback.includes('BẢN KHỞI TẠO ĐỀ THI THPT'));
pass('friendly capacity message available',fallback.includes('không đủ credit')&&fallback.includes('isProviderCapacityError'));
pass('resilience interface styles installed',css.includes('.v1156-resilience-bar')&&css.includes('.v1093-alert.warning'));
pass('Listening Lab remains removed',!apps.includes("slug: 'listening-lab'"));
pass('Vercel functions <=12',apiEntries.length<=12);
pass('public npm registry only',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.5.6 AI Workspace Resilience Check: ${passed}/${passed+failed} passed`);
console.log(`Deployable API entries: ${apiEntries.length}`);
if(failed)process.exit(1);
