import fs from 'node:fs';
let passed=0,failed=0;
const read=(p)=>fs.readFileSync(p,'utf8');
const pass=(name,ok)=>{if(ok){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const workHub=read('src/pages/WorkHub.jsx');
const delivery=read('src/utils/workHubDelivery.js');
const css=read('src/styles/v1133.css');
const status=read('src/components/StatusMenuBar.jsx');
const sql=read('supabase/brian_v11_3_4_bulk_assignment_delete.sql');
pass('package version 11.3.4',pkg.version==='11.3.4');
pass('version registry 11.3.4',read('src/config/version.js').includes("APP_VERSION = '11.3.4'")&&read('src/config/version.js').includes("RUNTIME_CORE_VERSION = '2.3.4'"));
pass('bulk assignment modes',workHub.includes("assignment_scope === 'selected'")&&workHub.includes("assignment_scope === 'department'")&&workHub.includes('Chọn nhiều người'));
pass('one work item per teacher',workHub.includes('payloads = targetIds.map')&&workHub.includes('assignment_batch_id')&&workHub.includes('assignment_batch_index'));
pass('whole-department assignment',workHub.includes('departmentTeachers')&&workHub.includes('Cả tổ ('));
pass('individual teacher notification copy',workHub.includes('gửi thông báo đến từng giáo viên'));
pass('safe single and batch delete UI',workHub.includes('deleteWorkItems')&&workHub.includes('Xoá công việc này')&&workHub.includes('Xoá cả đợt giao'));
pass('submission files cleaned before deletion',workHub.includes('removeWorkHubSubmissionFiles')&&delivery.includes('export async function removeWorkHubSubmissionFiles'));
pass('delete SQL policy is leader-only',sql.includes('work_hub_items_delete_v1134')&&sql.includes('bes_v1133_is_leader(auth.uid())')&&sql.includes('grant delete on public.work_hub_items'));
pass('batch metadata index',sql.includes('work_hub_items_assignment_batch_v1134'));
pass('V11.3.3 teacher response remains',workHub.includes('Nộp phản hồi công việc')&&workHub.includes("rpc('bes_v1133_submit_work_response'"));
pass('notification sound remains',status.includes('playNoticeTone')&&css.includes('V11.3.3 HF1'));
pass('animated unread badge remains',css.includes('bes-notice-badge-breathe')&&css.includes('has-new-notice'));
pass('Student Practice option hotfix remains',read('src/styles/v1132.css').includes('V11.3.2 HF1'));
pass('no internal registry',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.3.4 Bulk Work Assignment Check: ${passed}/${passed+failed} passed`);
if(failed) process.exit(1);
