import fs from 'node:fs';
let passed=0,failed=0;
const read=(p)=>fs.readFileSync(p,'utf8');
const exists=(p)=>fs.existsSync(p);
const pass=(name,ok)=>{if(ok){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const main=read('src/main.jsx');
const workHub=read('src/pages/WorkHub.jsx');
const status=read('src/components/StatusMenuBar.jsx');
const delivery=read('src/utils/workHubDelivery.js');
const css=read('src/styles/v1133.css');
const sql=read('supabase/brian_v11_3_3_work_assignment_delivery.sql');
pass('package version 11.3.3',pkg.version==='11.3.3');
pass('version registry 11.3.3',read('src/config/version.js').includes("APP_VERSION = '11.3.3'")&&read('src/config/version.js').includes("RUNTIME_CORE_VERSION = '2.3.3'"));
pass('V11.3.3 stylesheet loaded',main.includes("./styles/v1133.css")&&css.includes('Work Assignment Notification & File Response'));
pass('Work Hub assignment notice copy',workHub.includes('Đã giao công việc và gửi thông báo đến tài khoản giáo viên.'));
pass('Teacher file response form',workHub.includes('Nộp phản hồi công việc')&&workHub.includes('submitTeacherResponse')&&workHub.includes('type="file"'));
pass('Atomic submission RPC used',workHub.includes("rpc('bes_v1133_submit_work_response'")&&sql.includes('bes_v1133_submit_work_response'));
pass('Private submission storage helper',delivery.includes("WORK_HUB_BUCKET = 'work-hub-submissions'")&&delivery.includes('createSignedUrl'));
pass('Global notifications include Work Hub',status.includes('listWorkHubNotifications')&&status.includes("kind: 'work-hub'")&&status.includes('subscribeWorkHubNotifications'));
pass('Work notification opens selected task',status.includes('rememberWorkHubItem')&&workHub.includes('consumeRememberedWorkHubItem'));
pass('SQL creates notification table and triggers',sql.includes('create table if not exists public.work_hub_notifications')&&sql.includes('bes_v1133_work_item_insert')&&sql.includes('bes_v1133_work_item_update'));
pass('SQL private storage policies',sql.includes("'work-hub-submissions'")&&sql.includes('work_hub_files_select_v1133')&&sql.includes('work_hub_files_insert_v1133'));
pass('Submission comment type enabled',sql.includes("'submission'"));
pass('Realtime Work Hub enabled',sql.includes('supabase_realtime')&&delivery.includes('subscribeTable'));
pass('25 MB file limit',delivery.includes('25 * 1024 * 1024')&&sql.includes('26214400'));
pass('HF1 Student Practice remains present',read('src/styles/v1132.css').includes('V11.3.2 HF1'));
pass('no internal registry',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.3.3 Work Assignment Delivery Check: ${passed}/${passed+failed} passed`);
if(failed) process.exit(1);
