import fs from 'node:fs';
import path from 'node:path';
let passed=0,failed=0;
const read=(p)=>fs.readFileSync(p,'utf8');
const exists=(p)=>fs.existsSync(p);
const pass=(name,ok)=>{if(ok){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const wrapper=read('src/pages/EnglishLessonIntegrationStudio.jsx');
const toolPage=read('src/pages/ToolPage.jsx');
const apps=read('src/data/apps.js');
const home=read('src/pages/Home.jsx');
const version=JSON.parse(read('public/version.json'));
const vendorDir='src/vendor/englishLessonIntegration';
const chunks=exists(`${vendorDir}/chunks`)?fs.readdirSync(`${vendorDir}/chunks`).filter(n=>n.endsWith('.js')):[];
const vendorSource=chunks.map(n=>read(path.join(vendorDir,'chunks',n))).join('\n');
const apiEntries=fs.readdirSync('api').filter(n=>!n.startsWith('_')&&/\.(?:js|mjs|ts|py|go)$/i.test(n));
pass('package version 11.4.6',pkg.version==='11.4.6');
pass('version registry 11.4.6',read('src/config/version.js').includes("APP_VERSION = '11.4.6'")&&version.version==='11.4.6');
pass('lesson route retained',toolPage.includes("tool?.slug === 'english-lesson-integration'"));
pass('launcher registration retained',apps.includes("slug: 'english-lesson-integration'"));
pass('home shortcut retained',home.includes("makeAppWindow('english-lesson-integration'"));
pass('stable native entry retained',wrapper.includes("../vendor/englishLessonIntegration/elis.es.js"));
pass('native Brian AI bridge wired',wrapper.includes('getActiveAiConfig')&&wrapper.includes('buildNativeLessonPrompt')&&wrapper.includes('request: nativeAiConfigured'));
pass('AI settings refresh remount wired',wrapper.includes("bes-ai-settings-updated")&&wrapper.includes('aiSettingsRevision'));
pass('host provider inheritance wired',wrapper.includes('providerLabel: providerInfo.label')&&wrapper.includes('baseUrl: activeAI.baseUrl'));
pass('module native host request bundled',vendorSource.includes('native-host')&&vendorSource.includes('AI thật đang bật'));
pass('large AI action cards bundled',vendorSource.includes('min-height:154px')&&vendorSource.includes('grid-template-columns:repeat(2'));
pass('large proposal cards bundled',vendorSource.includes('min-height:104px')&&vendorSource.includes('font-size:15px'));
pass('review drawer bundled',vendorSource.includes('review-pane is-open')||vendorSource.includes('review-pane ${'));
pass('real AI status UI bundled',vendorSource.includes('AI Gateway của Brian')&&vendorSource.includes('Chạy AI với'));
pass('server endpoint fallback retained',read('api/ai.js').includes('lesson-assistant')&&read('server/lessonAiHandler.js').includes('lesson-assistant'));
pass('no extra lesson function',!exists('api/lesson-ai.mjs'));
pass('Vercel functions <=12',apiEntries.length<=12);
pass('Animated Home retained',home.includes('home-v1137')&&home.includes('home-motion-scene'));
pass('public npm registry only',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.4.6 Native AI + Large Cards Check: ${passed}/${passed+failed} passed`);
console.log(`Deployable API entries: ${apiEntries.length}`);
if(failed)process.exit(1);
