import fs from 'node:fs';
let passed=0,failed=0;
const read=(p)=>fs.readFileSync(p,'utf8');
const exists=(p)=>fs.existsSync(p);
const pass=(name,ok)=>{if(ok){console.log(`✓ ${name}`);passed+=1;}else{console.error(`✗ ${name}`);failed+=1;}};
const pkg=JSON.parse(read('package.json'));
const toolPage=read('src/pages/ToolPage.jsx');
const apps=read('src/data/apps.js');
const home=read('src/pages/Home.jsx');
const wrapper=read('src/pages/EnglishLessonIntegrationStudio.jsx');
const ai=read('api/ai.js');
const version=JSON.parse(read('public/version.json'));
const publicApiEntries=fs.readdirSync('api').filter(name=>!name.startsWith('_')&&/\.(?:js|mjs|ts|py|go)$/i.test(name));
pass('package version 11.4.3',pkg.version==='11.4.3');
pass('version registry 11.4.3',read('src/config/version.js').includes("APP_VERSION = '11.4.3'")&&version.version==='11.4.3');
pass('route registered in ToolPage',toolPage.includes("tool?.slug === 'english-lesson-integration'")&&toolPage.includes('EnglishLessonIntegrationStudio'));
pass('app registered in launcher',apps.includes("slug: 'english-lesson-integration'"));
pass('homepage shortcut retained',home.includes("makeAppWindow('english-lesson-integration'"));
pass('native wrapper uses consolidated endpoint',wrapper.includes("endpoint: '/api/ai'")&&!wrapper.includes("endpoint: '/api/lesson-ai'"));
pass('lesson AI dispatcher is inside api/ai',ai.includes('handleLessonAiRequest')&&ai.includes("['rewrite', 'generate-resource', 'health']"));
pass('lesson handler moved outside api directory',exists('server/lessonAiHandler.js')&&read('server/lessonAiHandler.js').includes('handleLessonAiRequest'));
pass('old extra function removed',!exists('api/lesson-ai.mjs'));
pass('Hobby function count is 12 or fewer',publicApiEntries.length<=12);
pass('compiled module endpoint consolidated',!read('public/bes-elis-v1142/chunks/mount-CCtnxx76.js').includes('/api/lesson-ai'));
pass('SQL migration retained',exists('supabase/brian_v11_4_2_lesson_integration.sql'));
pass('Animated Home V11.3.7 retained',home.includes('home-v1137')&&home.includes('home-motion-scene'));
pass('public npm registry only',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.4.3 Hobby Deploy Check: ${passed}/${passed+failed} passed`);
console.log(`Deployable API entries: ${publicApiEntries.length}`);
if(failed) process.exit(1);
