import fs from 'node:fs';
let passed=0,failed=0;
const read=(f)=>fs.readFileSync(f,'utf8');
const pass=(name,condition)=>{if(condition){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const version=JSON.parse(read('public/version.json'));
const release=JSON.parse(read('public/release-manifest.json'));
const apps=read('src/data/apps.js');
const home=read('src/pages/Home.jsx');
const homeCss=read('src/styles/v1137.css');
const profiles=read('src/data/designProfiles.js');
const pronunciation=read('src/pages/PronunciationCoach.jsx');
const workspace=read('src/utils/workspace.js');
const main=read('src/main.jsx');
const apiEntries=fs.readdirSync('api').filter((name)=>!name.startsWith('_')&&/\.(?:js|mjs|ts|py|go)$/i.test(name));
pass('package version 11.5.5',pkg.version==='11.5.5');
pass('version registry 11.5.5',version.version==='11.5.5'&&release.version==='11.5.5');
pass('runtime core 2.5.5',version.runtimeCore==='2.5.5'&&release.runtime==='2.5.5');
pass('Listening Lab flag disabled',version.listeningLab===false&&release.listeningLab===false);
pass('removed app registry marker',Array.isArray(version.removedApps)&&version.removedApps.includes('listening-lab'));
pass('Listening Lab removed from APPS',!apps.includes("slug: 'listening-lab'"));
pass('Listening Lab removed from Home runtime',!home.includes("makeAppWindow('listening-lab'")&&!home.includes("'listening-lab': 'listening'")&&!home.includes('windows.listening'));
pass('Listening Lab Home CSS removed',!homeCss.includes('.flat-window-listening'));
pass('Listening Lab design profile removed',!profiles.includes("'listening-lab':"));
pass('Listening Lab removed from Pronunciation destinations',!pronunciation.includes("id: 'listening-lab'"));
pass('stale Listening Lab tabs pruned',workspace.includes("RETIRED_TAB_IDS = new Set(['tool:listening-lab'])")&&workspace.includes('RETIRED_TAB_IDS.has(tab.id)'));
pass('current version imported through config',main.includes("from './config/version.js'"));
pass('Vercel functions <=12',apiEntries.length<=12);
pass('public npm registry only',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.5.5 Listening Lab Removal Check: ${passed}/${passed+failed} passed`);
console.log(`Deployable API entries: ${apiEntries.length}`);
if(failed)process.exit(1);
