import fs from 'node:fs';
import path from 'node:path';
let passed=0,failed=0;
const read=(p)=>fs.readFileSync(p,'utf8');
const exists=(p)=>fs.existsSync(p);
const pass=(name,ok)=>{if(ok){console.log(`✓ ${name}`);passed+=1;}else{console.error(`✗ ${name}`);failed+=1;}};
const pkg=JSON.parse(read('package.json'));
const toolPage=read('src/pages/ToolPage.jsx');
const apps=read('src/data/apps.js');
const home=read('src/pages/Home.jsx');
const wrapper=read('src/pages/EnglishLessonIntegrationStudio.jsx');
const ai=read('api/ai.js');
const handler=read('server/lessonAiHandler.js');
const hostCss=read('src/index.css');
const version=JSON.parse(read('public/version.json'));
const vendorDir='src/vendor/englishLessonIntegration';
const vendorEntry=`${vendorDir}/elis.es.js`;
const chunkDir=`${vendorDir}/chunks`;
const chunks=exists(chunkDir)?fs.readdirSync(chunkDir).filter(name=>name.endsWith('.js')):[];
const vendorSource=chunks.map(name=>read(path.join(chunkDir,name))).join('\n');
const publicApiEntries=fs.readdirSync('api').filter(name=>!name.startsWith('_')&&/\.(?:js|mjs|ts|py|go)$/i.test(name));
pass('package version 11.4.5',pkg.version==='11.4.5');
pass('version registry 11.4.5',read('src/config/version.js').includes("APP_VERSION = '11.4.5'")&&version.version==='11.4.5');
pass('route registered in ToolPage',toolPage.includes("tool?.slug === 'english-lesson-integration'")&&toolPage.includes('EnglishLessonIntegrationStudio'));
pass('app registered in launcher',apps.includes("slug: 'english-lesson-integration'"));
pass('homepage shortcut retained',home.includes("makeAppWindow('english-lesson-integration'"));
pass('wrapper imports stable native entry',wrapper.includes("../vendor/englishLessonIntegration/elis.es.js")&&wrapper.includes('mountEnglishLessonIntegrationStudio'));
pass('stable vendor entry exists',exists(vendorEntry)&&read(vendorEntry).includes('mountEnglishLessonIntegrationStudio'));
pass('native vendor chunks exist',chunks.length===4&&chunks.some(name=>name.startsWith('mount-'))&&chunks.some(name=>name.startsWith('index-'))&&chunks.some(name=>name.startsWith('pdf-'))&&chunks.some(name=>name.startsWith('exportDocx-')));
pass('larger workspace UI bundled',vendorSource.includes('workspace-large-display')&&vendorSource.includes('workspace-view-controls')&&vendorSource.includes('AI Copilot cho giáo án'));
pass('default integrated-only view bundled',vendorSource.includes('useState(!1)')||vendorSource.includes('Bản tích hợp'));
pass('AI Copilot client task bundled',vendorSource.includes('lesson-assistant')&&vendorSource.includes('Phân tích toàn bộ'));
pass('Brian visual sync host CSS',hostCss.includes('V11.4.5 — ELIS presentation sync')&&hostCss.includes('max-width:none'));
pass('lesson AI dispatcher includes Copilot task',ai.includes("'lesson-assistant'")&&handler.includes("'lesson-assistant'")&&handler.includes('assistantPrompt'));
pass('native wrapper uses consolidated endpoint',wrapper.includes("endpoint: '/api/ai'"));
pass('old extra function remains removed',!exists('api/lesson-ai.mjs'));
pass('Hobby function count is 12 or fewer',publicApiEntries.length<=12);
pass('SQL migration retained',exists('supabase/brian_v11_4_2_lesson_integration.sql'));
pass('Animated Home V11.3.7 retained',home.includes('home-v1137')&&home.includes('home-motion-scene'));
pass('public npm registry only',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.4.5 UX + AI Check: ${passed}/${passed+failed} passed`);
console.log(`Deployable API entries: ${publicApiEntries.length}`);
if(failed) process.exit(1);
