import fs from 'node:fs';
let passed=0,failed=0;
const read=(file)=>fs.readFileSync(file,'utf8');
const exists=(file)=>fs.existsSync(file);
const pass=(name,condition)=>{if(condition){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const version=JSON.parse(read('public/version.json'));
const release=JSON.parse(read('public/release-manifest.json'));
const source=read('src/pages/WritingStudio.jsx');
const css=read('src/pages/WritingStudio.css');
const toolPage=read('src/pages/ToolPage.jsx');
const apps=read('src/data/apps.js');
const apiEntries=fs.readdirSync('api').filter((name)=>!name.startsWith('_')&&/\.(?:js|mjs|ts|py|go)$/i.test(name));
pass('package version 11.5.2',pkg.version==='11.5.2');
pass('version registry 11.5.2',version.version==='11.5.2'&&release.version==='11.5.2');
pass('runtime core 2.5.2',version.runtimeCore==='2.5.2'&&release.runtime==='2.5.2');
pass('Writing Studio source exists',exists('src/pages/WritingStudio.jsx')&&exists('src/pages/WritingStudio.css'));
pass('native Writing Studio route',toolPage.includes("import('./WritingStudio.jsx')")&&toolPage.includes("tool?.slug === 'writing-studio'"));
pass('Writing Studio app registry retained',apps.includes("slug: 'writing-studio'")&&apps.includes('Process Workbench V2'));
pass('seven workflow steps',source.includes('const WORKFLOW_STEPS')&&(source.match(/\['0[1-7]'/g)||[]).length>=7);
pass('nine functional cards',source.includes('ws-card-mode')&&source.includes('ws-card-task')&&source.includes('ws-card-learner')&&source.includes('ws-card-source')&&source.includes('ws-card-rubric')&&source.includes('ws-card-planning')&&source.includes('ws-card-ai')&&source.includes('ws-card-editor')&&source.includes('ws-card-publish'));
pass('six writing modes',['guided','process','exam','model','feedback','diagnostic'].every((id)=>source.includes(`{ id: '${id}', icon:`)));
pass('genre task builder',source.includes('const GENRES')&&source.includes('WRITING TASK & GENRE'));
pass('rubric editor',source.includes('DEFAULT_RUBRIC')&&source.includes('SUCCESS CRITERIA & RUBRIC'));
pass('Planning Studio tabs',source.includes('PLANNING_TABS')&&source.includes('Idea Bank')&&source.includes('Language Toolkit'));
pass('Draft Editor and review',source.includes('DRAFT EDITOR & QUALITY REVIEW')&&source.includes('localAudit(project)'));
pass('version history',source.includes('saveVersion')&&source.includes('restoreVersion'));
pass('Teacher Vault',source.includes('saveToVault')&&source.includes('TEACHER VAULT · WRITING PORTFOLIO'));
pass('real AI gateway',source.includes('callAI({')&&source.includes('getActiveAiConfig'));
pass('AI coach tasks',source.includes('analyse-prompt')&&source.includes('feedback')&&source.includes('differentiate')&&source.includes('rewrite'));
pass('AI ownership safeguard',source.includes('Preserve student ownership')&&source.includes('Never claim to detect AI authorship'));
pass('document import',source.includes('readDocxTextFromBuffer')&&source.includes('readPdfTextFromBuffer'));
pass('Transfer Inbox',source.includes('listTransfers')&&source.includes('TRANSFER_APPLY_EVENT'));
pass('connected workflow',source.includes('const DESTINATIONS')&&source.includes("schema: 'bes-writing-pack/1.0'"));
pass('DOC and HTML exports',source.includes('exportAsWord')&&source.includes('exportAsHtml'));
pass('Modern SaaS product bar',css.includes('.ws-product-bar')&&css.includes('.ws-context-strip')&&css.includes('.ws-workflow'));
pass('two-card setup grid',css.includes('.ws-setup-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))'));
pass('responsive layouts',css.includes('@media(max-width:1180px)')&&css.includes('@media(max-width:780px)'));
pass('Vercel functions <=12',apiEntries.length<=12);
pass('no obsolete lesson AI function',!exists('api/lesson-ai.mjs'));
pass('public npm registry only',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.5.2 Writing Studio Check: ${passed}/${passed+failed} passed`);
console.log(`Deployable API entries: ${apiEntries.length}`);
if(failed)process.exit(1);
