import fs from 'node:fs';
let passed=0,failed=0;const read=(file)=>fs.readFileSync(file,'utf8');const exists=(file)=>fs.existsSync(file);const pass=(name,condition)=>{if(condition){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));const version=JSON.parse(read('public/version.json'));const release=JSON.parse(read('public/release-manifest.json'));const source=read('src/pages/PronunciationCoach.jsx');const css=read('src/pages/PronunciationCoach.css');const tool=read('src/pages/ToolPage.jsx');const apps=read('src/data/apps.js');const apiEntries=fs.readdirSync('api').filter((name)=>!name.startsWith('_')&&/\.(?:js|mjs|ts|py|go)$/i.test(name));
pass('package version 11.5.3',pkg.version==='11.5.3');pass('version registry 11.5.3',version.version==='11.5.3'&&release.version==='11.5.3');pass('runtime core 2.5.3',version.runtimeCore==='2.5.3'&&release.runtime==='2.5.3');
pass('Pronunciation Coach source exists',exists('src/pages/PronunciationCoach.jsx')&&exists('src/pages/PronunciationCoach.css'));
pass('native Pronunciation route',tool.includes("import('./PronunciationCoach.jsx')")&&tool.includes("tool?.slug === 'pronunciation-coach'"));
pass('app registry status updated',apps.includes("slug: 'pronunciation-coach'")&&apps.includes('Speech Workbench V2 · AI'));
pass('seven workflow steps',source.includes('const WORKFLOW')&&(source.match(/\['0[1-7]'/g)||[]).length>=7);
pass('nine functional cards',['pc-card-mode','pc-card-focus','pc-card-learner','pc-card-source','pc-card-blueprint','pc-card-ai','pc-card-model','pc-card-review','pc-card-publish'].every((marker)=>source.includes(marker)));
pass('six practice modes',['sound','word','rhythm','connected','intonation','diagnostic'].every((id)=>source.includes(`{ id: '${id}',`)));
pass('pronunciation focus groups',source.includes('const FOCUS_GROUPS')&&source.includes('Connected speech')&&source.includes('Intonation'));
pass('Practice Blueprint',source.includes('PRACTICE BLUEPRINT')&&source.includes('ACTIVITY_TYPES'));
pass('browser model player',source.includes('SpeechSynthesisUtterance')&&source.includes('speechSynthesis'));
pass('browser recorder',source.includes('MediaRecorder')&&source.includes('getUserMedia'));
pass('waveform visualisation',source.includes('createAnalyser')&&source.includes('canvasRef'));
pass('speech recognition',source.includes('SpeechRecognition')&&source.includes('webkitSpeechRecognition'));
pass('intelligibility check',source.includes('similarity(project.targetText')&&source.includes('Level 2 · Speech-to-text comparison'));
pass('evidence-aware safeguard',source.includes('not exact phoneme accuracy')&&source.includes('Never invent acoustic measurements'));
pass('real AI gateway',source.includes('callAI({')&&source.includes('getActiveAiConfig'));
pass('AI speech tasks',source.includes("id: 'analyse'")&&source.includes("id: 'remediation'")&&source.includes("id: 'final-sounds'"));
pass('document import',source.includes('readDocxTextFromBuffer')&&source.includes('readPdfTextFromBuffer'));
pass('Transfer Inbox',source.includes('listTransfers')&&source.includes('TRANSFER_APPLY_EVENT'));
pass('connected workflow',source.includes('const DESTINATIONS')&&source.includes("schema: 'bes-pronunciation-pack/1.0'"));
pass('Teacher Vault and versions',source.includes('saveToVault')&&source.includes('saveVersion')&&source.includes('restoreVersion'));
pass('assignment workflow',source.includes('createAssignment')&&source.includes('ASSIGN, PORTFOLIO & CONNECTED WORKFLOW'));
pass('DOC and HTML exports',source.includes('exportAsWord')&&source.includes('exportAsHtml'));
pass('Modern SaaS product UI',css.includes('.pc-product-bar')&&css.includes('.pc-summary')&&css.includes('.pc-workflow'));
pass('two-card setup grid',css.includes('.pc-setup-grid{max-width:1500px;margin:0 auto;display:grid;grid-template-columns:repeat(2,minmax(0,1fr))'));
pass('responsive layouts',css.includes('@media(max-width:1200px)')&&css.includes('@media(max-width:640px)'));
pass('Vercel functions <=12',apiEntries.length<=12);pass('no obsolete lesson AI function',!exists('api/lesson-ai.mjs'));pass('public npm registry only',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.5.3 Pronunciation Coach Check: ${passed}/${passed+failed} passed`);console.log(`Deployable API entries: ${apiEntries.length}`);if(failed)process.exit(1);
