import fs from 'node:fs';
let passed=0, failed=0;
const read=(p)=>fs.readFileSync(p,'utf8');
const exists=(p)=>fs.existsSync(p);
const pass=(name,ok)=>{if(ok){console.log(`✓ ${name}`);passed++;}else{console.error(`✗ ${name}`);failed++;}};
const pkg=JSON.parse(read('package.json'));
const lesson=read('src/pages/LessonArchitect.jsx');
const builder=read('src/components/LessonArchitectCurriculumBuilder.jsx');
const util=read('src/utils/lessonArchitectCurriculum.js');
const main=read('src/main.jsx');
pass('package version 11.3.1',pkg.version==='11.3.1');
pass('version registry 11.3.1',read('src/config/version.js').includes("APP_VERSION = '11.3.1'")&&read('src/config/version.js').includes("RUNTIME_CORE_VERSION = '2.3.1'"));
pass('annual curriculum workflow remains default',lesson.includes("useState('curriculum-batch')")&&lesson.includes('LessonArchitectCurriculumBuilder'));
pass('Global Success English preset',util.includes("subject: 'English'")&&util.includes("bookSeries: 'Global Success'")&&builder.includes('Mẫu Tiếng Anh 11 – Global Success'));
pass('English-only generation contract',util.includes('NON-NEGOTIABLE LANGUAGE RULE')&&util.includes('The entire exported lesson plan must be written in English'));
pass('English output validation and correction',util.includes('validateEnglishLessonOutput')&&builder.includes('buildEnglishCorrectionPrompt'));
pass('Circular 02/2025 digital framework',util.includes('Circular No. 02/2025/TT-BGDĐT')&&util.includes('24')===false&&util.includes('6.3'));
pass('six digital competence domains',util.includes('Data and information literacy')&&util.includes('Communication and collaboration in digital environments')&&util.includes('Digital content creation')&&util.includes('Artificial intelligence application'));
pass('digital competence evidence in activities',util.includes('Digital Competence Evidence')&&util.includes('[DC 1.2]'));
pass('Global Success lesson types',util.includes('Getting Started')&&util.includes('Communication and Culture/CLIL')&&util.includes('Looking Back and Project'));
pass('English Word export',util.includes('ANNUAL LESSON PLANS FOR GRADE')&&util.includes('ANNUAL TEACHING SEQUENCE'));
pass('A4 Times New Roman output',util.includes('margin: 2cm 1.5cm 2cm 2cm')&&util.includes('Times New Roman')&&util.includes('font-size: 13pt'));
pass('new stylesheet loaded',main.includes("./styles/v1131.css")&&exists('src/styles/v1131.css'));
pass('no internal registry',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.3.1 English Global Success Lesson Architect Check: ${passed}/${passed+failed} passed`);
if(failed) process.exit(1);
