import fs from 'node:fs';
const checks=[]; const pass=(name,ok)=>checks.push([name,Boolean(ok)]); const read=(f)=>fs.readFileSync(f,'utf8');
const pkg=JSON.parse(read('package.json')); const main=read('src/main.jsx');
const collaboration=read('src/pages/CollaborationHub.jsx'); const governance=read('src/pages/DataGovernance.jsx');
const util=read('src/utils/collaborationGovernance.js'); const sql=read('supabase/brian_v10_98_collaboration_governance.sql');
pass('package version 10.98.0',pkg.version==='10.98.0');
pass('verify script exists',Boolean(pkg.scripts['verify:v10.98']));
pass('main imports v1098 css',main.includes("./styles/v1098.css"));
pass('main lazy loads collaboration hub',main.includes("./pages/CollaborationHub.jsx"));
pass('main lazy loads data governance',main.includes("./pages/DataGovernance.jsx"));
pass('collaboration route registered',main.includes("'collaboration-hub'"));
pass('governance route registered',main.includes("'data-governance'"));
pass('collaboration has Realtime presence',collaboration.includes('subscribeSpacePresence'));
pass('collaboration has threaded comments',collaboration.includes('addThreadComment'));
pass('collaboration has content versions',collaboration.includes('createContentVersion'));
pass('governance has audit log',governance.includes('Audit log'));
pass('governance has backup restore',governance.includes('Backup & Restore'));
pass('governance has trash recovery',governance.includes('restoreDeletedEntity'));
pass('governance has permission overrides',governance.includes('savePermissionOverride'));
pass('utility supports snapshots',util.includes('createBackupSnapshot'));
pass('utility supports selective restore',util.includes('restoreBackupSnapshot'));
pass('utility supports soft delete',util.includes('softDeleteEntity'));
pass('utility supports audit events',util.includes('recordAuditEvent'));
pass('migration creates spaces',sql.includes('create table if not exists public.collaboration_spaces'));
pass('migration creates members',sql.includes('create table if not exists public.collaboration_members'));
pass('migration creates comments',sql.includes('create table if not exists public.collaboration_comments'));
pass('migration creates versions',sql.includes('create table if not exists public.content_versions'));
pass('migration creates audit events',sql.includes('create table if not exists public.audit_events'));
pass('migration creates snapshots',sql.includes('create table if not exists public.backup_snapshots'));
pass('migration creates deleted items',sql.includes('create table if not exists public.deleted_items'));
pass('migration creates RLS helper',sql.includes('bes_v1098_is_space_member'));
pass('resource library uses soft delete',read('src/pages/ResourceLibrary.jsx').includes('softDeleteEntity'));
pass('work hub emits audit events',read('src/pages/WorkHub.jsx').includes('recordAuditEvent'));
pass('runtime core 1.5.0',read('src/services/runtime/core.js').includes("version: '1.5.0'"));
pass('permissions include collaboration',read('src/utils/permissions.js').includes("'collaboration-hub': 'route:collaboration-hub'"));
pass('permissions include governance',read('src/utils/permissions.js').includes("'data-governance': 'route:data-governance'"));
pass('app cards added',read('src/data/apps.js').includes("slug: 'collaboration-hub'")&&read('src/data/apps.js').includes("slug: 'data-governance'"));
const failed=checks.filter(([,ok])=>!ok); checks.forEach(([name,ok])=>console.log(`${ok?'✓':'✗'} ${name}`));
console.log(`V10.98 Collaboration & Governance Check: ${checks.length-failed.length}/${checks.length} passed`);
if(failed.length)process.exit(1);
