import fs from 'node:fs';
let passed=0,failed=0;
const read=(p)=>fs.readFileSync(p,'utf8');
const exists=(p)=>fs.existsSync(p);
const pass=(name,ok)=>{if(ok){console.log(`✓ ${name}`);passed+=1;}else{console.error(`✗ ${name}`);failed+=1;}};
const pkg=JSON.parse(read('package.json'));
const toolPage=read('src/pages/ToolPage.jsx');
const apps=read('src/data/apps.js');
const profiles=read('src/data/designProfiles.js');
const home=read('src/pages/Home.jsx');
const wrapper=read('src/pages/EnglishLessonIntegrationStudio.jsx');
const version=JSON.parse(read('public/version.json'));
pass('package version 11.4.2',pkg.version==='11.4.2');
pass('version registry 11.4.2',read('src/config/version.js').includes("APP_VERSION = '11.4.2'")&&version.version==='11.4.2');
pass('route registered in ToolPage',toolPage.includes("tool?.slug === 'english-lesson-integration'")&&toolPage.includes('EnglishLessonIntegrationStudio'));
pass('app registered in launcher',apps.includes("slug: 'english-lesson-integration'")&&apps.includes('Tích hợp AI vào giáo án Tiếng Anh'));
pass('design profile registered',profiles.includes("'english-lesson-integration'")&&profiles.includes('Không gian tích hợp giáo án AI'));
pass('homepage pinned shortcut visible',home.includes("makeAppWindow('english-lesson-integration'"));
pass('native Brian wrapper present',exists('src/pages/EnglishLessonIntegrationStudio.jsx')&&wrapper.includes('mountEnglishLessonIntegrationStudio'));
pass('Shadow DOM isolation enabled',wrapper.includes('useShadowDom: true'));
pass('host managed auth/settings',wrapper.includes('managedAuth: true')&&wrapper.includes('managedSettings: true'));
pass('per-user identity supplied to embedded module',wrapper.includes('id: userId')&&wrapper.includes('managedAuth: true'));
pass('native connected transfer adapter',exists('src/components/LessonIntegrationBridgeAdapter.jsx')&&read('src/components/LessonIntegrationBridgeAdapter.jsx').includes('createTransfer(currentUser')&&exists('public/bes-elis-v1142/bridge-runtime.js'));
pass('Supabase singleton reused',wrapper.includes('getSupabasePublicConfig')&&wrapper.includes('supabase.auth.getSession'));
pass('secure lesson AI endpoint present',exists('api/lesson-ai.mjs')&&read('api/lesson-ai.mjs').includes("['rewrite', 'generate-resource', 'health']"));
pass('SQL migration present',exists('supabase/brian_v11_4_2_lesson_integration.sql')&&read('supabase/brian_v11_4_2_lesson_integration.sql').includes('bes_lesson_integration_projects'));
pass('release requires migration',version.requiresSql===true&&version.requiredMigration==='supabase/brian_v11_4_2_lesson_integration.sql');
pass('DOCX/PDF module chunks present',exists('public/bes-elis-v1142/chunks/exportDocx-D0oUwC7A.js')&&exists('public/bes-elis-v1142/chunks/pdf-DyTSsyHP.js'));
pass('compiled integration module present',exists('public/bes-elis-v1142/elis.es.js')&&exists('public/bes-elis-v1142/chunks/mount-CCtnxx76.js'));
pass('Animated Home V11.3.7 retained',home.includes('home-v1137')&&home.includes('home-motion-scene')&&home.includes('handleScenePointerMove'));
for(const slug of ['listening-lab','grammar-builder','writing-studio','pronunciation-coach']) pass(`V11.3.7 app retained: ${slug}`,apps.includes(`slug: '${slug}'`));
pass('no additional module service worker',!exists('public/bes-elis-v1142/sw.js'));
pass('public npm registry only',!read('package-lock.json').includes('applied-caas-gateway'));
console.log(`\nV11.4.2 Native Integration Check: ${passed}/${passed+failed} passed`);
if(failed) process.exit(1);
