import fs from 'node:fs';
const read=(f)=>fs.readFileSync(f,'utf8');
const exists=(f)=>fs.existsSync(f);
const checks=[];const pass=(name,value)=>checks.push([name,Boolean(value)]);
const pkg=JSON.parse(read('package.json'));
const main=read('src/main.jsx');
const apps=read('src/data/apps.js');
const permissions=read('src/utils/permissions.js');
const transfer=read('src/components/ContentTransferHub.jsx');
const page=read('src/pages/LessonPack.jsx');
const util=read('src/utils/lessonPack.js');
const sql=read('supabase/brian_v11_0_connected_teaching_suite.sql');
pass('package version 11.0.0',pkg.version==='11.0.0');
pass('version config 11.0.0',read('src/config/version.js').includes("APP_VERSION = '11.0.0'")&&read('src/config/version.js').includes("RUNTIME_CORE_VERSION = '2.0.0'"));
pass('Lesson Pack route registered',main.includes("'lesson-pack'")&&main.includes('<LessonPack'));
pass('Lesson Pack app card',apps.includes("slug: 'lesson-pack'")&&apps.includes('Gói bài dạy liên thông'));
pass('Lesson Pack permission',permissions.includes("'lesson-pack': 'route:lesson-pack'")&&permissions.includes("ROUTE_PERMISSION_IDS['lesson-pack']"));
pass('cross-app transfer target',transfer.includes("id: 'lesson-pack'")&&transfer.includes("route: '#/lesson-pack'"));
pass('Lesson Pack utility exists',exists('src/utils/lessonPack.js')&&util.includes('saveLessonPack')&&util.includes('itemFromTransfer'));
pass('Lesson Pack builder exists',page.includes('Activity sequence')&&page.includes('Dạy trực tiếp'));
pass('drag reorder exists',page.includes('draggable')&&page.includes('reorder(dragId'));
pass('live teaching timer exists',page.includes('setInterval')&&page.includes('Live teaching'));
pass('support/standard/advanced variants',page.includes('value=\"support\"')&&page.includes('value=\"standard\"')&&page.includes('value=\"advanced\"'));
pass('HTML and JSON export',page.includes("'text/html'")&&page.includes('JSON.stringify(pack'));
pass('connections to core apps',page.includes('Worksheet Factory')&&page.includes('Reading Studio')&&page.includes('Speaking Studio')&&page.includes('Assessment Core')&&page.includes('Learner Sprint'));
pass('V11 stylesheet loaded',main.includes("./styles/v1100.css")&&exists('src/styles/v1100.css'));
pass('database tables',sql.includes('create table if not exists public.lesson_packs')&&sql.includes('create table if not exists public.lesson_pack_items'));
pass('database RLS',sql.includes('lesson_packs_read_v1100')&&sql.includes('lesson_pack_items_read_v1100'));
pass('realtime registration',sql.includes('alter publication supabase_realtime add table public.lesson_packs'));
pass('V11 scripts registered',Boolean(pkg.scripts?.['verify:v11.0'])&&Boolean(pkg.scripts?.['release:guard:v11.0']));
const failed=checks.filter(([,ok])=>!ok);checks.forEach(([name,ok])=>console.log(`${ok?'✓':'✗'} ${name}`));
console.log(`V11.0 Connected Teaching Suite Check: ${checks.length-failed.length}/${checks.length} passed`);
if(failed.length)process.exit(1);
