from pathlib import Path

path = Path('src/components/GlobalAttendanceNavigationTab.jsx')
text = path.read_text(encoding='utf-8')

replacements = [
    (
        "import './GlobalAttendanceManualTeacher.css';\n",
        "import './GlobalAttendanceManualTeacher.css';\nimport AttendanceMonthlyReport from './attendance/AttendanceMonthlyReport.jsx';\nimport './attendance/AttendanceMaterial3.css';\n",
    ),
    (
        "const SESSION_COLUMNS = 'id,class_id,class_type,class_name,subject,teacher_id,teacher_name,teacher_email,attendance_date,checked_at,checked_by,total_students,present_count,absent_count,note,created_at';",
        "const SESSION_COLUMNS = 'id,class_id,class_type,class_name,subject,teacher_id,teacher_name,teacher_email,attendance_date,checked_at,checked_by,total_students,present_count,absent_count,note,session_status,lesson_periods,cancellation_reason,created_at';",
    ),
    (
        "  const [newTeacherName, setNewTeacherName] = useState('');\n  const fileRef = useRef(null);",
        "  const [newTeacherName, setNewTeacherName] = useState('');\n  const [lessonPeriods, setLessonPeriods] = useState(1);\n  const [showCancelSession, setShowCancelSession] = useState(false);\n  const [cancellationReason, setCancellationReason] = useState('');\n  const [reportMonth, setReportMonth] = useState(today.slice(0, 7));\n  const fileRef = useRef(null);",
    ),
    (
        "  function teacherForSession(session) {\n    return session?.teacher_name || 'Chưa ghi giáo viên';\n  }",
        "  function teacherForSession(session) {\n    if (session?.session_status === 'cancelled') return '—';\n    return session?.teacher_name || 'Chưa ghi giáo viên';\n  }",
    ),
    (
        "  useEffect(() => {\n    if (daySession) {\n      setSessionTeacher(daySession.teacher_name || '');\n      setNote(daySession.note || '');\n      return;\n    }\n    if (selectedTeacherOptions.length === 1) setSessionTeacher(selectedTeacherOptions[0]);\n    else setSessionTeacher('');\n  }, [daySession?.id, selectedClassId, selectedTeacherOptions.join('|')]);",
        "  useEffect(() => {\n    if (daySession) {\n      setSessionTeacher(daySession.teacher_name || '');\n      setLessonPeriods(daySession.session_status === 'cancelled' ? 0 : Number(daySession.lesson_periods || 1));\n      setNote(daySession.note || '');\n      setShowCancelSession(false);\n      setCancellationReason(daySession.cancellation_reason || '');\n      return;\n    }\n    setLessonPeriods(1);\n    setShowCancelSession(false);\n    setCancellationReason('');\n    if (selectedTeacherOptions.length === 1) setSessionTeacher(selectedTeacherOptions[0]);\n    else setSessionTeacher('');\n  }, [daySession?.id, selectedClassId, selectedTeacherOptions.join('|')]);",
    ),
    (
        "        p_teacher_name: sessionTeacher,\n        p_absent_member_keys: absentKeys,",
        "        p_teacher_name: sessionTeacher,\n        p_lesson_periods: lessonPeriods,\n        p_absent_member_keys: absentKeys,",
    ),
    (
        "  async function loadMonthlySessions(classId = selectedClassId, monthValue = calendarMonth) {",
        "  async function cancelClassSession() {\n    if (!selectedClass || busy || !client || isDayLocked || isFutureDate) return;\n    const reason = cancellationReason.trim();\n    if (!reason) {\n      setError('Vui lòng nhập Lý do hủy buổi học.');\n      return;\n    }\n    setBusy(true);\n    setError('');\n    setNotice('');\n    try {\n      const { data, error: cancelError } = await client.rpc('bes_cancel_extra_class_session', {\n        p_class_id: selectedClass.id,\n        p_attendance_date: attendanceDate,\n        p_cancellation_reason: reason,\n      });\n      if (cancelError) throw cancelError;\n      const created = Array.isArray(data) ? data[0] : data;\n      setDaySession(created || null);\n      setShowCancelSession(false);\n      setNotice(`Đã hủy buổi học ${selectedClass.class_name} ngày ${formatDate(attendanceDate)}.`);\n      await loadAll();\n      await loadMonthlySessions();\n    } catch (cancelError) {\n      setError(cancelError?.message || 'Không thể hủy buổi học.');\n      await loadDaySession();\n    } finally {\n      setBusy(false);\n    }\n  }\n\n  async function loadMonthlySessions(classId = selectedClassId, monthValue = calendarMonth) {",
    ),
    (
        "<div className=\"attendance-title\"><span><Icon name=\"attendance\" size={28} /></span><div><small>QUẢN LÝ CHUYÊN CẦN</small><strong>Điểm danh lớp phụ đạo & bồi dưỡng</strong><p>Mỗi lớp chỉ chốt một lần mỗi ngày · giờ xác nhận lưu theo máy chủ</p></div></div>",
        "<div className=\"attendance-title\"><span><Icon name=\"attendance\" size={28} /></span><div><small>QUẢN LÝ CHUYÊN CẦN</small><strong>Điểm danh lớp phụ đạo & bồi dưỡng</strong></div></div>",
    ),
    (
        "          <button type=\"button\" className={view === 'history' ? 'is-active' : ''} onClick={() => setView('history')}><Icon name=\"history\" size={18} />Lịch sử</button>\n        </nav>",
        "          <button type=\"button\" className={view === 'history' ? 'is-active' : ''} onClick={() => setView('history')}><Icon name=\"history\" size={18} />Lịch sử</button>\n          <button type=\"button\" className={view === 'report' ? 'is-active' : ''} onClick={() => setView('report')}><Icon name=\"history\" size={18} />Báo cáo</button>\n        </nav>",
    ),
    (
        "<header className=\"attendance-rollcall-head\"><div><span>{extraClassTypeLabel(selectedClass.class_type)}</span><h2>{selectedClass.class_name}</h2><p>{selectedClass.subject || 'Chưa ghi môn'} · GV phân công: {teachersForClass(selectedClass)}</p></div><div className=\"attendance-summary\"><b>{daySession ? `${daySession.present_count}/${daySession.total_students}` : `${summary.present}/${summary.total}`}</b><span>Có mặt</span><em>{daySession ? daySession.absent_count : summary.absent} vắng</em></div></header>",
        "<header className=\"attendance-rollcall-head\"><div><span>{extraClassTypeLabel(selectedClass.class_type)}</span><h2>{selectedClass.class_name}</h2><p>{selectedClass.subject || 'Chưa ghi môn'} · GV phân công: {teachersForClass(selectedClass)}</p></div><div className=\"attendance-summary\"><b>{daySession?.session_status === 'cancelled' ? 'Đã hủy' : daySession ? `${daySession.present_count}/${daySession.total_students}` : `${summary.present}/${summary.total}`}</b><span>{daySession?.session_status === 'cancelled' ? 'Buổi học' : 'Có mặt'}</span><em>{daySession?.session_status === 'cancelled' ? '0 tiết' : `${daySession ? daySession.absent_count : summary.absent} vắng`}</em></div></header>",
    ),
    (
        "                    <label className=\"is-teacher\"><span>Giáo viên dạy hôm nay</span>{selectedTeacherOptions.length > 1 ? <select value={sessionTeacher} disabled={isDayLocked} onChange={(event) => setSessionTeacher(event.target.value)}><option value=\"\">Chọn giáo viên</option>{selectedTeacherOptions.map((name) => <option key={name} value={name}>{name}</option>)}</select> : <strong>{selectedTeacherOptions[0] || sessionTeacher || 'Chưa có phân công'}</strong>}</label>\n                    {isDayLocked ? <div className=\"attendance-day-lock\"><Icon name=\"check\" size={18} /><div><b>Đã chốt {formatDate(daySession.attendance_date)}</b><span>GV {daySession.teacher_name} · {formatDateTime(daySession.checked_at)}</span></div></div> : <div className=\"attendance-day-open\"><b>Chưa chốt ngày này</b><span>{isFutureDate ? 'Không thể chọn ngày tương lai.' : 'Có thể điểm danh một lần.'}</span></div>}",
        "                    <label className=\"is-teacher\"><span>Giáo viên dạy hôm nay</span>{selectedTeacherOptions.length > 1 ? <select value={sessionTeacher} disabled={isDayLocked} onChange={(event) => setSessionTeacher(event.target.value)}><option value=\"\">Chọn giáo viên</option>{selectedTeacherOptions.map((name) => <option key={name} value={name}>{name}</option>)}</select> : <strong>{selectedTeacherOptions[0] || sessionTeacher || 'Chưa có phân công'}</strong>}</label>\n                    <div className=\"att-m3-period-field\"><span>Số tiết dạy</span><div className=\"att-m3-period-segment\">{[[1,'1 tiết'],[1.5,'1,5 tiết'],[2,'2 tiết']].map(([value,label]) => <button key={value} type=\"button\" disabled={isDayLocked} className={lessonPeriods === value ? 'is-active' : ''} onClick={() => setLessonPeriods(value)}>{label}</button>)}</div></div>\n                    {isDayLocked ? <div className={`attendance-day-lock ${daySession.session_status === 'cancelled' ? 'is-cancelled' : ''}`}><Icon name=\"check\" size={18} /><div><b>{daySession.session_status === 'cancelled' ? `Đã hủy ${formatDate(daySession.attendance_date)}` : `Đã điểm danh ${formatDate(daySession.attendance_date)}`}</b><span>{daySession.session_status === 'cancelled' ? `${daySession.cancellation_reason} · 0 tiết` : `GV ${daySession.teacher_name} · ${String(daySession.lesson_periods || 1).replace('.', ',')} tiết · ${formatDateTime(daySession.checked_at)}`}</span></div></div> : <div className=\"attendance-day-open\"><b>Chưa chốt ngày này</b><span>{isFutureDate ? 'Không thể chọn ngày tương lai.' : 'Có thể điểm danh hoặc hủy buổi học.'}</span></div>}",
    ),
    (
        "                  <footer className=\"attendance-confirm-bar\"><label><span>Ghi chú buổi học</span><input disabled={isDayLocked} value={note} onChange={(event) => setNote(event.target.value)} placeholder=\"Không bắt buộc\" /></label><div><span>{isDayLocked ? `Đã lưu ${formatDateTime(daySession.checked_at)}` : 'Giờ chốt được lấy từ máy chủ.'}</span><button type=\"button\" disabled={busy || !draft.length || isDayLocked || isFutureDate || !sessionTeacher} onClick={confirmAttendance}><Icon name=\"check\" size={18} />{isDayLocked ? `Đã chốt ${formatDate(daySession.attendance_date)}` : busy ? 'Đang lưu…' : 'Xác nhận điểm danh'}</button></div></footer>",
        "                  <footer className=\"attendance-confirm-bar\"><label><span>Ghi chú buổi học</span><input disabled={isDayLocked} value={note} onChange={(event) => setNote(event.target.value)} placeholder=\"Không bắt buộc\" /></label><div className=\"att-m3-session-actions\"><button className=\"att-m3-cancel-button\" type=\"button\" disabled={busy || isDayLocked || isFutureDate} onClick={() => setShowCancelSession((value) => !value)}>Hủy buổi học</button><button type=\"button\" disabled={busy || !draft.length || isDayLocked || isFutureDate || !sessionTeacher} onClick={confirmAttendance}><Icon name=\"check\" size={18} />{isDayLocked ? (daySession.session_status === 'cancelled' ? 'Đã hủy' : `Đã chốt ${formatDate(daySession.attendance_date)}`) : busy ? 'Đang lưu…' : 'Xác nhận điểm danh'}</button></div></footer>\n                  {showCancelSession && !isDayLocked ? <div className=\"att-m3-cancel-surface\"><label><span>Lý do hủy *</span><input value={cancellationReason} onChange={(event) => setCancellationReason(event.target.value)} placeholder=\"Ví dụ: Giáo viên bận công tác\" autoFocus /></label><button type=\"button\" onClick={() => { setShowCancelSession(false); setCancellationReason(''); }}>Không hủy</button><button className=\"is-confirm\" type=\"button\" disabled={busy || !cancellationReason.trim()} onClick={cancelClassSession}>{busy ? 'Đang lưu…' : 'Xác nhận hủy'}</button></div> : null}",
    ),
    (
        "                return <button key={dateValue} type=\"button\" className={`attendance-calendar-day ${dateValue === today ? 'is-today' : ''} ${session ? 'is-confirmed' : ''}`} disabled={!session} onClick={() => session && openSessionFromCalendar(session)}><span className=\"attendance-calendar-date\">{Number(dateValue.slice(-2))}</span>{session ? <><b><Icon name=\"check\" size={14} /> {session.present_count}/{session.total_students}</b><small>{session.teacher_name}</small><em>{formatDateTime(session.checked_at).split(' ')[1] || 'Đã chốt'}</em></> : <small>Chưa điểm danh</small>}</button>;",
        "                return <button key={dateValue} type=\"button\" className={`attendance-calendar-day ${dateValue === today ? 'is-today' : ''} ${session ? 'is-confirmed' : ''} ${session?.session_status === 'cancelled' ? 'is-cancelled' : ''}`} disabled={!session} onClick={() => session && openSessionFromCalendar(session)}><span className=\"attendance-calendar-date\">{Number(dateValue.slice(-2))}</span>{session ? (session.session_status === 'cancelled' ? <><b>Đã hủy</b><small>{session.cancellation_reason}</small><em>0 tiết</em></> : <><b><Icon name=\"check\" size={14} /> {session.present_count}/{session.total_students}</b><small>{session.teacher_name}</small><em>{String(session.lesson_periods || 1).replace('.', ',')} tiết</em></>) : <small>Chưa điểm danh</small>}</button>;",
    ),
    (
        "<div><b>{session.class_name}</b><small>{teacherForSession(session)} · {extraClassTypeLabel(session.class_type)}</small><time>{formatDate(session.attendance_date)} · {formatDateTime(session.checked_at)}</time></div><span className=\"attendance-history-count\"><b>{session.present_count}/{session.total_students}</b><em>{session.absent_count} vắng</em></span>",
        "<div><b>{session.class_name}</b><small>{session.session_status === 'cancelled' ? 'Đã hủy' : `${teacherForSession(session)} · ${String(session.lesson_periods || 1).replace('.', ',')} tiết`} · {extraClassTypeLabel(session.class_type)}</small><time>{formatDate(session.attendance_date)} · {formatDateTime(session.checked_at)}</time></div><span className=\"attendance-history-count\"><b>{session.session_status === 'cancelled' ? 'Đã hủy' : `${session.present_count}/${session.total_students}`}</b><em>{session.session_status === 'cancelled' ? '0 tiết' : `${session.absent_count} vắng`}</em></span>",
    ),
    (
        "<section className=\"attendance-history-detail\">{selectedSession ? <><header><span>{extraClassTypeLabel(selectedSession.class_type)}</span><h2>{selectedSession.class_name}</h2><p>Ngày học {formatDate(selectedSession.attendance_date)} · chốt {formatDateTime(selectedSession.checked_at)} · GV {teacherForSession(selectedSession)}</p><button type=\"button\" disabled={busy} onClick={() => deleteAttendanceSession(selectedSession)}><Icon name=\"trash\" size={17} />Xóa buổi điểm danh</button></header><div className=\"attendance-history-stat\"><div><b>{selectedSession.total_students}</b><span>Sĩ số</span></div><div><b>{selectedSession.present_count}</b><span>Có mặt</span></div><div><b>{selectedSession.absent_count}</b><span>Vắng</span></div></div>{selectedSession.note ? <div className=\"attendance-history-note\"><b>Ghi chú</b><p>{selectedSession.note}</p></div> : null}<div className=\"attendance-absent-list\"><strong>Học sinh vắng</strong>{selectedAbsentRecords.map((record, index) => <div key={record.id}><span>{index + 1}</span><div><b>{record.student_full_name}</b><small>{record.student_code || 'Không có mã HS'}</small></div><em>{record.school_class_name || '—'}</em></div>)}{!selectedAbsentRecords.length ? <p>Tất cả học sinh đều có mặt.</p> : null}</div></> : <div className=\"attendance-empty is-large\">Chọn một buổi để xem danh sách vắng và thời gian điểm danh.</div>}</section>",
        "<section className=\"attendance-history-detail\">{selectedSession ? <><header><span className={`att-m3-status-chip is-${selectedSession.session_status === 'cancelled' ? 'cancelled' : 'completed'}`}>{selectedSession.session_status === 'cancelled' ? 'Đã hủy' : 'Đã điểm danh'}</span><h2>{selectedSession.class_name}</h2><p>Ngày học {formatDate(selectedSession.attendance_date)} · chốt {formatDateTime(selectedSession.checked_at)}{selectedSession.session_status === 'cancelled' ? '' : ` · GV ${teacherForSession(selectedSession)}`}</p><span className=\"att-m3-period-chip\">{selectedSession.session_status === 'cancelled' ? '0 tiết' : `${String(selectedSession.lesson_periods || 1).replace('.', ',')} tiết`}</span><button type=\"button\" disabled={busy} onClick={() => deleteAttendanceSession(selectedSession)}><Icon name=\"trash\" size={17} />Xóa buổi điểm danh</button></header>{selectedSession.session_status === 'cancelled' ? <div className=\"att-m3-cancel-reason\"><b>Lý do hủy</b><p>{selectedSession.cancellation_reason}</p></div> : <><div className=\"attendance-history-stat\"><div><b>{selectedSession.total_students}</b><span>Sĩ số</span></div><div><b>{selectedSession.present_count}</b><span>Có mặt</span></div><div><b>{selectedSession.absent_count}</b><span>Vắng</span></div></div>{selectedSession.note ? <div className=\"attendance-history-note\"><b>Ghi chú</b><p>{selectedSession.note}</p></div> : null}<div className=\"attendance-absent-list\"><strong>Học sinh vắng</strong>{selectedAbsentRecords.map((record, index) => <div key={record.id}><span>{index + 1}</span><div><b>{record.student_full_name}</b><small>{record.student_code || 'Không có mã HS'}</small></div><em>{record.school_class_name || '—'}</em></div>)}{!selectedAbsentRecords.length ? <p>Tất cả học sinh đều có mặt.</p> : null}</div></>}</> : <div className=\"attendance-empty is-large\">Chọn một buổi để xem chi tiết.</div>}</section>",
    ),
    (
        "          {!loading && view === 'history' ? (\n            <div className=\"attendance-history-layout\">",
        "          {!loading && view === 'report' ? <AttendanceMonthlyReport client={client} classes={classes} month={reportMonth} onMonthChange={setReportMonth} onError={setError} /> : null}\n\n          {!loading && view === 'history' ? (\n            <div className=\"attendance-history-layout\">",
    ),
]

for old, new in replacements:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'Expected exactly one match, found {count}: {old[:140]!r}')
    text = text.replace(old, new, 1)

path.write_text(text, encoding='utf-8')
print('Patched GlobalAttendanceNavigationTab.jsx for Material 3 reporting')
