import fs from 'node:fs';
const version='11.3.1';
const generatedAt=new Date().toISOString();
const versionFile=JSON.parse(fs.readFileSync('public/version.json','utf8'));
versionFile.version=version;
versionFile.releaseName='English Global Success Lesson Architect';
versionFile.runtimeCore='2.3.1';
versionFile.schemaVersion='11.2.0';
versionFile.requiresSql=false;
versionFile.requiredMigration='';
versionFile.lessonArchitectEnglishOnly=true;
versionFile.globalSuccessPreset=true;
versionFile.digitalCompetenceFramework='Circular No. 02/2025/TT-BGDĐT';
versionFile.generatedAt=generatedAt;
fs.writeFileSync('public/version.json',JSON.stringify(versionFile,null,2)+'\n');
const release=JSON.parse(fs.readFileSync('public/release-manifest.json','utf8'));
release.version=version;
release.release='English Global Success Lesson Architect';
release.runtime='2.3.1';
release.schema='11.2.0';
release.englishOnlyLessonPlans=true;
release.globalSuccessGrade11=true;
release.moetDigitalCompetence=true;
release.digitalCompetenceFramework='Circular No. 02/2025/TT-BGDĐT';
release.generatedAt=generatedAt;
fs.writeFileSync('public/release-manifest.json',JSON.stringify(release,null,2)+'\n');
console.log(`Version registry synchronized: ${version}`);
