import fs from 'node:fs';
const must = (condition, message) => { if (!condition) throw new Error(message); };
const read = (path) => fs.readFileSync(path, 'utf8');
const server = read('server/unifiedAiProviderAdapter.js');
const runtime = read('src/utils/openRouter.js');
const registry = read('src/utils/aiPromptRegistry.js');
const main = read('src/main.jsx');
const textLab = read('src/pages/TextLabActivities.jsx');
must(read('src/config/version.js').includes("APP_VERSION = '12.40.1'"), 'V12.40.1 version is missing.');
must(server.includes("const FREE_MODEL = 'openrouter/free'"), 'OpenRouter free fallback model is missing.');
must(server.includes('executeChatRequest'), 'Credit-aware request wrapper is missing.');
must(server.includes("error?.code === 'OPENROUTER_CREDIT_LIMIT'"), 'Credit fallback trigger is missing.');
must(server.includes("OPENROUTER_BILLING_MODE"), 'Billing mode control is missing.');
must(server.includes('creditFallback: true'), 'Credit fallback metadata is missing.');
must(runtime.includes('creditFallback: Boolean(payload?.creditFallback)'), 'Browser provenance does not expose credit fallback.');
must(registry.includes("'textlab.generateActivity'"), 'TextLab task definition is missing.');
must(registry.includes('maxOutputTokens: 1400'), 'TextLab token budget was not reduced.');
must(main.includes('getAiServerHealth'), 'Global server gateway readiness bridge is missing.');
must(main.includes('aiGatewayReady || getProviderSummary().hasKey'), 'Global AI readiness still depends only on browser key state.');
must(textLab.includes('OPENROUTER_API_KEY trên Vercel'), 'TextLab gateway guidance was not updated.');
console.log('V12.40.1 verification passed: credit-aware free fallback, smaller TextLab budget, and global gateway readiness bridge are installed.');
