import fs from 'node:fs';
const must=(c,m)=>{if(!c) throw new Error(m)};
const settings=fs.readFileSync('src/pages/Settings.jsx','utf8');
const catalog=fs.readFileSync('src/data/aiProviderCatalog.js','utf8');
const providers=fs.readFileSync('src/utils/aiProviders.js','utf8');
must(settings.includes('OpenRouter AI Gateway'),'OpenRouter Gateway UI missing');
must(settings.includes('Lưu cho toàn website'),'Site-wide save action missing');
must(!settings.includes('AI Provider Command Center'),'Legacy provider command center remains');
must(!settings.includes('Tìm provider, model hoặc tính năng'),'Legacy provider search remains');
must(!settings.includes('visibleProviders.map'),'Legacy provider card list remains');
must((catalog.match(/\n  \{\n    id:/g)||[]).length===1,'Provider catalog must contain exactly one provider entry');
must(!/Google Gemini|Cerebras Inference|SambaNova|Cloudflare Workers|LM Studio|LocalAI/.test(settings+catalog+providers),'Retired provider labels remain in runtime source');
must(providers.includes("DEFAULT_PROVIDER = 'openrouter'"),'OpenRouter is not the default');
console.log('V12.39.1 verification passed: legacy provider UI removed; OpenRouter is the sole gateway.');
