import { WidgetRegistryEntry, WidgetCategory, WidgetType } from '../types';

export const WIDGET_REGISTRY: Record<WidgetType, WidgetRegistryEntry> = {
  // Time Category
  clock: {
    type: 'clock',
    title: { vi: 'Đồng hồ', en: 'Clock' },
    description: { vi: 'Đồng hồ kim hoặc số, ngày tháng, múi giờ', en: 'Digital/Analog clock with date & time' },
    icon: 'Clock',
    category: 'time',
    defaultWidth: 340,
    defaultHeight: 180,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { mode: 'digital', is24Hour: true, showSeconds: true, showDate: true },
  },
  timer: {
    type: 'timer',
    title: { vi: 'Bộ đếm ngược', en: 'Countdown Timer' },
    description: { vi: 'Đếm ngược thời gian với âm báo và đếm âm', en: 'Timer with custom alarms & overtime count' },
    icon: 'Timer',
    category: 'time',
    defaultWidth: 420,
    defaultHeight: 260,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { durationSeconds: 300, isRunning: false, remainingSeconds: 300, soundName: 'alarm' },
  },
  'visual-timer': {
    type: 'visual-timer',
    title: { vi: 'Đồng hồ trực quan', en: 'Visual Timer' },
    description: { vi: 'Đếm ngược bằng vòng tròn hoặc thanh màu thu nhỏ', en: 'Visual shrinking pie chart timer' },
    icon: 'PieChart',
    category: 'time',
    defaultWidth: 360,
    defaultHeight: 280,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { durationSeconds: 180, displayMode: 'circle' },
  },
  stopwatch: {
    type: 'stopwatch',
    title: { vi: 'Đồng hồ bấm giờ', en: 'Stopwatch' },
    description: { vi: 'Bấm giờ từng vòng và xuất file CSV', en: 'Lap timer with CSV export' },
    icon: 'Watch',
    category: 'time',
    defaultWidth: 320,
    defaultHeight: 280,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { laps: [] },
  },
  countdown: {
    type: 'countdown',
    title: { vi: 'Đếm ngược sự kiện', en: 'Event Countdown' },
    description: { vi: 'Đếm ngược đến giờ ra chơi, kiểm tra, thi đấu', en: 'Event countdown clock' },
    icon: 'Hourglass',
    category: 'time',
    defaultWidth: 440,
    defaultHeight: 240,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { title: 'Đếm ngược sự kiện', targetTimestamp: Date.now() + 86400000 },
  },
  calendar: {
    type: 'calendar',
    title: { vi: 'Lịch lớp học', en: 'Calendar' },
    description: { vi: 'Hiển thị lịch ngày, tuần, tháng và sự kiện', en: 'Classroom calendar view' },
    icon: 'Calendar',
    category: 'time',
    defaultWidth: 380,
    defaultHeight: 360,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { mode: 'month' },
  },
  timetable: {
    type: 'timetable',
    title: { vi: 'Lịch trình tiết học', en: 'Lesson Agenda' },
    description: { vi: 'Các bước tiết học (Warm-up, Practice, Exit ticket...)', en: 'Lesson sequence and agenda' },
    icon: 'ListOrdered',
    category: 'time',
    defaultWidth: 480,
    defaultHeight: 340,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { items: [] },
  },

  // Classroom Category
  'traffic-light': {
    type: 'traffic-light',
    title: { vi: 'Đèn tín hiệu', en: 'Traffic Light' },
    description: { vi: 'Đèn Xanh/Vàng/Đỏ kiểm soát trạng thái lớp', en: 'Green/Yellow/Red status lights' },
    icon: 'Disc',
    category: 'classroom',
    defaultWidth: 360,
    defaultHeight: 220,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { state: 'green', labels: { green: 'Hoạt động bình thường', yellow: 'Chú ý giảm âm lượng', red: 'Dừng lại quan sát' } },
  },
  'work-symbols': {
    type: 'work-symbols',
    title: { vi: 'Chế độ làm việc', en: 'Work Symbols' },
    description: { vi: 'Biểu tượng Im lặng, Làm cặp, Thảo luận nhóm...', en: 'Work mode icons (Silent, Pair, Group)' },
    icon: 'Users',
    category: 'classroom',
    defaultWidth: 420,
    defaultHeight: 200,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { activeSymbol: 'silent' },
  },
  'sound-level': {
    type: 'sound-level',
    title: { vi: 'Đo tiếng ồn', en: 'Noise Meter' },
    description: { vi: 'Phân tích mức âm thanh qua micro và cảnh báo', en: 'Web Audio microphone noise level meter' },
    icon: 'Volume2',
    category: 'classroom',
    defaultWidth: 440,
    defaultHeight: 240,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: false,
      usesMicrophone: true,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { threshold: 60, sensitivity: 'medium' },
  },
  'attention-signal': {
    type: 'attention-signal',
    title: { vi: 'Tín hiệu tập trung', en: 'Attention Signal' },
    description: { vi: 'Phát chuông, tiếng vỗ tay, gõ phách tập trung', en: 'Sound effect buttons for attention' },
    icon: 'Bell',
    category: 'classroom',
    defaultWidth: 340,
    defaultHeight: 200,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: false,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { sound: 'chime' },
  },
  scoreboard: {
    type: 'scoreboard',
    title: { vi: 'Bảng điểm', en: 'Scoreboard' },
    description: { vi: 'Cộng/trừ điểm theo đội hoặc cá nhân', en: 'Points counter for teams & students' },
    icon: 'Trophy',
    category: 'classroom',
    defaultWidth: 440,
    defaultHeight: 320,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { teams: [{ id: 't1', name: 'Đội A', score: 0, color: '#1a73e8' }, { id: 't2', name: 'Đội B', score: 0, color: '#e37400' }] },
  },

  // Students Category
  randomizer: {
    type: 'randomizer',
    title: { vi: 'Chọn tên ngẫu nhiên', en: 'Name Picker' },
    description: { vi: 'Gợi ý học sinh trả lời bài (Có chế độ công bằng)', en: 'Random name selector with fairness' },
    icon: 'Shuffle',
    category: 'students',
    defaultWidth: 420,
    defaultHeight: 380,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { fairnessMode: true, history: [] },
  },
  'group-maker': {
    type: 'group-maker',
    title: { vi: 'Chia nhóm học sinh', en: 'Group Maker' },
    description: { vi: 'Tự động chia nhóm ngẫu nhiên theo số nhóm/sĩ số', en: 'Student group generator' },
    icon: 'Grid',
    category: 'students',
    defaultWidth: 540,
    defaultHeight: 420,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { groupCount: 4 },
  },
  'seating-picker': {
    type: 'seating-picker',
    title: { vi: 'Sơ đồ chỗ ngồi', en: 'Seating Picker' },
    description: { vi: 'Chọn ngẫu nhiên theo vị trí sơ đồ lớp', en: 'Seating layout student selector' },
    icon: 'LayoutGrid',
    category: 'students',
    defaultWidth: 520,
    defaultHeight: 380,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { rows: 4, cols: 5 },
  },

  // Interactive & Games Category
  poll: {
    type: 'poll',
    title: { vi: 'Bình chọn nhanh', en: 'Quick Poll' },
    description: { vi: 'Tạo câu hỏi trắc nghiệm, hiển thị biểu đồ kết quả', en: 'Live poll & results charts' },
    icon: 'BarChart2',
    category: 'interactive',
    defaultWidth: 520,
    defaultHeight: 380,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { question: 'Câu hỏi trắc nghiệm?', options: [{ id: '1', text: 'Phương án A', votes: 0 }, { id: '2', text: 'Phương án B', votes: 0 }] },
  },
  dice: {
    type: 'dice',
    title: { vi: 'Xúc xắc', en: 'Dice Roller' },
    description: { vi: 'Tung 1-6 viên xúc xắc D4, D6, D8, D10, D12, D20', en: 'Roll 1-6 animated dice' },
    icon: 'Dices',
    category: 'games',
    defaultWidth: 380,
    defaultHeight: 260,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { count: 1, diceType: 'D6', values: [1] },
  },
  'coin-toss': {
    type: 'coin-toss',
    title: { vi: 'Tung đồng xu', en: 'Coin Toss' },
    description: { vi: 'Mặt Sấp/Ngửa, Đúng/Sai, Đội A/B', en: 'Flip coin for instant choice' },
    icon: 'CircleDot',
    category: 'games',
    defaultWidth: 320,
    defaultHeight: 260,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { headsLabel: 'Mặt Sấp', tailsLabel: 'Mặt Ngửa', currentResult: 'heads' },
  },
  spinner: {
    type: 'spinner',
    title: { vi: 'Vòng quay may mắn', en: 'Spinner Wheel' },
    description: { vi: 'Vòng quay câu hỏi hoặc danh sách chọn', en: 'Custom decision spinner wheel' },
    icon: 'RotateCw',
    category: 'games',
    defaultWidth: 460,
    defaultHeight: 460,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { options: ['Lựa chọn 1', 'Lựa chọn 2', 'Lựa chọn 3', 'Lựa chọn 4'] },
  },
  'number-generator': {
    type: 'number-generator',
    title: { vi: 'Tạo số ngẫu nhiên', en: 'Number Generator' },
    description: { vi: 'Tạo số trong khoảng tự chọn, không lặp', en: 'Random number generator' },
    icon: 'Binary',
    category: 'games',
    defaultWidth: 340,
    defaultHeight: 240,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: false,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { min: 1, max: 40, allowRepeat: false, history: [] },
  },
  'word-puzzle': {
    type: 'word-puzzle',
    title: { vi: 'Ô chữ bí mật', en: 'Word Puzzle' },
    description: { vi: 'Trò chơi đoán từ / từ khóa bài học', en: 'Classroom secret word guessing puzzle' },
    icon: 'HelpCircle',
    category: 'games',
    defaultWidth: 480,
    defaultHeight: 380,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { word: 'VIETNAM', hint: 'Tên quốc gia thân yêu của chúng ta', guessedLetters: [] },
  },
  flashcard: {
    type: 'flashcard',
    title: { vi: 'Thẻ ghi nhớ Flashcard', en: 'Flashcard' },
    description: { vi: 'Thẻ Lật 2 mặt câu hỏi & đáp án ghi nhớ', en: '2-sided interactive flashcard study game' },
    icon: 'Sparkles',
    category: 'interactive',
    defaultWidth: 420,
    defaultHeight: 320,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: {
      cards: [
        { question: 'Thủ đô của Việt Nam là gì?', answer: 'Hà Nội' },
        { question: 'Công thức hóa học của Nước?', answer: 'H2O' },
        { question: '3 x 8 bằng bao nhiêu?', answer: '24' },
      ],
      currentIndex: 0,
      isFlipped: false,
      learnedCount: 0,
    },
  },
  'true-false-race': {
    type: 'true-false-race',
    title: { vi: 'Thách thức Đúng / Sai', en: 'True or False Race' },
    description: { vi: 'Đua điểm trả lời Đúng/Sai nhanh', en: 'Fast-paced True/False classroom quiz' },
    icon: 'Zap',
    category: 'games',
    defaultWidth: 440,
    defaultHeight: 320,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: {
      questions: [
        { text: 'Trái Đất là hành tinh thứ 3 tính từ Mặt Trời?', isTrue: true },
        { text: 'Nước đóng băng ở 100 độ C?', isTrue: false },
        { text: 'Hình vuông có 4 cạnh bằng nhau?', isTrue: true },
      ],
      currentIndex: 0,
      score: 0,
      streak: 0,
    },
  },
  'tic-tac-toe': {
    type: 'tic-tac-toe',
    title: { vi: 'Caro Lớp Học (3x3)', en: 'Classroom Tic-Tac-Toe' },
    description: { vi: 'Trò chơi Caro thi đấu giữa Đội X & Đội O', en: 'Classroom 3x3 Tic-Tac-Toe competition' },
    icon: 'Trophy',
    category: 'games',
    defaultWidth: 380,
    defaultHeight: 400,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: {
      board: Array(9).fill(null),
      xIsNext: true,
      scoreX: 0,
      scoreO: 0,
    },
  },

  // Content Category
  text: {
    type: 'text',
    title: { vi: 'Văn bản', en: 'Text' },
    description: { vi: 'Soạn thảo nội dung, tiêu đề, hướng dẫn bài tập', en: 'Rich text headers and instructions' },
    icon: 'Type',
    category: 'content',
    defaultWidth: 440,
    defaultHeight: 180,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { content: 'Nhập nội dung văn bản ở đây...' },
  },
  'sticky-note': {
    type: 'sticky-note',
    title: { vi: 'Ghi chú dán', en: 'Sticky Note' },
    description: { vi: 'Thẻ ghi chú màu xinh xắn', en: 'Colorful memo note card' },
    icon: 'StickyNote',
    category: 'content',
    defaultWidth: 320,
    defaultHeight: 240,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { title: 'Ghi chú', content: 'Ghi lại nhắc nhở cho tiết học...' },
  },
  checklist: {
    type: 'checklist',
    title: { vi: 'Danh sách công việc', en: 'Checklist' },
    description: { vi: 'Đánh dấu các bước đã hoàn thành', en: 'Interactive checklist with completion' },
    icon: 'CheckSquare',
    category: 'content',
    defaultWidth: 380,
    defaultHeight: 260,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { items: [{ id: '1', text: 'Nhiệm vụ 1', completed: false }, { id: '2', text: 'Nhiệm vụ 2', completed: false }] },
  },
  'qr-code': {
    type: 'qr-code',
    title: { vi: 'Tạo mã QR', en: 'QR Code' },
    description: { vi: 'Mã QR chia sẻ liên kết, câu hỏi, Wi-Fi', en: 'Client-side QR Code generator' },
    icon: 'QrCode',
    category: 'content',
    defaultWidth: 320,
    defaultHeight: 280,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { url: 'https://ai.studio', title: 'Quét mã QR:' },
  },
  hyperlink: {
    type: 'hyperlink',
    title: { vi: 'Liên kết nhanh', en: 'Quick Link' },
    description: { vi: 'Nút bấm truy cập website, tài liệu', en: 'Quick link button card' },
    icon: 'ExternalLink',
    category: 'content',
    defaultWidth: 300,
    defaultHeight: 140,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: false,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { title: 'Trang web bài học', url: 'https://example.com' },
  },

  // Media Category
  image: {
    type: 'image',
    title: { vi: 'Hình ảnh', en: 'Image' },
    description: { vi: 'Tải ảnh PNG/JPG/SVG từ máy tính', en: 'Upload PNG/JPG images' },
    icon: 'Image',
    category: 'media',
    defaultWidth: 440,
    defaultHeight: 320,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { fit: 'contain' },
  },
  pdf: {
    type: 'pdf',
    title: { vi: 'Tài liệu PDF', en: 'PDF Viewer' },
    description: { vi: 'Trình chiếu file PDF trực tiếp trên canvas', en: 'Multi-page PDF document presenter' },
    icon: 'FileText',
    category: 'media',
    defaultWidth: 540,
    defaultHeight: 420,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { currentPage: 1 },
  },
  video: {
    type: 'video',
    title: { vi: 'Video', en: 'Video Player' },
    description: { vi: 'Phát video cục bộ hoặc link YouTube', en: 'Local or YouTube video embed' },
    icon: 'Video',
    category: 'media',
    defaultWidth: 520,
    defaultHeight: 320,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: true,
    },
    defaultSettings: { videoUrl: '' },
  },
  audio: {
    type: 'audio',
    title: { vi: 'Trình phát âm thanh', en: 'Audio Player' },
    description: { vi: 'Phát nhạc nền, bài nghe Tiếng Anh', en: 'Audio player for tracks & listening tests' },
    icon: 'Music',
    category: 'media',
    defaultWidth: 380,
    defaultHeight: 160,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: false,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { title: 'Bài nghe Tiếng Anh', loop: false },
  },
  webcam: {
    type: 'webcam',
    title: { vi: 'Camera trực tiếp', en: 'Webcam Stream' },
    description: { vi: 'Hiển thị góc quay camera giáo viên hoặc sản phẩm', en: 'Live camera video feed' },
    icon: 'Camera',
    category: 'media',
    defaultWidth: 420,
    defaultHeight: 280,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: true,
      usesNetwork: false,
    },
    defaultSettings: { mirrored: true },
  },
  embed: {
    type: 'embed',
    title: { vi: 'Nhúng trang web', en: 'Web Embed' },
    description: { vi: 'Iframe Google Slides, Padlet, Canva embed', en: 'Sanitized web iframe embed' },
    icon: 'Globe',
    category: 'media',
    defaultWidth: 560,
    defaultHeight: 380,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: true,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: true,
    },
    defaultSettings: { embedUrl: '' },
  },
  'browser-card': {
    type: 'browser-card',
    title: { vi: 'Thẻ liên kết web', en: 'Browser Card' },
    description: { vi: 'Hiển thị xem trước trang web an toàn', en: 'Safe website preview card' },
    icon: 'Compass',
    category: 'media',
    defaultWidth: 380,
    defaultHeight: 200,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: false,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: true,
    },
    defaultSettings: { title: 'Tài nguyên dạy học', url: 'https://wikipedia.org' },
  },

  // Decoration Category
  draw: {
    type: 'draw',
    title: { vi: 'Bảng vẽ & Chú thích', en: 'Drawing Canvas' },
    description: { vi: 'Vẽ tự do, đánh dấu, viết chữ lên màn hình', en: 'Freehand canvas drawing & annotations' },
    icon: 'PenTool',
    category: 'decoration',
    defaultWidth: 480,
    defaultHeight: 320,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: false,
      supportsFullscreen: true,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { color: '#1a73e8', brushSize: 4 },
  },
  sticker: {
    type: 'sticker',
    title: { vi: 'Sticker trang trí', en: 'Stickers & Badges' },
    description: { vi: 'Huy hiệu, ngôi sao, sticker động viên học sinh', en: 'Rewards and decorative badges' },
    icon: 'Smile',
    category: 'decoration',
    defaultWidth: 160,
    defaultHeight: 160,
    capabilities: {
      resizable: true,
      rotatable: true,
      pinnable: true,
      spotlightable: false,
      supportsFullscreen: false,
      usesMicrophone: false,
      usesCamera: false,
      usesNetwork: false,
    },
    defaultSettings: { stickerType: 'star' },
  },
};
