import './styles/SupplementalLearning.css';
import { ensureRuntimeReady, getRuntimeClient, subscribeRuntime } from './services/runtime/core.js';
import { attachSupplementalProof, beginSupplementalAttendance, confirmSupplementalAttendance } from './attendance/supplementalLearningApi.js';

const INSTALL_KEY='__besSupplementalAttendanceQuickInstalled';
const ROLLCALL_ID='bes-supplemental-rollcall';
const OPEN_EVENT='bes-open-supplemental-attendance';
const CHANGED_EVENT='bes-supplemental-attendance-changed';
let client=null;let activeSession=null;let participantState=[];let busy=false;
function esc(value){return String(value??'').replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function kindLabel(kind){return kind==='recurring'?'Nhóm dài ngày':'Phát sinh';}
function accessError(error){const code=String(error?.message||error||'');if(code.includes('outside_time'))return'Ngoài khung Giờ GV do Admin quy định.';if(code.includes('missing_permission'))return'Tài khoản chưa được Admin cấp quyền Điểm danh nhanh.';if(code.includes('cancelled')||code.includes('đã bị hủy'))return'Buổi Học bổ sung đã bị hủy.';return code||'Không thể mở điểm danh Học bổ sung.';}
function safeFileName(name='proof.jpg'){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(-120)||'proof.jpg';}
function closeRollcall(){document.getElementById(ROLLCALL_ID)?.remove();activeSession=null;participantState=[];}
function participantHtml(p,index){const absent=p.status==='absent';return `<article class="bes-supplemental-participant" data-index="${index}"><div><strong>${esc(p.fullName)}</strong><small>${esc(p.studentCode||'Không mã')} · ${esc(p.schoolClassName||'Chưa lớp')}</small></div><div class="bes-supplemental-status-buttons">${['present','tardy','absent'].map((status)=>`<button type="button" data-status="${status}" class="${p.status===status?'is-active':''}">${status==='present'?'Có mặt':status==='tardy'?'Đi trễ':'Vắng'}</button>`).join('')}</div><div class="bes-supplemental-absence ${absent?'':'is-hidden'}"><select data-field="absenceReasonCode"><option value="">Lý do vắng</option><option value="permission" ${p.absenceReasonCode==='permission'?'selected':''}>Có phép</option><option value="sick" ${p.absenceReasonCode==='sick'?'selected':''}>Ốm</option><option value="unknown" ${p.absenceReasonCode==='unknown'?'selected':''}>Không rõ lý do</option><option value="other" ${p.absenceReasonCode==='other'?'selected':''}>Khác</option></select><input data-field="absenceNote" value="${esc(p.absenceNote||'')}" placeholder="Ghi chú vắng"></div></article>`;}
function renderRollcall(message=''){let host=document.getElementById(ROLLCALL_ID);if(!host){host=document.createElement('div');host.id=ROLLCALL_ID;document.body.append(host);}const s=activeSession?.session||{};host.innerHTML=`<div class="bes-supplemental-backdrop" data-rollcall-close></div><section class="bes-supplemental-rollcall" role="dialog" aria-modal="true"><header><div><span class="bes-supplemental-source-badge">HỌC BỔ SUNG · ${kindLabel(s.kind)}</span><h2>${esc(s.title||s.subject||'Học bổ sung')}</h2><p>${esc(s.attendance_date||'')} · ${esc(s.subject||'')} · ${esc(s.teacher_name||'Chưa giáo viên')} · ${esc(s.room||'Chưa phòng')}</p></div><button type="button" data-rollcall-close aria-label="Đóng">×</button></header>${message?`<div class="bes-supplemental-rollcall-message">${esc(message)}</div>`:''}<main>${participantState.map(participantHtml).join('')||'<p class="bes-supplemental-empty">Buổi học chưa có học sinh.</p>'}</main><footer><label>Ghi chú buổi học<textarea data-session-note rows="2">${esc(s.session_note||'')}</textarea></label><label>Minh chứng hình ảnh<input type="file" data-proof accept="image/*"></label><div><button type="button" data-rollcall-close>Thoát</button><button type="button" class="is-primary" data-confirm ${busy?'disabled':''}>Chốt điểm danh</button></div></footer></section>`;bindRollcall(host);}
function bindRollcall(host){host.querySelectorAll('[data-rollcall-close]').forEach((n)=>n.addEventListener('click',closeRollcall));host.querySelectorAll('.bes-supplemental-participant').forEach((row)=>{const index=Number(row.dataset.index);row.querySelectorAll('[data-status]').forEach((button)=>button.addEventListener('click',()=>{participantState[index].status=button.dataset.status;if(button.dataset.status!=='absent'){participantState[index].absenceReasonCode='';participantState[index].absenceNote='';}renderRollcall();}));row.querySelector('[data-field="absenceReasonCode"]')?.addEventListener('change',(e)=>{participantState[index].absenceReasonCode=e.target.value;});row.querySelector('[data-field="absenceNote"]')?.addEventListener('input',(e)=>{participantState[index].absenceNote=e.target.value;});});host.querySelector('[data-confirm]')?.addEventListener('click',()=>void confirmCurrent(host));}
async function ensureClient(){if(client)return client;try{await ensureRuntimeReady();}catch{/* runtime can recover */}client=getRuntimeClient();return client;}
async function openRollcall(rawSessionId,knownStatus=''){if(busy)return;const sessionId=String(rawSessionId||'').trim();if(!sessionId)return;const status=String(knownStatus||'').toLowerCase();if(status==='confirmed'){window.alert('Buổi Học bổ sung này đã chốt điểm danh. Xem tại Lịch sử.');return;}if(status==='cancelled'){window.alert('Buổi Học bổ sung đã bị hủy.');return;}await ensureClient();if(!client){window.alert('Chưa thể kết nối dữ liệu điểm danh. Vui lòng thử lại.');return;}busy=true;try{activeSession=await beginSupplementalAttendance(client,sessionId);participantState=(activeSession?.participants||[]).map((p)=>({participantId:p.id,status:p.status||'present',fullName:p.fullName||p.full_name||'',studentCode:p.studentCode||p.student_code||'',schoolClassName:p.schoolClassName||p.school_class_name||'',absenceReasonCode:p.absenceReasonCode||p.absence_reason_code||'',absenceNote:p.absenceNote||p.absence_note||''}));renderRollcall();}catch(error){window.alert(accessError(error));}finally{busy=false;}}
async function confirmCurrent(host){if(!activeSession||busy)return;const missing=participantState.find((p)=>!['present','absent','tardy'].includes(p.status));if(missing){renderRollcall('Hãy chọn trạng thái cho toàn bộ học sinh.');return;}const absentWithoutReason=participantState.find((p)=>p.status==='absent'&&!p.absenceReasonCode);if(absentWithoutReason){renderRollcall(`Hãy chọn lý do vắng cho ${absentWithoutReason.fullName}.`);return;}busy=true;const note=host.querySelector('[data-session-note]')?.value||'';const file=host.querySelector('[data-proof]')?.files?.[0]||null;const sessionId=activeSession.session.id;const proofPath=file?`${sessionId}/${Date.now()}-${safeFileName(file.name)}`:'';renderRollcall('Đang chốt điểm danh trên máy chủ…');try{await confirmSupplementalAttendance(client,{sessionId,participants:participantState,sessionNote:note,proofPath:''});let proofWarning='';if(file){const {error}=await client.storage.from('attendance-session-proofs').upload(proofPath,file,{upsert:false,contentType:file.type||'image/jpeg'});if(error){proofWarning='Điểm danh đã chốt nhưng ảnh minh chứng chưa tải lên được.';}else{try{await attachSupplementalProof(client,sessionId,proofPath);}catch{proofWarning='Điểm danh và ảnh đã lưu, nhưng chưa gắn được ảnh vào lịch sử buổi học.';}}}closeRollcall();window.dispatchEvent(new CustomEvent(CHANGED_EVENT,{detail:{sessionId}}));if(proofWarning)window.alert(proofWarning);}catch(error){renderRollcall(error?.message||'Không thể chốt điểm danh.');}finally{busy=false;}}
async function handleOpen(event){const sessionId=event?.detail?.sessionId;const status=event?.detail?.status||'';await openRollcall(sessionId,status);}
async function install(){if(window[INSTALL_KEY])return;window[INSTALL_KEY]=true;window.addEventListener(OPEN_EVENT,handleOpen);try{await ensureRuntimeReady();}catch{/* runtime can recover */}client=getRuntimeClient();subscribeRuntime(()=>{client=getRuntimeClient();});}
if(typeof window!=='undefined'&&typeof document!=='undefined')void install();
