import './styles/SupplementalLearning.css';
import { ensureRuntimeReady, getRuntimeClient, getRuntimeState, subscribeRuntime } from './services/runtime/core.js';
import { loadAttendanceActivities, loadSupplementalHistory, loadSupplementalStudentReport } from './attendance/supplementalLearningApi.js';

const INSTALL_KEY='__besSupplementalReportingInstalled';
const FILTER_ID='bes-supplemental-activity-filter';
const PANEL_ID='bes-supplemental-reporting-panel';
const TAB_SELECTOR='.attendance-tabs button';
let client=null;let runtime=null;let observer=null;let activeTab='';let filter='all';let query='';let dateFrom='';let dateTo='';let loading=false;let token=0;
function esc(value){return String(value??'').replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function dayOffset(days){const date=new Date();date.setDate(date.getDate()+days);return date.toISOString().slice(0,10);}
function normalize(value){return String(value||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function tabKind(button){const text=normalize(button?.textContent);if(/lich su|history/.test(text))return'history';if(/bao cao|report/.test(text))return'report';return'';}
function activeButton(){return [...document.querySelectorAll(TAB_SELECTOR)].find((button)=>button.getAttribute('aria-selected')==='true'||button.classList.contains('active')||button.dataset.active==='true');}
function detectActiveTab(){const detected=tabKind(activeButton());if(detected)activeTab=detected;return activeTab;}
function shell(){return document.querySelector('.attendance-shell')||document.querySelector('[data-route="attendance"]')||document.querySelector('#bes-main-content');}
function filterOptions(){return[['all','Tất cả'],['remedial','Phụ đạo'],['enrichment','Bồi dưỡng'],['supplemental','Học bổ sung']];}
function ensureFilter(){const host=shell();if(!host||!detectActiveTab()){document.getElementById(FILTER_ID)?.remove();closePanel();return;}let bar=document.getElementById(FILTER_ID);if(!bar){bar=document.createElement('section');bar.id=FILTER_ID;bar.className='bes-supplemental-report-filter';const tabs=document.querySelector('.attendance-tabs');if(tabs?.parentElement)tabs.insertAdjacentElement('afterend',bar);else host.prepend(bar);}bar.innerHTML=`<div><span>Loại hoạt động</span>${filterOptions().map(([value,label])=>`<button type="button" data-activity-filter="${value}" class="${filter===value?'is-active':''}">${label}</button>`).join('')}</div><small>${activeTab==='report'?'Báo cáo Phụ đạo/Bồi dưỡng hiện tại được giữ nguyên; Học bổ sung có báo cáo riêng.':'Lịch sử có thể xem riêng Học bổ sung hoặc xem tất cả hoạt động.'}</small>`;bar.querySelectorAll('[data-activity-filter]').forEach((button)=>button.addEventListener('click',()=>{filter=button.dataset.activityFilter;window.dispatchEvent(new CustomEvent('bes-attendance-activity-filter-change',{detail:{activityType:filter,tab:activeTab}}));ensureFilter();void refreshPanel();}));void refreshPanel();}
function rangeControls(){if(!dateFrom)dateFrom=dayOffset(activeTab==='report'?-365:-31);if(!dateTo)dateTo=dayOffset(0);return`<div class="bes-supplemental-report-tools"><label>Từ ngày<input type="date" data-report-from value="${esc(dateFrom)}"></label><label>Đến ngày<input type="date" data-report-to value="${esc(dateTo)}"></label>${activeTab==='history'?`<label>Tìm kiếm<input type="search" data-report-query value="${esc(query)}" placeholder="Học sinh, môn, nhóm, giáo viên"></label>`:''}<button type="button" data-report-refresh>Cập nhật</button>${activeTab==='report'&&filter==='supplemental'?'<button type="button" class="is-primary" data-report-print>In / Lưu PDF</button>':''}</div>`;}
function statusLabel(value){return({confirmed:'Đã chốt',cancelled:'Đã hủy',scheduled:'Chưa điểm danh',in_progress:'Đang điểm danh',present:'Có mặt',absent:'Vắng',tardy:'Đi trễ'})[value]||value||'';}
function activityLabel(type){return({remedial:'Phụ đạo',enrichment:'Bồi dưỡng',supplemental:'Học bổ sung'})[type]||type;}
function historyHtml(rows){if(!rows.length)return'<p class="bes-supplemental-empty">Không có dữ liệu phù hợp trong khoảng ngày này.</p>';return`<div class="bes-supplemental-history-list">${rows.map((row)=>{const participants=row.participants||[];return`<article class="bes-supplemental-history-card"><header><div><span class="bes-supplemental-source-badge">HỌC BỔ SUNG · ${row.kind==='recurring'?'Nhóm dài ngày':'Phát sinh'}</span><h3>${esc(row.title||row.subject)}</h3><p>${esc(row.date)} · ${esc(row.subject)} · ${esc(row.teacherName||'Chưa giáo viên')} · ${esc(row.room||'Chưa phòng')} · ${esc(row.timeRange||'')}</p></div><strong>${statusLabel(row.status)}</strong></header>${row.status==='confirmed'?`<div class="bes-supplemental-history-stats"><span>Tổng <b>${Number(row.totalStudents||0)}</b></span><span>Có mặt <b>${Number(row.presentCount||0)}</b></span><span>Đi trễ <b>${Number(row.tardyCount||0)}</b></span><span>Vắng <b>${Number(row.absentCount||0)}</b></span></div>`:''}${row.cancellationReason?`<p class="bes-supplemental-cancel-reason">Lý do hủy: ${esc(row.cancellationReason)}</p>`:''}${participants.length?`<details><summary>Danh sách học sinh (${participants.length})</summary><div class="bes-supplemental-history-participants">${participants.map((p)=>`<div><span><b>${esc(p.fullName)}</b><small>${esc(p.studentCode||'Không mã')} · ${esc(p.schoolClassName||'Chưa lớp')}</small></span><em data-status="${esc(p.status)}">${statusLabel(p.status)}</em>${p.status==='absent'&&(p.absenceReasonCode||p.absenceNote)?`<small>${esc(p.absenceReasonCode||'')} ${esc(p.absenceNote||'')}</small>`:''}</div>`).join('')}</div></details>`:''}${row.sessionNote?`<p><b>Ghi chú:</b> ${esc(row.sessionNote)}</p>`:''}</article>`;}).join('')}</div>`;}
function unifiedHistoryHtml(rows){if(!rows.length)return'<p class="bes-supplemental-empty">Không có hoạt động trong khoảng ngày này.</p>';return`<div class="bes-supplemental-unified-list">${rows.map((row)=>`<article><span data-type="${esc(row.activityType)}">${activityLabel(row.activityType)}</span><div><b>${esc(row.title||row.subject)}</b><small>${esc(row.date)} · ${esc(row.subject)} · ${esc(row.teacherName||'')} · ${esc(row.timeRange||'')} · ${esc(row.room||'')}</small></div><strong>${statusLabel(row.status)}</strong></article>`).join('')}</div>`;}
function reportHtml(rows){const totals=rows.reduce((acc,row)=>{acc.sessions+=Number(row.eligibleSessionCount||0);acc.present+=Number(row.presentCount||0);acc.absent+=Number(row.absentCount||0);acc.tardy+=Number(row.tardyCount||0);return acc;},{sessions:0,present:0,absent:0,tardy:0});return`<section class="bes-supplemental-pdf-report"><header><span>SỞ GIÁO DỤC VÀ ĐÀO TẠO THÀNH PHỐ HỒ CHÍ MINH</span><strong>TRƯỜNG TRUNG - TIỂU HỌC PÉTRUS KÝ</strong><h1>BÁO CÁO HỌC BỔ SUNG KIẾN THỨC</h1><p>Từ ${esc(dateFrom)} đến ${esc(dateTo)} · Chỉ tính các buổi đã chốt điểm danh; buổi hủy không vào mẫu số.</p></header><div class="bes-supplemental-report-summary"><span>Học sinh <b>${rows.length}</b></span><span>Lượt buổi đủ điều kiện <b>${totals.sessions}</b></span><span>Có mặt <b>${totals.present}</b></span><span>Đi trễ <b>${totals.tardy}</b></span><span>Vắng <b>${totals.absent}</b></span></div>${rows.length?`<div class="bes-supplemental-report-table-wrap"><table><thead><tr><th>Học sinh</th><th>Lớp</th><th>Môn</th><th>Buổi</th><th>Có mặt</th><th>Trễ</th><th>Vắng</th><th>Tỉ lệ</th></tr></thead><tbody>${rows.map((row)=>`<tr><td><b>${esc(row.fullName)}</b><small>${esc(row.studentCode||'')}</small></td><td>${esc(row.schoolClassName||'')}</td><td>${esc((row.subjects||[]).join(', '))}</td><td>${Number(row.eligibleSessionCount||0)}</td><td>${Number(row.presentCount||0)}</td><td>${Number(row.tardyCount||0)}</td><td>${Number(row.absentCount||0)}</td><td>${Number(row.attendanceRate||0)}%</td></tr>`).join('')}</tbody></table></div>`:'<p class="bes-supplemental-empty">Chưa có buổi Học bổ sung đã chốt trong khoảng ngày.</p>'}</section>`;}
function renderPanel(body,title){let panel=document.getElementById(PANEL_ID);if(!panel){panel=document.createElement('section');panel.id=PANEL_ID;panel.className='bes-supplemental-reporting-panel';const host=shell();host?.append(panel);}panel.innerHTML=`<header class="bes-supplemental-reporting-head"><div><span class="bes-supplemental-kicker">${activeTab==='report'?'BÁO CÁO':'LỊCH SỬ'} · ${activityLabel(filter)||'Tất cả'}</span><h2>${esc(title)}</h2></div>${filter==='supplemental'?'<button type="button" data-report-close aria-label="Quay về dữ liệu hiện có">×</button>':''}</header>${rangeControls()}<main>${body}</main>`;panel.classList.toggle('is-exclusive',filter==='supplemental');if(filter==='supplemental')document.body.classList.add('bes-supplemental-report-exclusive');else document.body.classList.remove('bes-supplemental-report-exclusive');panel.querySelector('[data-report-close]')?.addEventListener('click',()=>{filter='all';ensureFilter();void refreshPanel();});panel.querySelector('[data-report-refresh]')?.addEventListener('click',()=>{dateFrom=panel.querySelector('[data-report-from]')?.value||dateFrom;dateTo=panel.querySelector('[data-report-to]')?.value||dateTo;query=panel.querySelector('[data-report-query]')?.value||query;void refreshPanel(true);});panel.querySelector('[data-report-query]')?.addEventListener('keydown',(event)=>{if(event.key==='Enter'){event.preventDefault();panel.querySelector('[data-report-refresh]')?.click();}});panel.querySelector('[data-report-print]')?.addEventListener('click',()=>window.print());}
function closePanel(){document.getElementById(PANEL_ID)?.remove();document.body.classList.remove('bes-supplemental-report-exclusive');}
async function refreshPanel(force=false){if(!client||!activeTab){closePanel();return;}if(!dateFrom)dateFrom=dayOffset(activeTab==='report'?-365:-31);if(!dateTo)dateTo=dayOffset(0);if(!['all','remedial','enrichment','supplemental'].includes(filter))filter='all';const current=++token;loading=true;try{
 if(activeTab==='history'){
   if(filter==='supplemental'){const rows=await loadSupplementalHistory(client,{from:dateFrom,to:dateTo},query);if(current!==token)return;renderPanel(historyHtml(rows),'Lịch sử Học bổ sung');}
   else {const rows=await loadAttendanceActivities(client,{from:dateFrom,to:dateTo},filter);if(current!==token)return;renderPanel(unifiedHistoryHtml(rows),filter==='all'?'Tất cả hoạt động điểm danh':`Lịch sử ${activityLabel(filter)}`);}
 }else if(activeTab==='report'){
   if(filter==='supplemental'){const rows=await loadSupplementalStudentReport(client,{from:dateFrom,to:dateTo});if(current!==token)return;renderPanel(reportHtml(rows),'Báo cáo Học bổ sung');}
   else if(filter==='all'){const rows=await loadSupplementalStudentReport(client,{from:dateFrom,to:dateTo});if(current!==token)return;renderPanel(`<div class="bes-supplemental-combined-note"><strong>Chế độ Tất cả</strong><p>Báo cáo Phụ đạo/Bồi dưỡng hiện có phía trên vẫn giữ nguyên cách tính. Khối dưới đây là Học bổ sung và chỉ xuất hiện vì bạn đã chọn “Tất cả”; không tự cộng vào tổng cũ.</p></div>${reportHtml(rows)}`,'Tất cả báo cáo điểm danh');}
   else {closePanel();}
 }
 }catch(error){if(current!==token)return;renderPanel(`<p class="bes-supplemental-empty">${esc(error?.message||'Không thể tải dữ liệu báo cáo.')}</p>`,'Không thể tải dữ liệu');}finally{if(current===token)loading=false;void force;}}
function bindTabs(){document.querySelectorAll(TAB_SELECTOR).forEach((button)=>{if(button.dataset.besSupplementalReportingBound)return;button.dataset.besSupplementalReportingBound='true';button.addEventListener('click',()=>{const next=tabKind(button);activeTab=next;if(!next){document.getElementById(FILTER_ID)?.remove();closePanel();return;}dateFrom='';dateTo='';query='';filter='all';setTimeout(()=>ensureFilter(),0);});});const detected=detectActiveTab();if(detected)ensureFilter();}
function start(){if(observer)return;observer=new MutationObserver(bindTabs);observer.observe(document.body,{childList:true,subtree:true});bindTabs();}
async function install(){if(window[INSTALL_KEY])return;window[INSTALL_KEY]=true;try{await ensureRuntimeReady();}catch{/* runtime can recover */}runtime=getRuntimeState();client=getRuntimeClient();start();subscribeRuntime((next)=>{runtime=next||getRuntimeState();client=getRuntimeClient();if(activeTab)void refreshPanel(true);});}
if(typeof window!=='undefined'&&typeof document!=='undefined')install();
