import './styles/SupplementalLearning.css';
import { ensureRuntimeReady, getRuntimeClient, getRuntimeState, subscribeRuntime } from './services/runtime/core.js';
import { attachSupplementalProof, beginSupplementalAttendance, confirmSupplementalAttendance, loadSupplementalAttendanceActivities } from './attendance/supplementalLearningApi.js';

const INSTALL_KEY='__besSupplementalAttendanceQuickInstalled';
const DAILY_ROOT='[data-bes-supplemental-daily-scroll-root]';
const SECTION_CLASS='bes-supplemental-daily-section';
const ROLLCALL_ID='bes-supplemental-rollcall';
let client=null;let runtime=null;let observer=null;let queued=false;let requestKey='';let activities=[];let activeSession=null;let participantState=[];let busy=false;
function esc(value){return String(value??'').replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function dateForRoot(root){return String(root?.querySelector('input[type="date"]')?.value||document.querySelector('.attendance-daily-compact-toolbar input[type="date"]')?.value||new Date().toISOString().slice(0,10)).slice(0,10);}
function kindLabel(kind){return kind==='recurring'?'Nhóm dài ngày':'Phát sinh';}
function statusLabel(status){return({scheduled:'Chưa điểm danh',in_progress:'Đang điểm danh',confirmed:'Đã chốt',cancelled:'Đã hủy'})[status]||status;}
function accessError(error){const code=String(error?.message||error||'');if(code.includes('outside_time'))return'Ngoài khung Giờ GV do Admin quy định.';if(code.includes('missing_permission'))return'Tài khoản chưa được Admin cấp quyền Điểm danh nhanh.';if(code.includes('cancelled')||code.includes('đã bị hủy'))return'Buổi Học bổ sung đã bị hủy.';return code||'Không thể mở điểm danh Học bổ sung.';}
function renderSection(root){let section=root.querySelector(`.${SECTION_CLASS}`);if(!section){section=document.createElement('section');section.className=SECTION_CLASS;section.dataset.besSupplementalDaily='true';root.append(section);}section.innerHTML=`<header><div><span>HỌC BỔ SUNG</span><strong>${activities.length} buổi</strong></div><small>Nhóm dài ngày và buổi phát sinh</small></header><div class="bes-supplemental-daily-grid">${activities.length?activities.map((a)=>`<button type="button" class="bes-supplemental-daily-card" data-bes-attendance-source="supplemental" data-bes-supplemental-session-id="${esc(a.id)}" ${a.status==='cancelled'?'disabled':''}><span class="bes-supplemental-source-badge">HỌC BỔ SUNG</span><strong>${esc(a.title||a.subject)}</strong><small>${esc(a.subject)} · ${esc(a.timeRange||'')} · ${esc(a.room||'Chưa phòng')}</small><small>${esc(a.teacherName||'Chưa giáo viên')} · ${a.participantCount} học sinh</small><span class="bes-supplemental-kind">${kindLabel(a.supplementalKind)} · ${statusLabel(a.status)}</span></button>`).join(''):'<p>Không có buổi Học bổ sung trong ngày này.</p>'}</div>`;section.querySelectorAll('[data-bes-supplemental-session-id]').forEach((button)=>button.addEventListener('click',(event)=>{event.preventDefault();event.stopPropagation();void openRollcall(button.dataset.besSupplementalSessionId);}));}
async function refresh(root=document.querySelector(DAILY_ROOT),force=false){if(!root||!client)return;const date=dateForRoot(root);const key=`${runtime?.user?.id||runtime?.profile?.id||'user'}:${date}`;if(!force&&requestKey===key){if(!root.querySelector(`.${SECTION_CLASS}`))renderSection(root);return;}requestKey=key;try{activities=await loadSupplementalAttendanceActivities(client,{from:date,to:date});renderSection(root);}catch(error){activities=[];renderSection(root);const section=root.querySelector(`.${SECTION_CLASS}`);if(section)section.dataset.loadError=error?.message||'error';}}
function queueRefresh(force=false){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;const root=document.querySelector(DAILY_ROOT);if(root)void refresh(root,force);});}
function safeFileName(name='proof.jpg'){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(-120)||'proof.jpg';}
function closeRollcall(){document.getElementById(ROLLCALL_ID)?.remove();activeSession=null;participantState=[];}
function participantHtml(p,index){const absent=p.status==='absent';return `<article class="bes-supplemental-participant" data-index="${index}"><div><strong>${esc(p.fullName)}</strong><small>${esc(p.studentCode||'Không mã')} · ${esc(p.schoolClassName||'Chưa lớp')}</small></div><div class="bes-supplemental-status-buttons">${['present','tardy','absent'].map((status)=>`<button type="button" data-status="${status}" class="${p.status===status?'is-active':''}">${status==='present'?'Có mặt':status==='tardy'?'Đi trễ':'Vắng'}</button>`).join('')}</div><div class="bes-supplemental-absence ${absent?'':'is-hidden'}"><select data-field="absenceReasonCode"><option value="">Lý do vắng</option><option value="permission" ${p.absenceReasonCode==='permission'?'selected':''}>Có phép</option><option value="sick" ${p.absenceReasonCode==='sick'?'selected':''}>Ốm</option><option value="unknown" ${p.absenceReasonCode==='unknown'?'selected':''}>Không rõ lý do</option><option value="other" ${p.absenceReasonCode==='other'?'selected':''}>Khác</option></select><input data-field="absenceNote" value="${esc(p.absenceNote||'')}" placeholder="Ghi chú vắng"></div></article>`;}
function renderRollcall(message=''){let host=document.getElementById(ROLLCALL_ID);if(!host){host=document.createElement('div');host.id=ROLLCALL_ID;document.body.append(host);}const s=activeSession?.session||{};host.innerHTML=`<div class="bes-supplemental-backdrop" data-rollcall-close></div><section class="bes-supplemental-rollcall" role="dialog" aria-modal="true"><header><div><span class="bes-supplemental-source-badge">HỌC BỔ SUNG · ${kindLabel(s.kind)}</span><h2>${esc(s.title||s.subject||'Học bổ sung')}</h2><p>${esc(s.attendance_date||'')} · ${esc(s.subject||'')} · ${esc(s.teacher_name||'Chưa giáo viên')} · ${esc(s.room||'Chưa phòng')}</p></div><button type="button" data-rollcall-close aria-label="Đóng">×</button></header>${message?`<div class="bes-supplemental-rollcall-message">${esc(message)}</div>`:''}<main>${participantState.map(participantHtml).join('')||'<p class="bes-supplemental-empty">Buổi học chưa có học sinh.</p>'}</main><footer><label>Ghi chú buổi học<textarea data-session-note rows="2">${esc(s.session_note||'')}</textarea></label><label>Minh chứng hình ảnh<input type="file" data-proof accept="image/*"></label><div><button type="button" data-rollcall-close>Thoát</button><button type="button" class="is-primary" data-confirm ${busy?'disabled':''}>Chốt điểm danh</button></div></footer></section>`;bindRollcall(host);}
function bindRollcall(host){host.querySelectorAll('[data-rollcall-close]').forEach((n)=>n.addEventListener('click',closeRollcall));host.querySelectorAll('.bes-supplemental-participant').forEach((row)=>{const index=Number(row.dataset.index);row.querySelectorAll('[data-status]').forEach((button)=>button.addEventListener('click',()=>{participantState[index].status=button.dataset.status;if(button.dataset.status!=='absent'){participantState[index].absenceReasonCode='';participantState[index].absenceNote='';}renderRollcall();}));row.querySelector('[data-field="absenceReasonCode"]')?.addEventListener('change',(e)=>{participantState[index].absenceReasonCode=e.target.value;});row.querySelector('[data-field="absenceNote"]')?.addEventListener('input',(e)=>{participantState[index].absenceNote=e.target.value;});});host.querySelector('[data-confirm]')?.addEventListener('click',()=>void confirmCurrent(host));}
async function openRollcall(sessionId){if(busy||!client)return;const current=activities.find((a)=>a.id===sessionId);if(current?.status==='confirmed'){window.alert('Buổi Học bổ sung này đã chốt điểm danh. Xem tại Lịch sử.');return;}busy=true;try{activeSession=await beginSupplementalAttendance(client,sessionId);participantState=(activeSession?.participants||[]).map((p)=>({participantId:p.id,status:p.status||'present',fullName:p.fullName||p.full_name||'',studentCode:p.studentCode||p.student_code||'',schoolClassName:p.schoolClassName||p.school_class_name||'',absenceReasonCode:p.absenceReasonCode||p.absence_reason_code||'',absenceNote:p.absenceNote||p.absence_note||''}));renderRollcall();}catch(error){window.alert(accessError(error));}finally{busy=false;}}
async function confirmCurrent(host){if(!activeSession||busy)return;const missing=participantState.find((p)=>!['present','absent','tardy'].includes(p.status));if(missing){renderRollcall('Hãy chọn trạng thái cho toàn bộ học sinh.');return;}const absentWithoutReason=participantState.find((p)=>p.status==='absent'&&!p.absenceReasonCode);if(absentWithoutReason){renderRollcall(`Hãy chọn lý do vắng cho ${absentWithoutReason.fullName}.`);return;}busy=true;const note=host.querySelector('[data-session-note]')?.value||'';const file=host.querySelector('[data-proof]')?.files?.[0]||null;const sessionId=activeSession.session.id;const proofPath=file?`${sessionId}/${Date.now()}-${safeFileName(file.name)}`:'';renderRollcall('Đang chốt điểm danh trên máy chủ…');try{await confirmSupplementalAttendance(client,{sessionId,participants:participantState,sessionNote:note,proofPath:''});let proofWarning='';if(file){const {error}=await client.storage.from('attendance-session-proofs').upload(proofPath,file,{upsert:false,contentType:file.type||'image/jpeg'});if(error){proofWarning='Điểm danh đã chốt nhưng ảnh minh chứng chưa tải lên được.';}else{try{await attachSupplementalProof(client,sessionId,proofPath);}catch{proofWarning='Điểm danh và ảnh đã lưu, nhưng chưa gắn được ảnh vào lịch sử buổi học.';}}}closeRollcall();requestKey='';await refresh(document.querySelector(DAILY_ROOT),true);if(proofWarning)window.alert(proofWarning);}catch(error){renderRollcall(error?.message||'Không thể chốt điểm danh.');}finally{busy=false;}}
function start(){if(observer)return;document.addEventListener('change',(event)=>{if(event.target?.matches?.(`${DAILY_ROOT} input[type="date"], .attendance-daily-compact-toolbar input[type="date"]`)){requestKey='';queueRefresh(true);}},true);observer=new MutationObserver(()=>queueRefresh(false));observer.observe(document.body,{childList:true,subtree:true});queueRefresh(true);}
async function install(){if(window[INSTALL_KEY])return;window[INSTALL_KEY]=true;try{await ensureRuntimeReady();}catch{/* runtime can recover */}runtime=getRuntimeState();client=getRuntimeClient();start();subscribeRuntime((next)=>{runtime=next||getRuntimeState();client=getRuntimeClient();requestKey='';queueRefresh(true);});}
if(typeof window!=='undefined'&&typeof document!=='undefined')install();
