-- Brian English Studio: weekly English practice v1
-- Public students can list and download published HTML exercises without signing in.
-- Department publishers manage content. Results are optional and insert-only for guests.

create extension if not exists pgcrypto;

create table if not exists public.weekly_practice_items (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 180),
  description text not null default '',
  week_key text not null check (char_length(week_key) between 1 and 32),
  school_year text not null default '',
  grade text not null default 'Tất cả',
  category text not null default 'Tổng hợp',
  cefr text not null default '',
  question_count integer not null default 0 check (question_count >= 0 and question_count <= 1000),
  duration_minutes integer not null default 0 check (duration_minutes >= 0 and duration_minutes <= 1440),
  opens_at timestamptz not null default now(),
  closes_at timestamptz,
  status text not null default 'draft' check (status in ('draft', 'published', 'maintenance', 'archived')),
  allow_retake boolean not null default true,
  max_attempts integer check (max_attempts is null or max_attempts between 1 and 100),
  collect_results boolean not null default false,
  show_answers boolean not null default true,
  storage_bucket text not null default 'weekly-practice',
  storage_path text not null unique,
  file_name text not null default '',
  file_size bigint not null default 0 check (file_size >= 0 and file_size <= 10485760),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  is_featured boolean not null default false,
  constraint weekly_practice_dates_valid check (closes_at is null or closes_at > opens_at)
);

create index if not exists weekly_practice_items_public_idx
  on public.weekly_practice_items (status, is_featured desc, opens_at desc);
create index if not exists weekly_practice_items_week_idx
  on public.weekly_practice_items (week_key, school_year);

create table if not exists public.weekly_practice_events (
  id bigint generated by default as identity primary key,
  practice_id uuid not null references public.weekly_practice_items(id) on delete cascade,
  event_type text not null check (event_type in ('open', 'complete', 'error')),
  device_id text not null check (char_length(device_id) between 1 and 128),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists weekly_practice_events_lookup_idx
  on public.weekly_practice_events (practice_id, event_type, created_at desc);

create table if not exists public.weekly_practice_results (
  id bigint generated by default as identity primary key,
  practice_id uuid not null references public.weekly_practice_items(id) on delete cascade,
  device_id text not null check (char_length(device_id) between 1 and 128),
  student_name text not null check (char_length(student_name) between 1 and 120),
  class_code text not null check (char_length(class_code) between 1 and 80),
  student_code text not null default '' check (char_length(student_code) <= 80),
  score numeric,
  max_score numeric,
  correct_count integer check (correct_count is null or correct_count >= 0),
  question_count integer check (question_count is null or question_count >= 0),
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  answers jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint weekly_practice_score_valid check (
    score is null or max_score is null or (score >= 0 and max_score >= 0 and score <= max_score)
  ),
  constraint weekly_practice_answers_object check (jsonb_typeof(answers) = 'object'),
  constraint weekly_practice_result_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create index if not exists weekly_practice_results_lookup_idx
  on public.weekly_practice_results (practice_id, class_code, created_at desc);

create or replace function public.set_weekly_practice_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists weekly_practice_items_updated_at on public.weekly_practice_items;
create trigger weekly_practice_items_updated_at
before update on public.weekly_practice_items
for each row execute function public.set_weekly_practice_updated_at();

alter table public.weekly_practice_items enable row level security;
alter table public.weekly_practice_events enable row level security;
alter table public.weekly_practice_results enable row level security;

-- Anyone can see metadata for published exercises, including future and expired weeks.
drop policy if exists "Public can read published weekly practice" on public.weekly_practice_items;
create policy "Public can read published weekly practice"
on public.weekly_practice_items
for select
to anon, authenticated
using (status = 'published');

-- Admin/TTCM publishers can manage all states.
drop policy if exists "Publishers can read all weekly practice" on public.weekly_practice_items;
create policy "Publishers can read all weekly practice"
on public.weekly_practice_items
for select
to authenticated
using (public.can_publish_department());

drop policy if exists "Publishers can insert weekly practice" on public.weekly_practice_items;
create policy "Publishers can insert weekly practice"
on public.weekly_practice_items
for insert
to authenticated
with check (public.can_publish_department() and created_by = auth.uid());

drop policy if exists "Publishers can update weekly practice" on public.weekly_practice_items;
create policy "Publishers can update weekly practice"
on public.weekly_practice_items
for update
to authenticated
using (public.can_publish_department())
with check (public.can_publish_department());

drop policy if exists "Publishers can delete weekly practice" on public.weekly_practice_items;
create policy "Publishers can delete weekly practice"
on public.weekly_practice_items
for delete
to authenticated
using (public.can_publish_department());

-- Anonymous event inserts are deliberately narrow and contain no account token or IP address.
drop policy if exists "Public can record weekly practice events" on public.weekly_practice_events;
create policy "Public can record weekly practice events"
on public.weekly_practice_events
for insert
to anon, authenticated
with check (
  exists (
    select 1 from public.weekly_practice_items item
    where item.id = practice_id and item.status = 'published'
  )
);

drop policy if exists "Publishers can read weekly practice events" on public.weekly_practice_events;
create policy "Publishers can read weekly practice events"
on public.weekly_practice_events
for select
to authenticated
using (public.can_publish_department());

-- Results can only be inserted for a published exercise that explicitly collects results.
drop policy if exists "Public can submit enabled weekly practice results" on public.weekly_practice_results;
create policy "Public can submit enabled weekly practice results"
on public.weekly_practice_results
for insert
to anon, authenticated
with check (
  exists (
    select 1 from public.weekly_practice_items item
    where item.id = practice_id
      and item.status = 'published'
      and item.collect_results = true
  )
);

drop policy if exists "Publishers can read weekly practice results" on public.weekly_practice_results;
create policy "Publishers can read weekly practice results"
on public.weekly_practice_results
for select
to authenticated
using (public.can_publish_department());

drop policy if exists "Publishers can delete weekly practice results" on public.weekly_practice_results;
create policy "Publishers can delete weekly practice results"
on public.weekly_practice_results
for delete
to authenticated
using (public.can_publish_department());

grant select on public.weekly_practice_items to anon, authenticated;
grant insert on public.weekly_practice_events to anon, authenticated;
grant insert on public.weekly_practice_results to anon, authenticated;
grant select, insert, update, delete on public.weekly_practice_items to authenticated;
grant select, delete on public.weekly_practice_events to authenticated;
grant select, delete on public.weekly_practice_results to authenticated;
grant usage, select on sequence public.weekly_practice_events_id_seq to anon, authenticated;
grant usage, select on sequence public.weekly_practice_results_id_seq to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'weekly-practice',
  'weekly-practice',
  false,
  10485760,
  array['text/html', 'application/xhtml+xml']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Storage remains private. Public download is granted only when a matching published row exists.
drop policy if exists "Public can download published weekly practice HTML" on storage.objects;
create policy "Public can download published weekly practice HTML"
on storage.objects
for select
to anon, authenticated
using (
  bucket_id = 'weekly-practice'
  and exists (
    select 1 from public.weekly_practice_items item
    where item.storage_bucket = bucket_id
      and item.storage_path = name
      and item.status = 'published'
  )
);

drop policy if exists "Publishers can upload weekly practice HTML" on storage.objects;
create policy "Publishers can upload weekly practice HTML"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'weekly-practice' and public.can_publish_department());

drop policy if exists "Publishers can update weekly practice HTML" on storage.objects;
create policy "Publishers can update weekly practice HTML"
on storage.objects
for update
to authenticated
using (bucket_id = 'weekly-practice' and public.can_publish_department())
with check (bucket_id = 'weekly-practice' and public.can_publish_department());

drop policy if exists "Publishers can delete weekly practice HTML" on storage.objects;
create policy "Publishers can delete weekly practice HTML"
on storage.objects
for delete
to authenticated
using (bucket_id = 'weekly-practice' and public.can_publish_department());

comment on table public.weekly_practice_items is
  'Weekly interactive HTML exercises shown publicly on the Brian homepage.';
comment on table public.weekly_practice_results is
  'Optional guest submissions. Student identity is collected only for exercises with collect_results enabled.';
