-- Professional Hub RLS and workflow hardening
-- Phase 2.1B: review-only migration.
-- Do not apply to Production before explicit approval and account-level testing.

begin;

-- ---------------------------------------------------------------------------
-- 1. Audit log
-- ---------------------------------------------------------------------------

create table if not exists public.professional_hub_audit_log (
  id bigint generated by default as identity primary key,
  hub_id uuid not null
    references public.professional_hubs(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  old_state jsonb,
  new_state jsonb,
  created_at timestamptz not null default now()
);

create index if not exists professional_hub_audit_log_hub_created_idx
  on public.professional_hub_audit_log(hub_id, created_at desc);

alter table public.professional_hub_audit_log
  enable row level security;

drop policy if exists professional_hub_audit_log_select_leader
  on public.professional_hub_audit_log;

create policy professional_hub_audit_log_select_leader
on public.professional_hub_audit_log
for select
to authenticated
using (
  public.has_professional_hub_role(hub_id, array['leader'])
);

revoke insert, update, delete
  on public.professional_hub_audit_log
  from authenticated;

create or replace function public.professional_hub_write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  source_row jsonb;
  target_row jsonb;
  target_hub_id uuid;
  target_entity_id uuid;
begin
  source_row := case
    when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old)
    else null
  end;

  target_row := case
    when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new)
    else null
  end;

  target_hub_id := coalesce(
    (target_row ->> 'hub_id')::uuid,
    (source_row ->> 'hub_id')::uuid
  );

  target_entity_id := coalesce(
    nullif(target_row ->> 'id', '')::uuid,
    nullif(source_row ->> 'id', '')::uuid
  );

  insert into public.professional_hub_audit_log (
    hub_id,
    actor_id,
    action,
    entity_type,
    entity_id,
    old_state,
    new_state
  )
  values (
    target_hub_id,
    auth.uid(),
    lower(tg_op),
    tg_table_name,
    target_entity_id,
    source_row,
    target_row
  );

  return coalesce(new, old);
end;
$$;

revoke all
  on function public.professional_hub_write_audit_log()
  from public;

-- ---------------------------------------------------------------------------
-- 2. Reusable active-membership assertion
-- ---------------------------------------------------------------------------

create or replace function public.assert_professional_hub_active_member(
  target_hub_id uuid,
  target_user_id uuid,
  field_name text default 'user'
)
returns void
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if target_user_id is null then
    return;
  end if;

  if not exists (
    select 1
    from public.professional_hub_members membership
    where membership.hub_id = target_hub_id
      and membership.user_id = target_user_id
      and membership.membership_status = 'active'
  ) then
    raise exception '% must be an active member of the Professional Hub',
      field_name
      using errcode = '23514';
  end if;
end;
$$;

revoke all
  on function public.assert_professional_hub_active_member(uuid, uuid, text)
  from public;

grant execute
  on function public.assert_professional_hub_active_member(uuid, uuid, text)
  to authenticated;

-- ---------------------------------------------------------------------------
-- 3. Membership protection
-- ---------------------------------------------------------------------------

create or replace function public.professional_hub_guard_membership()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  remaining_leaders integer;
begin
  if tg_op = 'UPDATE' then
    if new.hub_id is distinct from old.hub_id
      or new.user_id is distinct from old.user_id
    then
      raise exception 'Membership identity cannot be changed'
        using errcode = '23514';
    end if;
  end if;

  if old.role = 'leader'
    and old.membership_status = 'active'
    and (
      tg_op = 'DELETE'
      or new.role is distinct from 'leader'
      or new.membership_status is distinct from 'active'
    )
  then
    select count(*)
    into remaining_leaders
    from public.professional_hub_members membership
    where membership.hub_id = old.hub_id
      and membership.user_id <> old.user_id
      and membership.role = 'leader'
      and membership.membership_status = 'active';

    if remaining_leaders = 0 then
      raise exception 'A Professional Hub must retain at least one active leader'
        using errcode = '23514';
    end if;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists professional_hub_members_guard
  on public.professional_hub_members;

create trigger professional_hub_members_guard
before update or delete
on public.professional_hub_members
for each row
execute function public.professional_hub_guard_membership();

-- Physical deletion is disabled for normal Hub users.
drop policy if exists professional_hub_members_delete_leader
  on public.professional_hub_members;

-- ---------------------------------------------------------------------------
-- 4. Cross-Hub ownership validation
-- ---------------------------------------------------------------------------

create or replace function public.professional_hub_validate_member_links()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if tg_table_name = 'professional_hub_task_assignees' then
    perform public.assert_professional_hub_active_member(
      new.hub_id,
      new.user_id,
      'assignee'
    );
  elsif tg_table_name = 'professional_hub_plans' then
    perform public.assert_professional_hub_active_member(
      new.hub_id,
      new.owner_id,
      'plan owner'
    );
  elsif tg_table_name = 'professional_hub_records' then
    perform public.assert_professional_hub_active_member(
      new.hub_id,
      new.owner_id,
      'record owner'
    );
  elsif tg_table_name = 'professional_hub_evidence' then
    perform public.assert_professional_hub_active_member(
      new.hub_id,
      new.owner_id,
      'evidence owner'
    );
  elsif tg_table_name = 'professional_hub_notifications' then
    perform public.assert_professional_hub_active_member(
      new.hub_id,
      new.recipient_id,
      'notification recipient'
    );
  elsif tg_table_name = 'professional_hub_meetings' then
    perform public.assert_professional_hub_active_member(
      new.hub_id,
      new.chair_id,
      'meeting chair'
    );
    perform public.assert_professional_hub_active_member(
      new.hub_id,
      new.secretary_id,
      'meeting secretary'
    );
  end if;

  return new;
end;
$$;

drop trigger if exists professional_hub_task_assignees_member_link
  on public.professional_hub_task_assignees;
create trigger professional_hub_task_assignees_member_link
before insert or update of hub_id, user_id
on public.professional_hub_task_assignees
for each row
execute function public.professional_hub_validate_member_links();

drop trigger if exists professional_hub_plans_member_link
  on public.professional_hub_plans;
create trigger professional_hub_plans_member_link
before insert or update of hub_id, owner_id
on public.professional_hub_plans
for each row
execute function public.professional_hub_validate_member_links();

drop trigger if exists professional_hub_records_member_link
  on public.professional_hub_records;
create trigger professional_hub_records_member_link
before insert or update of hub_id, owner_id
on public.professional_hub_records
for each row
execute function public.professional_hub_validate_member_links();

drop trigger if exists professional_hub_evidence_member_link
  on public.professional_hub_evidence;
create trigger professional_hub_evidence_member_link
before insert or update of hub_id, owner_id
on public.professional_hub_evidence
for each row
execute function public.professional_hub_validate_member_links();

drop trigger if exists professional_hub_notifications_member_link
  on public.professional_hub_notifications;
create trigger professional_hub_notifications_member_link
before insert or update of hub_id, recipient_id
on public.professional_hub_notifications
for each row
execute function public.professional_hub_validate_member_links();

drop trigger if exists professional_hub_meetings_member_link
  on public.professional_hub_meetings;
create trigger professional_hub_meetings_member_link
before insert or update of hub_id, chair_id, secretary_id
on public.professional_hub_meetings
for each row
execute function public.professional_hub_validate_member_links();

-- ---------------------------------------------------------------------------
-- 5. Teacher visibility: own data only; leader sees all within the Hub
-- ---------------------------------------------------------------------------

drop policy if exists professional_hub_task_assignees_select_member
  on public.professional_hub_task_assignees;

create policy professional_hub_task_assignees_select_self_or_leader
on public.professional_hub_task_assignees
for select
to authenticated
using (
  user_id = auth.uid()
  or public.has_professional_hub_role(hub_id, array['leader'])
);

drop policy if exists professional_hub_plans_select_member
  on public.professional_hub_plans;

create policy professional_hub_plans_select_owner_or_leader
on public.professional_hub_plans
for select
to authenticated
using (
  owner_id = auth.uid()
  or public.has_professional_hub_role(hub_id, array['leader'])
);

drop policy if exists professional_hub_records_select_member
  on public.professional_hub_records;

create policy professional_hub_records_select_owner_or_leader
on public.professional_hub_records
for select
to authenticated
using (
  owner_id = auth.uid()
  or public.has_professional_hub_role(hub_id, array['leader'])
);

drop policy if exists professional_hub_evidence_select_member
  on public.professional_hub_evidence;

create policy professional_hub_evidence_select_owner_or_leader
on public.professional_hub_evidence
for select
to authenticated
using (
  owner_id = auth.uid()
  or public.has_professional_hub_role(hub_id, array['leader'])
);

-- Plans, records and evidence use archive/status transitions instead of
-- destructive client-side deletion.
drop policy if exists professional_hub_plans_delete_owner_or_leader
  on public.professional_hub_plans;

drop policy if exists professional_hub_records_delete_owner_or_leader
  on public.professional_hub_records;

drop policy if exists professional_hub_evidence_delete_owner_or_leader
  on public.professional_hub_evidence;

-- ---------------------------------------------------------------------------
-- 6. Assignment workflow guard
-- ---------------------------------------------------------------------------

create or replace function public.professional_hub_guard_task_assignee_update()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  caller_id uuid := auth.uid();
  caller_is_leader boolean;
begin
  if new.task_id is distinct from old.task_id
    or new.hub_id is distinct from old.hub_id
    or new.user_id is distinct from old.user_id
  then
    raise exception 'Task assignment identity cannot be changed'
      using errcode = '23514';
  end if;

  if caller_id is null then
    return new;
  end if;

  caller_is_leader := public.has_professional_hub_role(
    old.hub_id,
    array['leader']
  );

  if caller_is_leader then
    if new.status = 'completed' then
      new.completed_at := coalesce(new.completed_at, now());
      new.progress := 100;
    elsif new.status <> 'completed' then
      new.completed_at := null;
    end if;

    return new;
  end if;

  if caller_id <> old.user_id then
    raise exception 'Teachers may update only their own assignments'
      using errcode = '42501';
  end if;

  if (
    to_jsonb(new)
      - array[
          'status',
          'progress',
          'note',
          'submitted_at',
          'updated_at'
        ]
  ) is distinct from (
    to_jsonb(old)
      - array[
          'status',
          'progress',
          'note',
          'submitted_at',
          'updated_at'
        ]
  ) then
    raise exception 'Teachers may update only progress, note and submission state'
      using errcode = '42501';
  end if;

  if not (
    (old.status = 'assigned'
      and new.status in ('assigned', 'in_progress', 'submitted'))
    or
    (old.status = 'in_progress'
      and new.status in ('in_progress', 'submitted'))
    or
    (old.status = 'returned'
      and new.status in ('returned', 'in_progress', 'submitted'))
    or
    (old.status = 'submitted'
      and new.status = 'submitted')
    or
    (old.status = 'completed'
      and new.status = 'completed')
  ) then
    raise exception 'Invalid teacher task-status transition: % -> %',
      old.status,
      new.status
      using errcode = '23514';
  end if;

  if new.status = 'submitted' then
    new.submitted_at := coalesce(new.submitted_at, now());
  end if;

  new.completed_at := old.completed_at;

  return new;
end;
$$;

drop trigger if exists professional_hub_task_assignees_update_guard
  on public.professional_hub_task_assignees;

create trigger professional_hub_task_assignees_update_guard
before update
on public.professional_hub_task_assignees
for each row
execute function public.professional_hub_guard_task_assignee_update();

-- ---------------------------------------------------------------------------
-- 7. Review workflow guards
-- ---------------------------------------------------------------------------

alter table public.professional_hub_plans
  add column if not exists review_note text;

create or replace function public.professional_hub_guard_reviewable_update()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  caller_id uuid := auth.uid();
  caller_is_owner boolean;
  caller_is_leader boolean;
  allowed boolean := false;
begin
  if new.hub_id is distinct from old.hub_id
    or new.owner_id is distinct from old.owner_id
  then
    raise exception 'Reviewable item identity cannot be changed'
      using errcode = '23514';
  end if;

  if caller_id is null then
    return new;
  end if;

  caller_is_owner := caller_id = old.owner_id;
  caller_is_leader := public.has_professional_hub_role(
    old.hub_id,
    array['leader']
  );

  -- The owner path is checked first to prevent a leader approving
  -- an item that they personally own.
  if caller_is_owner then
    if old.status not in ('draft', 'needs_revision') then
      raise exception 'Owner cannot modify an item after submission'
        using errcode = '42501';
    end if;

    allowed := (
      new.status = old.status
      or new.status = 'submitted'
    );

    if not allowed then
      raise exception 'Owner may only save or submit the item'
        using errcode = '23514';
    end if;

    if tg_table_name = 'professional_hub_plans' then
      new.reviewer_id := old.reviewer_id;
      new.approved_at := old.approved_at;
      new.review_note := old.review_note;
    elsif tg_table_name = 'professional_hub_records' then
      new.reviewer_id := old.reviewer_id;
      new.reviewed_at := old.reviewed_at;
      new.feedback := old.feedback;
    elsif tg_table_name = 'professional_hub_evidence' then
      new.verified_by := old.verified_by;
      new.verified_at := old.verified_at;
    end if;

    if new.status = 'submitted'
      and tg_table_name = 'professional_hub_records'
    then
      new.submitted_at := coalesce(new.submitted_at, now());
    end if;

    return new;
  end if;

  if not caller_is_leader then
    raise exception 'Only the owner or Hub leader may update this item'
      using errcode = '42501';
  end if;

  if old.status <> 'submitted' then
    raise exception 'Leader may review only submitted items'
      using errcode = '23514';
  end if;

  if tg_table_name = 'professional_hub_evidence' then
    if new.status not in ('verified', 'rejected') then
      raise exception 'Evidence review must end as verified or rejected'
        using errcode = '23514';
    end if;

    new.verified_by := caller_id;
    new.verified_at := now();
  else
    if new.status not in ('approved', 'needs_revision') then
      raise exception 'Review must end as approved or needs_revision'
        using errcode = '23514';
    end if;

    new.reviewer_id := caller_id;

    if tg_table_name = 'professional_hub_plans' then
      new.approved_at := case
        when new.status = 'approved' then now()
        else null
      end;
    elsif tg_table_name = 'professional_hub_records' then
      new.reviewed_at := now();
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists professional_hub_plans_review_guard
  on public.professional_hub_plans;
create trigger professional_hub_plans_review_guard
before update
on public.professional_hub_plans
for each row
execute function public.professional_hub_guard_reviewable_update();

drop trigger if exists professional_hub_records_review_guard
  on public.professional_hub_records;
create trigger professional_hub_records_review_guard
before update
on public.professional_hub_records
for each row
execute function public.professional_hub_guard_reviewable_update();

drop trigger if exists professional_hub_evidence_review_guard
  on public.professional_hub_evidence;
create trigger professional_hub_evidence_review_guard
before update
on public.professional_hub_evidence
for each row
execute function public.professional_hub_guard_reviewable_update();

-- ---------------------------------------------------------------------------
-- 8. Notification update guard: recipient may change read_at only
-- ---------------------------------------------------------------------------

create or replace function public.professional_hub_guard_notification_update()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then
    return new;
  end if;

  if auth.uid() <> old.recipient_id then
    raise exception 'Only the recipient may update a notification'
      using errcode = '42501';
  end if;

  if (
    to_jsonb(new) - array['read_at']
  ) is distinct from (
    to_jsonb(old) - array['read_at']
  ) then
    raise exception 'Notification recipients may update read_at only'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

drop trigger if exists professional_hub_notifications_update_guard
  on public.professional_hub_notifications;

create trigger professional_hub_notifications_update_guard
before update
on public.professional_hub_notifications
for each row
execute function public.professional_hub_guard_notification_update();

-- ---------------------------------------------------------------------------
-- 9. Immutable task identity
-- ---------------------------------------------------------------------------

create or replace function public.professional_hub_guard_task_identity()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if new.hub_id is distinct from old.hub_id
    or new.created_by is distinct from old.created_by
  then
    raise exception 'Task hub and creator cannot be changed'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists professional_hub_tasks_identity_guard
  on public.professional_hub_tasks;

create trigger professional_hub_tasks_identity_guard
before update
on public.professional_hub_tasks
for each row
execute function public.professional_hub_guard_task_identity();

-- ---------------------------------------------------------------------------
-- 10. Audit triggers for meaningful business entities
-- ---------------------------------------------------------------------------

drop trigger if exists professional_hub_members_audit
  on public.professional_hub_members;
create trigger professional_hub_members_audit
after insert or update or delete
on public.professional_hub_members
for each row
execute function public.professional_hub_write_audit_log();

drop trigger if exists professional_hub_tasks_audit
  on public.professional_hub_tasks;
create trigger professional_hub_tasks_audit
after insert or update or delete
on public.professional_hub_tasks
for each row
execute function public.professional_hub_write_audit_log();

drop trigger if exists professional_hub_task_assignees_audit
  on public.professional_hub_task_assignees;
create trigger professional_hub_task_assignees_audit
after insert or update or delete
on public.professional_hub_task_assignees
for each row
execute function public.professional_hub_write_audit_log();

drop trigger if exists professional_hub_plans_audit
  on public.professional_hub_plans;
create trigger professional_hub_plans_audit
after insert or update or delete
on public.professional_hub_plans
for each row
execute function public.professional_hub_write_audit_log();

drop trigger if exists professional_hub_records_audit
  on public.professional_hub_records;
create trigger professional_hub_records_audit
after insert or update or delete
on public.professional_hub_records
for each row
execute function public.professional_hub_write_audit_log();

drop trigger if exists professional_hub_meetings_audit
  on public.professional_hub_meetings;
create trigger professional_hub_meetings_audit
after insert or update or delete
on public.professional_hub_meetings
for each row
execute function public.professional_hub_write_audit_log();

drop trigger if exists professional_hub_evidence_audit
  on public.professional_hub_evidence;
create trigger professional_hub_evidence_audit
after insert or update or delete
on public.professional_hub_evidence
for each row
execute function public.professional_hub_write_audit_log();

comment on table public.professional_hub_audit_log is
  'Immutable business-event history for the native Brian Professional Hub.';

comment on function public.professional_hub_guard_reviewable_update() is
  'Prevents self-approval and enforces owner-submit / leader-review transitions.';

commit;
