-- 2026-09-09: allow safe corrections after an attendance session is confirmed.
-- Ordinary teachers may edit only the session they personally confirmed and only
-- through checked_at + 30 minutes. Admin and attendance:report users bypass the
-- 30-minute expiry. This grace period is intentionally independent from the
-- Admin-configured global teacher_start_time / teacher_end_time window.

create schema if not exists private;

create table if not exists public.bes_extra_attendance_record_changes (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.bes_extra_attendance_sessions(id) on delete cascade,
  record_id uuid references public.bes_extra_attendance_records(id) on delete cascade,
  class_id uuid not null references public.bes_extra_classes(id) on delete cascade,
  member_key text not null default '',
  student_full_name text not null default '',
  change_kind text not null default 'record' check (change_kind in ('record', 'session_note')),
  changed_by uuid references public.profiles(id) on delete set null,
  changed_by_name text not null default '',
  changed_at timestamptz not null default clock_timestamp(),
  old_status text not null default '',
  new_status text not null default '',
  old_absence_reason_code text not null default '',
  new_absence_reason_code text not null default '',
  old_absence_note text not null default '',
  new_absence_note text not null default '',
  session_note_before text not null default '',
  session_note_after text not null default ''
);

create index if not exists bes_extra_attendance_record_changes_session_idx
  on public.bes_extra_attendance_record_changes (session_id, changed_at desc);
create index if not exists bes_extra_attendance_record_changes_record_idx
  on public.bes_extra_attendance_record_changes (record_id, changed_at desc)
  where record_id is not null;

alter table public.bes_extra_attendance_record_changes enable row level security;
revoke all on table public.bes_extra_attendance_record_changes from anon, authenticated;

drop policy if exists "Attendance readers view post-confirm changes" on public.bes_extra_attendance_record_changes;
create policy "Attendance readers view post-confirm changes"
  on public.bes_extra_attendance_record_changes
  for select
  to authenticated
  using (public.can_read_extra_class_attendance());

grant select on public.bes_extra_attendance_record_changes to authenticated;

create or replace function private.bes_extra_attendance_edit_decision(
  p_session_id uuid,
  p_now timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_session public.bes_extra_attendance_sessions%rowtype;
  v_now timestamptz := coalesce(p_now, clock_timestamp());
  v_expires_at timestamptz;
  v_is_admin boolean := false;
  v_has_report boolean := false;
  v_remaining_seconds integer := 0;
begin
  if v_uid is null then
    return jsonb_build_object('allowed', false, 'reason', 'not_authenticated');
  end if;

  select * into v_profile
  from public.profiles p
  where p.id = v_uid
    and p.approved = true;

  if not found then
    return jsonb_build_object('allowed', false, 'reason', 'profile_not_approved');
  end if;

  select * into v_session
  from public.bes_extra_attendance_sessions s
  where s.id = p_session_id;

  if not found then
    return jsonb_build_object('allowed', false, 'reason', 'session_not_found');
  end if;

  if v_session.session_status <> 'completed' then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'not_completed',
      'session_id', v_session.id,
      'server_now', v_now
    );
  end if;

  if v_session.checked_at is null then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'invalid_checked_at',
      'session_id', v_session.id,
      'server_now', v_now
    );
  end if;

  v_expires_at := v_session.checked_at + interval '30 minutes';
  v_remaining_seconds := greatest(0, floor(extract(epoch from (v_expires_at - v_now)))::integer);
  v_is_admin := lower(coalesce(v_profile.role, '')) in ('admin', 'administrator');
  v_has_report := coalesce(v_profile.permissions -> 'allowed', '[]'::jsonb) ? 'attendance:report';

  if v_is_admin then
    return jsonb_build_object(
      'allowed', true,
      'reason', 'admin_bypass',
      'bypass', true,
      'session_id', v_session.id,
      'checked_at', v_session.checked_at,
      'expires_at', v_expires_at,
      'remaining_seconds', v_remaining_seconds,
      'server_now', v_now
    );
  end if;

  if v_has_report then
    return jsonb_build_object(
      'allowed', true,
      'reason', 'report_bypass',
      'bypass', true,
      'session_id', v_session.id,
      'checked_at', v_session.checked_at,
      'expires_at', v_expires_at,
      'remaining_seconds', v_remaining_seconds,
      'server_now', v_now
    );
  end if;

  if not public.can_take_extra_class_attendance() then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'missing_permission',
      'session_id', v_session.id,
      'expires_at', v_expires_at,
      'remaining_seconds', v_remaining_seconds,
      'server_now', v_now
    );
  end if;

  if v_session.checked_by is distinct from v_uid then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'not_session_teacher',
      'session_id', v_session.id,
      'expires_at', v_expires_at,
      'remaining_seconds', v_remaining_seconds,
      'server_now', v_now
    );
  end if;

  if v_now > v_expires_at then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'edit_window_expired',
      'session_id', v_session.id,
      'checked_at', v_session.checked_at,
      'expires_at', v_expires_at,
      'remaining_seconds', 0,
      'server_now', v_now
    );
  end if;

  return jsonb_build_object(
    'allowed', true,
    'reason', 'within_edit_window',
    'bypass', false,
    'session_id', v_session.id,
    'checked_at', v_session.checked_at,
    'expires_at', v_expires_at,
    'remaining_seconds', v_remaining_seconds,
    'server_now', v_now
  );
end;
$$;

create or replace function public.bes_get_extra_attendance_edit_access(
  p_session_id uuid
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.bes_extra_attendance_edit_decision(p_session_id, clock_timestamp());
$$;

create or replace function public.bes_update_extra_attendance_session(
  p_session_id uuid,
  p_records jsonb,
  p_note text default ''
)
returns public.bes_extra_attendance_sessions
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_session public.bes_extra_attendance_sessions%rowtype;
  v_decision jsonb;
  v_records jsonb := coalesce(p_records, '[]'::jsonb);
  v_record public.bes_extra_attendance_records%rowtype;
  v_item record;
  v_input_count integer := 0;
  v_distinct_count integer := 0;
  v_actual_count integer := 0;
  v_unknown_count integer := 0;
  v_present integer := 0;
  v_absent integer := 0;
  v_new_status text;
  v_new_reason text;
  v_new_note text;
  v_session_note_before text := '';
  v_session_note_after text := trim(coalesce(p_note, ''));
  v_changed_at timestamptz := clock_timestamp();
begin
  v_decision := private.bes_extra_attendance_edit_decision(p_session_id, v_changed_at);
  if not coalesce((v_decision ->> 'allowed')::boolean, false) then
    case coalesce(v_decision ->> 'reason', '')
      when 'edit_window_expired' then
        raise exception 'Đã hết 30 phút điều chỉnh kể từ lúc chốt điểm danh.' using errcode = '42501';
      when 'not_session_teacher' then
        raise exception 'Chỉ giáo viên đã chốt buổi điểm danh này mới được điều chỉnh.' using errcode = '42501';
      when 'missing_permission' then
        raise exception 'Bạn không có quyền Điểm danh nhanh.' using errcode = '42501';
      when 'not_completed' then
        raise exception 'Chỉ buổi đã điểm danh mới có thể điều chỉnh.' using errcode = '22023';
      else
        raise exception 'Bạn không có quyền điều chỉnh buổi điểm danh này.' using errcode = '42501';
    end case;
  end if;

  select * into v_profile
  from public.profiles p
  where p.id = v_uid
    and p.approved = true;

  if not found then
    raise exception 'Tài khoản chưa được duyệt.' using errcode = '42501';
  end if;

  select * into v_session
  from public.bes_extra_attendance_sessions s
  where s.id = p_session_id
  for update;

  if not found then
    raise exception 'Không tìm thấy buổi điểm danh.' using errcode = 'P0002';
  end if;

  if jsonb_typeof(v_records) <> 'array' then
    raise exception 'Danh sách điều chỉnh không hợp lệ.' using errcode = '22023';
  end if;

  select count(*)::integer into v_actual_count
  from public.bes_extra_attendance_records r
  where r.session_id = p_session_id;

  select count(*)::integer,
         count(distinct x.record_id)::integer
    into v_input_count, v_distinct_count
  from jsonb_to_recordset(v_records) as x(
    record_id uuid,
    status text,
    reason_code text,
    note text
  );

  if v_input_count <> v_actual_count or v_input_count <> v_distinct_count then
    raise exception 'Danh sách điều chỉnh phải chứa đúng một trạng thái cho mỗi học sinh của buổi học.' using errcode = '22023';
  end if;

  select count(*)::integer into v_unknown_count
  from jsonb_to_recordset(v_records) as x(record_id uuid, status text, reason_code text, note text)
  where x.record_id is null
     or not exists (
       select 1
       from public.bes_extra_attendance_records r
       where r.id = x.record_id
         and r.session_id = p_session_id
     );

  if v_unknown_count > 0 then
    raise exception 'Danh sách điều chỉnh có học sinh không thuộc buổi điểm danh này.' using errcode = '22023';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(v_records) as x(record_id uuid, status text, reason_code text, note text)
    where trim(coalesce(x.status, '')) not in ('present', 'absent')
       or (
         trim(coalesce(x.status, '')) = 'absent'
         and trim(coalesce(x.reason_code, '')) not in ('excused', 'unexcused', 'sick', 'family', 'other', 'unspecified')
       )
       or (
         trim(coalesce(x.status, '')) = 'absent'
         and trim(coalesce(x.reason_code, '')) = 'other'
         and trim(coalesce(x.note, '')) = ''
       )
  ) then
    raise exception 'Trạng thái hoặc lý do vắng không hợp lệ; lý do Khác phải có ghi chú.' using errcode = '22023';
  end if;

  v_session_note_before := coalesce(v_session.note, '');

  for v_item in
    select *
    from jsonb_to_recordset(v_records) as x(record_id uuid, status text, reason_code text, note text)
  loop
    select * into v_record
    from public.bes_extra_attendance_records r
    where r.id = v_item.record_id
      and r.session_id = p_session_id
    for update;

    v_new_status := trim(coalesce(v_item.status, ''));
    if v_new_status = 'present' then
      v_new_reason := '';
      v_new_note := '';
    else
      v_new_reason := trim(coalesce(v_item.reason_code, ''));
      v_new_note := trim(coalesce(v_item.note, ''));
    end if;

    if v_record.status is distinct from v_new_status
       or coalesce(v_record.absence_reason_code, '') is distinct from v_new_reason
       or coalesce(v_record.absence_note, '') is distinct from v_new_note then
      insert into public.bes_extra_attendance_record_changes (
        session_id, record_id, class_id, member_key, student_full_name,
        change_kind, changed_by, changed_by_name, changed_at,
        old_status, new_status,
        old_absence_reason_code, new_absence_reason_code,
        old_absence_note, new_absence_note,
        session_note_before, session_note_after
      ) values (
        v_session.id, v_record.id, v_session.class_id, v_record.member_key, v_record.student_full_name,
        'record', v_uid, coalesce(v_profile.full_name, v_profile.email, ''), v_changed_at,
        v_record.status, v_new_status,
        coalesce(v_record.absence_reason_code, ''), v_new_reason,
        coalesce(v_record.absence_note, ''), v_new_note,
        v_session_note_before, v_session_note_after
      );

      update public.bes_extra_attendance_records
      set status = v_new_status,
          absence_reason_code = v_new_reason,
          absence_note = v_new_note
      where id = v_record.id;
    end if;
  end loop;

  if v_session_note_before is distinct from v_session_note_after then
    insert into public.bes_extra_attendance_record_changes (
      session_id, record_id, class_id, member_key, student_full_name,
      change_kind, changed_by, changed_by_name, changed_at,
      old_status, new_status,
      old_absence_reason_code, new_absence_reason_code,
      old_absence_note, new_absence_note,
      session_note_before, session_note_after
    ) values (
      v_session.id, null, v_session.class_id, '', '',
      'session_note', v_uid, coalesce(v_profile.full_name, v_profile.email, ''), v_changed_at,
      '', '', '', '', '', '',
      v_session_note_before, v_session_note_after
    );
  end if;

  select
    count(*) filter (where r.status = 'present')::integer,
    count(*) filter (where r.status = 'absent')::integer
  into v_present, v_absent
  from public.bes_extra_attendance_records r
  where r.session_id = p_session_id;

  update public.bes_extra_attendance_sessions
  set total_students = v_present + v_absent,
      present_count = v_present,
      absent_count = v_absent,
      note = v_session_note_after
  where id = p_session_id
  returning * into v_session;

  -- checked_at is intentionally not changed: saving a correction must never
  -- restart or extend the teacher's 30-minute window.
  return v_session;
end;
$$;

revoke all on function private.bes_extra_attendance_edit_decision(uuid,timestamptz) from public;
revoke all on function private.bes_extra_attendance_edit_decision(uuid,timestamptz) from anon;
revoke all on function public.bes_get_extra_attendance_edit_access(uuid) from public;
revoke all on function public.bes_get_extra_attendance_edit_access(uuid) from anon;
revoke all on function public.bes_update_extra_attendance_session(uuid,jsonb,text) from public;
revoke all on function public.bes_update_extra_attendance_session(uuid,jsonb,text) from anon;

grant execute on function private.bes_extra_attendance_edit_decision(uuid,timestamptz) to authenticated;
grant execute on function public.bes_get_extra_attendance_edit_access(uuid) to authenticated;
grant execute on function public.bes_update_extra_attendance_session(uuid,jsonb,text) to authenticated;

comment on table public.bes_extra_attendance_record_changes is
  'Audit trail for post-confirm attendance corrections, including status/reason changes and session-note edits.';
comment on function public.bes_update_extra_attendance_session(uuid,jsonb,text) is
  'Updates a completed attendance snapshot without modifying checked_at. Teacher window: checked_at + 30 minutes; Admin/report bypass.';
