const ALLOWED_HOSTS = [
  'giaoducthoidai.vn', 'tuoitre.vn', 'thanhnien.vn', 'vnexpress.net', 'dantri.com.vn',
  'vietnamnet.vn', 'laodong.vn', 'nhandan.vn', 'baochinhphu.vn', 'vov.vn', 'vtv.vn',
  'giadinh.suckhoedoisong.vn', 'suckhoedoisong.vn',
  'bbc.com', 'bbc.co.uk', 'theguardian.com', 'voanews.com', 'reuters.com', 'apnews.com',
];

const ENTITY_MAP = { amp: '&', quot: '"', apos: "'", lt: '<', gt: '>', nbsp: ' ', ndash: '–', mdash: '—', hellip: '…', rsquo: '’', lsquo: '‘', ldquo: '“', rdquo: '”', copy: '©', reg: '®', bull: '•', middot: '·' };
const NOISE_PATTERNS = [/quảng cáo/i, /advertisement/i, /đăng ký nhận tin/i, /theo dõi chúng tôi/i, /chia sẻ bài viết/i, /bài viết liên quan/i, /tin liên quan/i, /xem thêm/i, /read more/i, /related stories/i, /cookie/i, /privacy policy/i, /terms of use/i, /newsletter/i, /sign up/i, /đăng nhập/i];

function decodeEntities(value = '') {
  return String(value).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1').replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code))).replace(/&#x([0-9a-f]+);/gi, (_, code) => String.fromCodePoint(parseInt(code, 16))).replace(/&([a-z]+);/gi, (all, key) => ENTITY_MAP[key.toLowerCase()] ?? all);
}
function stripTags(value = '') {
  return decodeEntities(value).replace(/<script[\s\S]*?<\/script>/gi, ' ').replace(/<style[\s\S]*?<\/style>/gi, ' ').replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ').replace(/<svg[\s\S]*?<\/svg>/gi, ' ').replace(/<br\s*\/?\s*>/gi, '\n').replace(/<\/p>/gi, '\n\n').replace(/<\/h[1-6]>/gi, '\n\n').replace(/<\/li>/gi, '\n').replace(/<[^>]+>/g, ' ').replace(/\r/g, '').replace(/[ \t]+/g, ' ').replace(/\n\s+/g, '\n').replace(/\n{3,}/g, '\n\n').trim();
}
function normalizeText(value = '') { return stripTags(value).replace(/\u00a0/g, ' ').replace(/[ \t]{2,}/g, ' ').replace(/\n{3,}/g, '\n\n').trim(); }
function allowedUrl(raw = '') { let url; try { url = new URL(raw); } catch { throw new Error('Invalid article URL'); } if (!['http:', 'https:'].includes(url.protocol)) throw new Error('Unsupported URL protocol'); const host = url.hostname.toLowerCase().replace(/^www\./, ''); if (!ALLOWED_HOSTS.some((item) => host === item || host.endsWith(`.${item}`))) throw new Error('Publisher is not supported'); return url; }
function absoluteUrl(value = '', baseUrl) { if (!value) return ''; try { const url = new URL(decodeEntities(value), baseUrl); return ['http:', 'https:'].includes(url.protocol) ? url.toString() : ''; } catch { return ''; } }
function getAttr(tag = '', attr = '') { const match = tag.match(new RegExp(`\\s${attr}\\s*=\\s*["']([^"']+)["']`, 'i')); return match ? decodeEntities(match[1]).trim() : ''; }
function removeElementBlocks(html = '', tag = '') { return html.replace(new RegExp(`<${tag}\\b[\\s\\S]*?<\\/${tag}>`, 'gi'), ' '); }
function cleanHtml(html = '') { let value = String(html || ''); ['script', 'style', 'noscript', 'svg', 'canvas', 'iframe', 'form', 'button', 'nav', 'footer', 'aside'].forEach((tag) => { value = removeElementBlocks(value, tag); }); return value.replace(/<!--([\s\S]*?)-->/g, ' ').replace(/<(div|section)[^>]*(?:class|id)=["'][^"']*(?:advert|ads?|banner|sidebar|related|recommend|social|share|comment|newsletter|cookie|paywall|subscription|promo|outbrain|taboola)[^"']*["'][^>]*>[\s\S]*?<\/\1>/gi, ' ').replace(/<header\b[\s\S]*?<\/header>/gi, ' '); }
function findMeta(html = '', property = '') { const escaped = property.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); const patterns = [new RegExp(`<meta[^>]+property=["']${escaped}["'][^>]+content=["']([^"']+)["'][^>]*>`, 'i'), new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+property=["']${escaped}["'][^>]*>`, 'i'), new RegExp(`<meta[^>]+name=["']${escaped}["'][^>]+content=["']([^"']+)["'][^>]*>`, 'i'), new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+name=["']${escaped}["'][^>]*>`, 'i')]; for (const pattern of patterns) { const match = html.match(pattern); if (match?.[1]) return decodeEntities(match[1]).trim(); } return ''; }

function articleJsonLd(html = '') {
  const scripts = [...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)];
  const candidates = [];
  const walk = (value) => { if (!value) return; if (Array.isArray(value)) { value.forEach(walk); return; } if (typeof value !== 'object') return; const type = Array.isArray(value['@type']) ? value['@type'].join(' ') : String(value['@type'] || ''); if (/article|newsarticle|reportage|blogposting/i.test(type) || typeof value.articleBody === 'string') candidates.push(value); if (value['@graph']) walk(value['@graph']); Object.values(value).forEach((child) => { if (child && typeof child === 'object' && child !== value['@graph']) walk(child); }); };
  for (const match of scripts) { const raw = decodeEntities(match[1]).trim().replace(/^\s*<!--|-->\s*$/g, ''); try { walk(JSON.parse(raw)); } catch { /* malformed */ } }
  return candidates.filter((item) => typeof item.articleBody === 'string' && normalizeText(item.articleBody).length > 220).sort((a, b) => normalizeText(b.articleBody).length - normalizeText(a.articleBody).length)[0] || null;
}
function findMatchingBlock(html, startIndex, tagName) { const openerEnd = html.indexOf('>', startIndex); if (openerEnd < 0) return ''; const tokenRegex = new RegExp(`<\\/?${tagName}\\b[^>]*>`, 'gi'); tokenRegex.lastIndex = startIndex; let depth = 0; let match; while ((match = tokenRegex.exec(html))) { const closing = /^<\//.test(match[0]); if (closing) depth -= 1; else if (!/\/\s*>$/.test(match[0])) depth += 1; if (depth === 0) return html.slice(startIndex, tokenRegex.lastIndex); } return html.slice(startIndex, Math.min(html.length, startIndex + 220000)); }
function classToken(tag = '') { return `${getAttr(tag, 'class')} ${getAttr(tag, 'id')}`.trim(); }
function candidateBlocks(html = '') {
  const starts = []; const tagRegex = /<(article|main|section|div)\b[^>]*>/gi; let match;
  while ((match = tagRegex.exec(html))) { const tagName = match[1].toLowerCase(); const token = classToken(match[0]); const useful = tagName === 'article' || tagName === 'main' || /article|story|content|body|detail|entry|post|main|cms|news|singular|page-content|detail-content|article-body/i.test(token); const noisy = /related|recommend|sidebar|share|social|comment|advert|ads?|footer|header|nav|menu|cookie|newsletter|promo|author-box/i.test(token); if (useful && !noisy) starts.push({ index: match.index, tagName, token }); if (starts.length > 120) break; }
  return starts.map((entry) => { const fragment = findMatchingBlock(html, entry.index, entry.tagName); const text = normalizeText(fragment); const pCount = (fragment.match(/<p\b/gi) || []).length; const headingCount = (fragment.match(/<h[2-4]\b/gi) || []).length; const imageCount = (fragment.match(/<img\b/gi) || []).length; const linkText = [...fragment.matchAll(/<a\b[^>]*>([\s\S]*?)<\/a>/gi)].reduce((sum, item) => sum + normalizeText(item[1]).length, 0); const linkDensity = text.length ? linkText / text.length : 1; const score = text.length + pCount * 170 + headingCount * 70 + Math.min(imageCount, 6) * 45 - Math.round(linkDensity * text.length * 1.1); return { ...entry, fragment, text, pCount, score }; }).filter((item) => item.text.length > 320 && item.pCount >= 2).sort((a, b) => b.score - a.score);
}
function isNoiseText(text = '') { const clean = text.trim(); if (!clean || clean.length < 3) return true; if (NOISE_PATTERNS.some((pattern) => pattern.test(clean)) && clean.length < 280) return true; return /^(facebook|twitter|email|copy link|zalo|print|share)$/i.test(clean); }
function pushTextBlock(blocks, type, rawText) { const text = normalizeText(rawText); if (isNoiseText(text) || (type === 'paragraph' && text.length < 18) || blocks.at(-1)?.text === text) return; blocks.push({ type, text }); }
function blocksFromHtml(fragment = '', baseUrl = '') {
  const cleaned = cleanHtml(fragment); const blocks = []; const blockRegex = /<(h[2-4]|p|blockquote|li|figure|img)\b[^>]*>([\s\S]*?)<\/\1>|<img\b[^>]*>/gi; let match;
  while ((match = blockRegex.exec(cleaned))) { const whole = match[0]; const type = (match[1] || 'img').toLowerCase(); if (type === 'img') { const src = absoluteUrl(getAttr(whole, 'src') || getAttr(whole, 'data-src') || getAttr(whole, 'data-original') || getAttr(whole, 'data-lazy-src'), baseUrl); if (src && !blocks.some((item) => item.type === 'image' && item.src === src)) blocks.push({ type: 'image', src, alt: getAttr(whole, 'alt') || '' }); continue; } if (type === 'figure') { const imgTag = whole.match(/<img\b[^>]*>/i)?.[0] || ''; const src = absoluteUrl(getAttr(imgTag, 'src') || getAttr(imgTag, 'data-src') || getAttr(imgTag, 'data-original') || getAttr(imgTag, 'data-lazy-src'), baseUrl); const caption = normalizeText(whole.match(/<figcaption\b[^>]*>([\s\S]*?)<\/figcaption>/i)?.[1] || ''); if (src && !blocks.some((item) => item.type === 'image' && item.src === src)) blocks.push({ type: 'image', src, alt: getAttr(imgTag, 'alt') || '', caption }); continue; } const rawText = match[2] || ''; if (/^h/.test(type)) pushTextBlock(blocks, 'heading', rawText); else if (type === 'blockquote') pushTextBlock(blocks, 'quote', rawText); else if (type === 'li') pushTextBlock(blocks, 'list', rawText); else pushTextBlock(blocks, 'paragraph', rawText); }
  if (blocks.filter((item) => item.text).length < 4) normalizeText(cleaned).split(/\n{2,}|(?<=[.!?…])\s+(?=[A-ZÀ-Ỹ])/).map((item) => item.trim()).filter((item) => item.length > 35).forEach((paragraph) => pushTextBlock(blocks, 'paragraph', paragraph));
  return blocks.slice(0, 360);
}
function blocksFromPlainText(text = '') { const normalized = normalizeText(text); let paragraphs = normalized.split(/\n{2,}/).map((item) => item.trim()).filter(Boolean); if (paragraphs.length < 2 && normalized.length > 520) { const sentences = normalized.match(/[^.!?…]+[.!?…]+(?:["”’']+)?|[^.!?…]+$/g) || [normalized]; paragraphs = []; for (let index = 0; index < sentences.length; index += 3) paragraphs.push(sentences.slice(index, index + 3).join(' ').trim()); } const blocks = []; paragraphs.forEach((paragraph) => pushTextBlock(blocks, 'paragraph', paragraph)); return blocks; }
function imageFromJsonLd(value, baseUrl) { if (!value) return ''; if (typeof value === 'string') return absoluteUrl(value, baseUrl); if (Array.isArray(value)) return imageFromJsonLd(value[0], baseUrl); if (typeof value === 'object') return absoluteUrl(value.url || value.contentUrl || '', baseUrl); return ''; }
function textFromBlocks(blocks = []) { return blocks.filter((item) => item.text).map((item) => item.text).join('\n\n').trim(); }
function wordCount(text = '') { return String(text || '').split(/\s+/).filter(Boolean).length; }
function extractFromHtml(html, url) {
  const jsonLd = articleJsonLd(html);
  if (jsonLd) { const blocks = blocksFromPlainText(jsonLd.articleBody); const text = textFromBlocks(blocks); if (wordCount(text) >= 80) return { title: normalizeText(jsonLd.headline || jsonLd.name || findMeta(html, 'og:title')), dek: normalizeText(jsonLd.description || findMeta(html, 'description') || findMeta(html, 'og:description')), author: normalizeText(typeof jsonLd.author === 'string' ? jsonLd.author : jsonLd.author?.name || jsonLd.author?.[0]?.name || ''), publishedAt: jsonLd.datePublished || jsonLd.dateModified || '', image: imageFromJsonLd(jsonLd.image, url) || absoluteUrl(findMeta(html, 'og:image'), url), blocks, text, method: 'publisher-jsonld' }; }
  const cleaned = cleanHtml(html); const best = candidateBlocks(cleaned)[0]; const fragment = best?.fragment || cleaned.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i)?.[1] || cleaned; const blocks = blocksFromHtml(fragment, url); const text = textFromBlocks(blocks);
  return { title: normalizeText(findMeta(html, 'og:title') || html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1] || ''), dek: normalizeText(findMeta(html, 'description') || findMeta(html, 'og:description')), author: normalizeText(findMeta(html, 'author')), publishedAt: findMeta(html, 'article:published_time') || '', image: absoluteUrl(findMeta(html, 'og:image'), url), blocks, text, method: best ? 'publisher-html' : 'publisher-body' };
}
function findAmpUrl(html = '', baseUrl = '') { const tag = html.match(/<link\b[^>]*rel=["']amphtml["'][^>]*>/i)?.[0] || html.match(/<link\b[^>]*href=["'][^"']+["'][^>]*rel=["']amphtml["'][^>]*>/i)?.[0] || ''; return absoluteUrl(getAttr(tag, 'href'), baseUrl); }
async function fetchText(url, { timeout = 15000, headers = {} } = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout); try { const response = await fetch(url, { signal: controller.signal, redirect: 'follow', headers: { 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/150 Safari/537.36', Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,text/plain;q=0.8,*/*;q=0.5', 'Accept-Language': 'vi-VN,vi;q=0.9,en-GB;q=0.8,en;q=0.7', 'Cache-Control': 'no-cache', ...headers } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return { text: await response.text(), finalUrl: response.url || String(url), contentType: response.headers.get('content-type') || '' }; } finally { clearTimeout(timer); } }
function markdownBlocks(markdown = '', baseUrl = '') {
  let body = String(markdown || '').replace(/\r/g, '').trim(); const marker = body.indexOf('Markdown Content:'); if (marker >= 0) body = body.slice(marker + 'Markdown Content:'.length).trim(); body = body.replace(/^Title:\s.*$/gmi, '').replace(/^URL Source:\s.*$/gmi, '').replace(/^Published Time:\s.*$/gmi, '').replace(/^Warning:\s.*$/gmi, '').replace(/^\[Skip to content\].*$/gmi, '').trim();
  const blocks = []; const lines = body.split('\n'); let paragraph = []; const flush = () => { const text = paragraph.join(' ').replace(/\s+/g, ' ').trim(); paragraph = []; if (text) pushTextBlock(blocks, 'paragraph', text.replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1').replace(/[*_`]/g, '')); };
  for (const raw of lines) { const line = raw.trim(); if (!line) { flush(); continue; } const image = line.match(/^!\[([^\]]*)\]\(([^\s\)]+)(?:\s+["'][^"']*["'])?\)$/); if (image) { flush(); const src = absoluteUrl(image[2], baseUrl); if (src) blocks.push({ type: 'image', src, alt: image[1] || '' }); continue; } const heading = line.match(/^#{1,4}\s+(.+)$/); if (heading) { flush(); pushTextBlock(blocks, 'heading', heading[1]); continue; } const quote = line.match(/^>\s*(.+)$/); if (quote) { flush(); pushTextBlock(blocks, 'quote', quote[1]); continue; } const list = line.match(/^[-*+]\s+(.+)$/) || line.match(/^\d+\.\s+(.+)$/); if (list) { flush(); pushTextBlock(blocks, 'list', list[1]); continue; } if (/^[-=_]{3,}$/.test(line)) { flush(); continue; } paragraph.push(line); }
  flush(); return blocks.slice(0, 420);
}
async function fetchJinaReader(url) { const result = await fetchText(`https://r.jina.ai/${url}`, { timeout: 20000, headers: { Accept: 'text/markdown,text/plain;q=0.9,*/*;q=0.5', 'X-Return-Format': 'markdown', 'X-Remove-Selector': 'header,footer,nav,aside,form,.advertisement,.ads,.related,.comments,.share,.social', 'X-With-Generated-Alt': 'true' } }); const blocks = markdownBlocks(result.text, url); return { blocks, text: textFromBlocks(blocks), method: 'reader-service' }; }
function bodyItem(req) { const body = req.body && typeof req.body === 'object' ? req.body : {}; const query = req.query || {}; return { url: String(body.url || query.url || ''), source: String(body.source || query.source || '').slice(0, 100), title: String(body.title || ''), summary: String(body.summary || ''), content: String(body.content || ''), image: String(body.image || ''), author: String(body.author || ''), publishedAt: String(body.publishedAt || '') }; }
function candidateScore(article) { const words = wordCount(article?.text || ''); const headings = (article?.blocks || []).filter((item) => item.type === 'heading').length; const images = (article?.blocks || []).filter((item) => item.type === 'image').length; return words * 10 + headings * 30 + Math.min(images, 5) * 15; }
function responsePayload({ article, url, publisher, fallbackWords }) { const text = article.text || textFromBlocks(article.blocks || []); const count = wordCount(text); return { url, publisher: publisher || new URL(url).hostname.replace(/^www\./, ''), title: article.title || '', dek: article.dek || '', author: article.author || '', publishedAt: article.publishedAt || '', image: article.image || '', blocks: article.blocks || [], text, wordCount: count, readingMinutes: Math.max(1, Math.ceil(count / 190)), full: count >= Math.max(100, Math.round((fallbackWords || 0) * 1.25)), method: article.method || 'unknown', fetchedAt: new Date().toISOString() }; }

export default async function handler(req, res) {
  if (!['GET', 'POST'].includes(req.method)) { res.setHeader('Allow', 'GET, POST'); return res.status(405).json({ error: 'Method not allowed' }); }
  const item = bodyItem(req); let url; try { url = allowedUrl(item.url); } catch (error) { return res.status(400).json({ error: error.message || 'Invalid URL' }); }
  const attempts = []; const candidates = []; const fallbackText = normalizeText(item.content || item.summary || ''); const fallbackBlocks = blocksFromPlainText(fallbackText); const fallbackWords = wordCount(fallbackText);
  if (fallbackWords >= 15) candidates.push({ title: item.title, dek: item.summary, author: item.author || item.source, publishedAt: item.publishedAt, image: item.image, blocks: fallbackBlocks, text: fallbackText, method: 'feed-fallback' });
  const [directResult, readerResult] = await Promise.allSettled([fetchText(url.toString()), fetchJinaReader(url.toString())]);
  if (readerResult.status === 'fulfilled') { attempts.push({ method: readerResult.value.method, words: wordCount(readerResult.value.text) }); candidates.push({ ...readerResult.value, title: item.title, dek: item.summary, author: item.author || item.source, publishedAt: item.publishedAt, image: item.image }); } else attempts.push({ method: 'reader-error', error: readerResult.reason?.name === 'AbortError' ? 'timeout' : readerResult.reason?.message || 'reader failed' });
  if (directResult.status === 'fulfilled') { const direct = directResult.value; const extracted = extractFromHtml(direct.text, direct.finalUrl); attempts.push({ method: extracted.method, words: wordCount(extracted.text) }); candidates.push(extracted); if (wordCount(extracted.text) < 260) { const ampUrl = findAmpUrl(direct.text, direct.finalUrl); if (ampUrl) { try { const amp = await fetchText(ampUrl, { timeout: 12000 }); const ampArticle = extractFromHtml(amp.text, amp.finalUrl); attempts.push({ method: `${ampArticle.method}-amp`, words: wordCount(ampArticle.text) }); candidates.push({ ...ampArticle, method: `${ampArticle.method}-amp` }); } catch (ampError) { attempts.push({ method: 'amp-error', error: ampError?.message || 'AMP fetch failed' }); } } } } else attempts.push({ method: 'publisher-error', error: directResult.reason?.name === 'AbortError' ? 'timeout' : directResult.reason?.message || 'fetch failed' });
  const best = candidates.filter((entry) => wordCount(entry?.text || '') >= 15).sort((a, b) => candidateScore(b) - candidateScore(a))[0];
  if (!best) { res.setHeader('Cache-Control', 'no-store'); return res.status(502).json({ error: 'Article content could not be loaded at the moment.', attempts }); }
  res.setHeader('Cache-Control', 's-maxage=1200, stale-while-revalidate=21600');
  return res.status(200).json({ ...responsePayload({ article: best, url: url.toString(), publisher: item.source, fallbackWords }), attempts });
}
